export interface Achievement {
  id: string;
  name: string;
  description: string;
  condition: (player: any, monster: any, stats?: any) => boolean;
}

export const ACHIEVEMENTS_LIST: Achievement[] = [
  { id: "first_blood", name: "Primeira Vitória", description: "Derrote o primeiro monstro.", condition: (p) => p.monstersDefeated >= 1 },
  { id: "slayer_10", name: "Caçador Aprendiz", description: "Derrote 10 monstros.", condition: (p) => p.monstersDefeated >= 10 },
  { id: "slayer_50", name: "Caçador Experiente", description: "Derrote 50 monstros.", condition: (p) => p.monstersDefeated >= 50 },
  { id: "slayer_100", name: "Lenda Viva", description: "Derrote 100 monstros.", condition: (p) => p.monstersDefeated >= 100 },
  { id: "level_5", name: "Ganhando Poder", description: "Alcance o Nível 5.", condition: (p) => p.level >= 5 },
  { id: "level_15", name: "Mago Habilidoso", description: "Alcance o Nível 15.", condition: (p) => p.level >= 15 },
  { id: "level_30", name: "Arquimago", description: "Alcance o Nível 30.", condition: (p) => p.level >= 30 },
  { id: "level_50", name: "Deus da Magia", description: "Alcance o Nível 50.", condition: (p) => p.level >= 50 },
  { id: "boss_slayer_1", name: "Derrubando Gigantes", description: "Derrote o primeiro chefe.", condition: (_, __, s) => s?.bossesDefeated >= 1 },
  { id: "boss_slayer_5", name: "Mata-Gigantes", description: "Derrote 5 chefes.", condition: (_, __, s) => s?.bossesDefeated >= 5 },
  { id: "fire_master", name: "Piromante", description: "Use feitiços de Fogo 20 vezes.", condition: (_, __, s) => s?.spellsCast?.fire >= 20 },
  { id: "water_master", name: "Hidromante", description: "Use feitiços de Água 20 vezes.", condition: (_, __, s) => s?.spellsCast?.water >= 20 },
  { id: "nature_master", name: "Druida", description: "Use feitiços de Natureza 20 vezes.", condition: (_, __, s) => s?.spellsCast?.nature >= 20 },
  { id: "light_master", name: "Clérigo", description: "Use feitiços de Luz 20 vezes.", condition: (_, __, s) => s?.spellsCast?.light >= 20 },
  { id: "void_master", name: "Conjurador do Vazio", description: "Use feitiços do Vazio 20 vezes.", condition: (_, __, s) => s?.spellsCast?.void >= 20 },
  { id: "heal_50", name: "Curandeiro", description: "Cure-se 50 vezes.", condition: (_, __, s) => s?.totalHeals >= 50 },
  { id: "shiny_hunter", name: "Caçador de Raridades", description: "Derrote um monstro Shiny.", condition: (_, __, s) => s?.shiniesDefeated >= 1 },
  { id: "shiny_hunter_5", name: "Colecionador", description: "Derrote 5 monstros Shiny.", condition: (_, __, s) => s?.shiniesDefeated >= 5 },
  { id: "death_1", name: "É Apenas o Começo", description: "Morra pela primeira vez.", condition: (_, __, s) => s?.deaths >= 1 },
  { id: "death_10", name: "Não Desista", description: "Morra 10 vezes.", condition: (_, __, s) => s?.deaths >= 10 },
  { id: "spell_1", name: "Iniciado nas Arcanas", description: "Conjure feitiços 30 vezes com sucesso.", condition: (_, __, s) => s?.totalSpellsCast >= 30 },
  { id: "spell_100", name: "Conhecimento Básico", description: "Conclure feitiços 100 vezes.", condition: (_, __, s) => s?.totalSpellsCast >= 100 },
  { id: "spell_500", name: "Dicionário Ambulante", description: "Conclure feitiços 500 vezes.", condition: (_, __, s) => s?.totalSpellsCast >= 500 },
  { id: "spell_1000", name: "Senhor das Palavras", description: "Conclure feitiços 1000 vezes.", condition: (_, __, s) => s?.totalSpellsCast >= 1000 },
  { id: "damage_1k", name: "Bateu Forte", description: "Cause 5.000 de dano total.", condition: (_, __, s) => s?.totalDamageDealt >= 5000 },
  { id: "damage_10k", name: "Destruidor", description: "Cause 20.000 de dano total.", condition: (_, __, s) => s?.totalDamageDealt >= 20000 },
  { id: "damage_100k", name: "Cataclismo", description: "Cause 100.000 de dano total.", condition: (_, __, s) => s?.totalDamageDealt >= 100000 },
  { id: "damage_1m", name: "Dano Massivo", description: "Cause 1.000.000 de dano total.", condition: (_, __, s) => s?.totalDamageDealt >= 1000000 },
  { id: "survivor", name: "Sobrevivente", description: "Vença uma batalha com menos de 5% de HP.", condition: (p, m) => m && m.currentHp <= 0 && p.hp > 0 && p.hp < p.maxHp * 0.05 },
  { id: "flawless", name: "Intocável", description: "Vença uma batalha sem receber dano.", condition: (_, __, s) => s?.flawlessVictories >= 1 },
  { id: "bonus_1", name: "Atacando o Ponto Fraco", description: "Atinja o elemento bônus 1 vez.", condition: (_, __, s) => s?.totalBonusHits >= 1 },
  { id: "bonus_50", name: "Estrategista", description: "Atinja o elemento bônus 50 vezes.", condition: (_, __, s) => s?.totalBonusHits >= 50 },
  { id: "shield_master", name: "Muralha", description: "Use feitiços de Escudo 20 vezes.", condition: (_, __, s) => s?.totalShields >= 20 },
  { id: "status_dealer", name: "Mestre dos Debuffs", description: "Cause status negativos 50 vezes.", condition: (_, __, s) => s?.statusApplied >= 50 },
  { id: "status_cleansed", name: "Puro", description: "Purifique-se 10 vezes.", condition: (_, __, s) => s?.statusCleansed >= 10 },
  { id: "thunder_master", name: "Senhor dos Raios", description: "Use feitiços de Trovão 20 vezes.", condition: (_, __, s) => s?.spellsCast?.thunder >= 20 },
  { id: "wind_master", name: "Mestre dos Ventos", description: "Use feitiços de Vento 20 vezes.", condition: (_, __, s) => s?.spellsCast?.wind >= 20 },
  { id: "physical_master", name: "Guerreiro Mágico", description: "Use feitiços Físicos 20 vezes.", condition: (_, __, s) => s?.spellsCast?.physical >= 20 },
  { id: "arcane_master", name: "Arcanista", description: "Use feitiços Arcanos 20 vezes.", condition: (_, __, s) => s?.spellsCast?.arcane >= 20 },
  { id: "earth_master", name: "Geomante", description: "Use feitiços de Terra 20 vezes.", condition: (_, __, s) => s?.spellsCast?.earth >= 20 },
  { id: "ice_master", name: "Criomante", description: "Use feitiços de Gelo 20 vezes.", condition: (_, __, s) => s?.spellsCast?.ice >= 20 },
  { id: "metal_master", name: "Mano de Ferro", description: "Use feitiços de Metal 20 vezes.", condition: (_, __, s) => s?.spellsCast?.metal >= 20 },
  { id: "blood_master", name: "Hemomante", description: "Use feitiços de Sangue 20 vezes.", condition: (_, __, s) => s?.spellsCast?.blood >= 20 },
  { id: "cosmos_master", name: "Astrologiano", description: "Use feitiços Solares/Cósmicos 20 vezes.", condition: (_, __, s) => s?.spellsCast?.cosmos >= 20 },
  { id: "music_master", name: "Bardo", description: "Use feitiços de Música 20 vezes.", condition: (_, __, s) => s?.spellsCast?.music >= 20 },
  { id: "time_master", name: "Cronos", description: "Use feitiços de Tempo 20 vezes.", condition: (_, __, s) => s?.spellsCast?.time >= 20 },
  { id: "immortal", name: "Imortal", description: "Alcance 10.000 de Vida Máxima.", condition: (p) => p.maxHp >= 10000 },
  { id: "one_shot", name: "Soco Inglês", description: "Derrote um monstro com apenas um ataque.", condition: (_, __, s) => s?.oneShots >= 1 },
  { id: "no_miss", name: "Precisão", description: "Acerte 10 feitiços consecutivos sem errar o idioma.", condition: (_, __, s) => s?.consecutiveHits >= 10 },
  { id: "god_slayer", name: "Destruidor de Deuses", description: "Derrote o Deus da Destruição.", condition: (_, __, s) => s?.godDefeated >= 1 }
];
