import { ElementType, StatusType } from './types';

export const ELEMENTS_INFO: Record<ElementType, { name: string; icon: string; color: string; bg: string; description: string }> = {
  fire: { name: 'Fogo', icon: '🔥', color: '#8b0000', bg: '#f9f3e5', description: 'Causa dano adicional ao longo do tempo (queimadura).' },
  water: { name: 'Água', icon: '🌊', color: '#1e3a8a', bg: '#f9f3e5', description: 'Fluxo contínuo, magias de ataque focadas.' },
  thunder: { name: 'Trovão', icon: '⚡', color: '#854d0e', bg: '#f9f3e5', description: 'Pode paralisar o inimigo, impedindo suas ações.' },
  wind: { name: 'Vento', icon: '🌪️', color: '#134e4a', bg: '#f9f3e5', description: 'Ataques rápidos e consistentes.' },
  nature: { name: 'Natureza', icon: '🌿', color: '#14532d', bg: '#f9f3e5', description: 'Ataques que podem usar veneno ou curar.' },
  physical: { name: 'Físico', icon: '⚔️', color: '#334155', bg: '#f9f3e5', description: 'Golpes marciais e poder cru. Pode causar sangramento.' },
  light: { name: 'Luz & Cura', icon: '✨', color: '#b45309', bg: '#f9f3e5', description: 'Magias focadas em cura, escudo e aumento de atributos.' },
  arcane: { name: 'Arcano', icon: '🔮', color: '#4c1d95', bg: '#f9f3e5', description: 'Magia pura, altera a realidade e causa alto dano.' },
  void: { name: 'Vazio & Tempo', icon: '🌌', color: '#312e81', bg: '#f9f3e5', description: 'Manipula o espaço-tempo para debuffs.' },
  utility: { name: 'Utilitário', icon: '🧪', color: '#713f12', bg: '#f9f3e5', description: 'Meta-conhecimento, auxílio na conjuração e revelação de segredos.' },
  time: { name: 'Tempo', icon: '⏳', color: '#312e81', bg: '#f9f3e5', description: 'Altera o fluxo e as recargas das magias.' },
  music: { name: 'Música', icon: '🎵', color: '#4c1d95', bg: '#f9f3e5', description: 'Feitiços que causam status negativos e dano.' },
  earth: { name: 'Terra', icon: '🪨', color: '#57534e', bg: '#f9f3e5', description: 'Magias pesadas, de resistência, causar lentidão ou fraqueza.' },
  ice: { name: 'Gelo', icon: '❄️', color: '#0ea5e9', bg: '#f9f3e5', description: 'Pode congelar o alvo, impedindo a ação no turno.' },
  metal: { name: 'Metal', icon: '⚙️', color: '#71717a', bg: '#f9f3e5', description: 'Armas conjuradas, dano físico intenso.' },
  blood: { name: 'Sangue', icon: '🩸', color: '#991b1b', bg: '#f9f3e5', description: 'Sacrifícios ou feitiços necromânticos que sugam vida.' },
  cosmos: { name: 'Cosmos', icon: '🌌', color: '#1e1b4b', bg: '#f9f3e5', description: 'Feitiços de destruição massiva de alto nível.' }
};

export const STATUS_ICONS: Record<StatusType, string> = {
  burn: '🔥', bleed: '🩸', freeze: '❄️', paralyze: '⚡', weaken: '💧', shield: '🛡️', regen: '✨', poison: '🤢', blind: '👁️', silence: '🤐',
  hint: '💡', cleanse: '✨', reduce_cd: '⏳', force_bonus: '🎯', damage_buff: '💪',
  reveal_combo: '🔍', reveal_2_combos: '🔭', predict_attack: '🔮', show_weakness: '🎯', boss_eye: '👁️',
  echo_next: '📢', autocomplete_next: '⌨️', ignore_typo_next: '🛡️', combo_window_up: '⏱️'
};

export const STATUS_NAMES_PT: Record<StatusType, string> = {
  burn: 'Queimadura', bleed: 'Sangramento', freeze: 'Congelamento', paralyze: 'Paralisia', weaken: 'Fraqueza', shield: 'Escudo', regen: 'Regeneração', poison: 'Veneno', blind: 'Cegueira', silence: 'Selado',
  hint: 'Dica', cleanse: 'Purificação', reduce_cd: 'Recarga', force_bonus: 'Ponto Fraco', damage_buff: 'Aumento de Dano',
  reveal_combo: 'Revelar Combo', reveal_2_combos: 'Revelar 2 Combos', predict_attack: 'Previsão', show_weakness: 'Ver Fraqueza', boss_eye: 'Olho do Chefe',
  echo_next: 'Eco Próximo', autocomplete_next: 'Autocompletar', ignore_typo_next: 'Escudo de Letras', combo_window_up: 'Janela Estendida'
};

export const FLAVOR_WORDS: Record<string, { t: string; r: string }> = {
  'baka': { t: 'Idiota', r: 'Quem você está chamando de idiota?! 💢' },
  'aho': { t: 'Estúpido', r: 'Olhe para você antes de falar! 🙄' },
  'shine': { t: 'Morra', r: 'Vem tentar a sorte! 🔪' },
  'kuso': { t: 'Droga', r: 'Frustrado? Que pena... 😈' },
  'nani': { t: 'O quê?', r: 'Isso mesmo que você ouviu! 🗣️' },
  'yamete': { t: 'Pare', r: 'Eu nunca vou parar! ⚔️' },
  'tasukete': { t: 'Socorro', r: 'Ninguém virá te salvar! 🕸️' },
  'kawaii': { t: 'Fofo', r: 'N-Não me chame de fofo! 😳' },
  'gomen': { t: 'Desculpa', r: 'É tarde demais para perdão! 🗡️' },
  'omae': { t: 'Você', r: 'Eu?! O que tem eu?! 🤨' },
  'dorobou': { t: 'Ladrão', r: 'Achado não é roubado! 🏃‍♂️💨' },
  'yowai': { t: 'Fraco', r: 'Vou te mostrar quem é o fraco! 💥' },
  'konnichiwa': { t: 'Olá', r: 'Não temos tempo para cumprimentos! ⚔️' },
  'arigatou': { t: 'Obrigado', r: 'Não agradeça por sua ruína! 💀' },
  'sayounara': { t: 'Adeus', r: 'Adeus para sempre, herói tolo! 👋' },
  'kakkoii': { t: 'Legal', r: 'Humph, eu sei que sou estiloso! 😎' },
  'sugoi': { t: 'Incrível', r: 'Impressionado com o meu poder?! 🌠' },
  'yabai': { t: 'Perigoso', r: 'Você que corre perigo real! ⚠️' },
  'kimoi': { t: 'Nojento', r: 'Olha para a sua cara! 🤮' },
  'uzai': { t: 'Irritante', r: 'Vou ser ainda mais irritante! 🦟' },
  'urusai': { t: 'Barulhento', r: 'VOU GRITAR MAIS ALTO! 📢' },
  'damare': { t: 'Cale-se', r: 'Me obrigue a calar a boca! 🤐' },
  'chotto': { t: 'Um pouco', r: 'Nem um segundo de pausa! ⏱️' },
  'matte': { t: 'Espere', r: 'Monstros não esperam! 🏃‍♂️' },
  'hayaku': { t: 'Rápido', r: 'Estou indo te destruir! 🌪️' },
  'nigero': { t: 'Fuja', r: 'Não há para onde fugir! 🚪🔒' },
  'kowai': { t: 'Assustador', r: 'Sinta o terror! 👻' },
  'itai': { t: 'Dói', r: 'Vai doer muito mais! 🩸' },
  'kurushii': { t: 'Doloroso', r: 'Sofra sob o meu poder! 😈' },
  'sumimasen': { t: 'Com licença', r: 'Sem licença para fracos! 🛑' },
  'muda': { t: 'Inútil', r: 'MUDA MUDA MUDA! 👊' },
  'zako': { t: 'Lixo', r: 'Eu sou a elite das trevas! 👑' }
};

export const ENEMY_SKILLS_POOL: Record<string, any> = {
  'heal': { name: 'Cura Regenerativa', type: 'heal', mult: 0.2 }, 
  'burn': { name: 'Sopro de Fogo', type: 'status', effect: 'burn', duration: 3 },
  'poison': { name: 'Névoa Venenosa', type: 'status', effect: 'poison', duration: 4 },
  'paralyze': { name: 'Olhar Eletrizante', type: 'status', effect: 'paralyze', duration: 1 },
  'weaken': { name: 'Fraqueza', type: 'status', effect: 'weaken', duration: 3 },
  'shield': { name: 'Pele de Ferro', type: 'status', effect: 'shield', duration: 3 },
  'lifesteal': { name: 'Drenar Vida', type: 'lifesteal', mult: 1.0 }, 
  'critical': { name: 'Ataque Brutal', type: 'attack', mult: 2.0 }, 
  'summon': { name: 'Lacaio', type: 'summon', mult: 0.3 }, 
  'blind': { name: 'Cegueira', type: 'status', effect: 'blind', duration: 2 },
  'seal': { name: 'Selo do Conhecimento', type: 'status', effect: 'silence', duration: 4 },
  'silence_song': { name: 'Canção do Silêncio', type: 'status', effect: 'silence', duration: 2 },
  'heavy_strike': { name: 'Golpe Pesado', type: 'attack', mult: 1.8 },
  'void_gaze': { name: 'Olhar do Vazio', type: 'status', effect: 'weaken', duration: 4 },
  'freeze': { name: 'Nevasca', type: 'status', effect: 'freeze', duration: 2 },
  'corrupt': { name: 'Toque Corrupto', type: 'status', effect: 'poison', duration: 5 },
  'quake': { name: 'Terremoto', type: 'attack', mult: 1.5 },
  'tsunami': { name: 'Tsunami', type: 'attack', mult: 1.4 },
  'thunderstorm': { name: 'Tempestade de Raios', type: 'attack', mult: 1.6 },
  'tornado': { name: 'Tornado Destrutivo', type: 'attack', mult: 1.3 },
  'meteor': { name: 'Chuva de Meteoros', type: 'attack', mult: 2.5 },
  'light_ray': { name: 'Feixe de Luz', type: 'attack', mult: 1.2 },
  'mind_control': { name: 'Controle Mental', type: 'status', effect: 'paralyze', duration: 2 },
  'bleed_bite': { name: 'Mordida Profunda', type: 'status', effect: 'bleed', duration: 4 },
  'blood_rain': { name: 'Chuva de Sangue', type: 'lifesteal', mult: 1.5 },
  'time_stop': { name: 'Parar o Tempo', type: 'status', effect: 'freeze', duration: 3 },
  'acid_spit': { name: 'Cuspe Ácido', type: 'status', effect: 'weaken', duration: 5 },
  'inferno': { name: 'Inferno', type: 'status', effect: 'burn', duration: 6 },
  'frostbite': { name: 'Mordida Gélida', type: 'status', effect: 'freeze', duration: 1 },
  'earth_wall': { name: 'Parede de Terra', type: 'status', effect: 'shield', duration: 4 },
  'divine_shield': { name: 'Escudo Divino', type: 'status', effect: 'shield', duration: 5 },
  'dark_matter': { name: 'Matéria Escura', type: 'attack', mult: 2.2 },
  'solar_flare': { name: 'Erupção Solar', type: 'attack', mult: 1.9 },
  'lunar_eclipse': { name: 'Eclipse Lunar', type: 'status', effect: 'blind', duration: 4 },
  'venom_stinger': { name: 'Ferrão Venenoso', type: 'status', effect: 'poison', duration: 3 },
  'ghost_touch': { name: 'Toque Fantasma', type: 'status', effect: 'weaken', duration: 2 },
  'death_scythe': { name: 'Foice da Morte', type: 'attack', mult: 3.0 },
  'soul_drain': { name: 'Drenar Alma', type: 'lifesteal', mult: 2.0 },
  'illusion': { name: 'Ilusão', type: 'status', effect: 'blind', duration: 3 },
  'mirror_image': { name: 'Imagem Espelhada', type: 'status', effect: 'shield', duration: 2 },
  'roar': { name: 'Rugido Aterrorizante', type: 'status', effect: 'paralyze', duration: 1 },
  'sonic_boom': { name: 'Estrondo Sônico', type: 'attack', mult: 1.5 },
  'laser_beam': { name: 'Feixe de Laser', type: 'attack', mult: 1.7 },
  'crystal_prison': { name: 'Prisão de Cristal', type: 'status', effect: 'freeze', duration: 2 },
  'shadow_strike': { name: 'Golpe Sombrio', type: 'attack', mult: 1.4 },
  'holy_light': { name: 'Luz Sagrada', type: 'heal', mult: 0.5 },
  'demonic_aura': { name: 'Aura Demoníaca', type: 'status', effect: 'weaken', duration: 5 },
  'vampiric_bite': { name: 'Mordida Vampírica', type: 'lifesteal', mult: 1.2 },
  'toxic_spores': { name: 'Esporos Tóxicos', type: 'status', effect: 'poison', duration: 5 },
  'curse': { name: 'Maldição Profunda', type: 'status', effect: 'silence', duration: 3 },
  'nightmare': { name: 'Pesadelo', type: 'status', effect: 'weaken', duration: 4 }
};

export const SEQUENCE_BONUSES = [
  // --- TIER 1: ELEMENTAL PAIRS (2-Spells) ---
  { id: 'fire_wind', sequence: ['fire', 'wind'], name: 'Tempestade de Chamas', bonus: 'damage', mult: 1.6, msg: 'O vento alimenta o incêndio!' },
  { id: 'water_ice', sequence: ['water', 'ice'], name: 'Nevasca Prateada', bonus: 'paralyze', duration: 1, msg: 'A água congela instantaneamente!' },
  { id: 'earth_physical', sequence: ['earth', 'physical'], name: 'Impacto Vulcânico', bonus: 'damage', mult: 1.7, msg: 'A terra treme sob seus pés!' },
  { id: 'light_arcane', sequence: ['light', 'arcane'], name: 'Iluminação Arcana', bonus: 'reduce_cd', msg: 'Conhecimento puro flui em sua mente!' },
  { id: 'nature_water', sequence: ['nature', 'water'], name: 'Crescimento Acelerado', bonus: 'regen', duration: 4, msg: 'A umidade desperta as raízes!' },
  { id: 'thunder_metal', sequence: ['thunder', 'metal'], name: 'Supercondução', bonus: 'damage', mult: 1.8, msg: 'O metal amplifica o choque!' },
  { id: 'blood_fire', sequence: ['blood', 'fire'], name: 'Inferno de Sangue', bonus: 'damage', mult: 1.9, msg: 'O sangue ferve em chamas negras!' },
  { id: 'void_time', sequence: ['void', 'time'], name: 'Abismo Temporal', bonus: 'paralyze', duration: 2, msg: 'O tempo para no vácuo!' },
  { id: 'music_wind', sequence: ['music', 'wind'], name: 'Sinfonia dos Ventos', bonus: 'damage', mult: 1.5, msg: 'As notas viajam na brisa!' },
  { id: 'metal_fire', sequence: ['metal', 'fire'], name: 'Forja Ardente', bonus: 'damage', mult: 1.7, msg: 'Lâminas moldadas no calor!' },
  { id: 'ice_thunder', sequence: ['ice', 'thunder'], name: 'Choque Críptico', bonus: 'damage', mult: 1.6, msg: 'Eletricidade estática no gelo!' },
  { id: 'cosmos_void', sequence: ['cosmos', 'void'], name: 'Colapso Estelar', bonus: 'damage', mult: 2.1, msg: 'Uma estrela morre no vazio!' },
  { id: 'utility_light', sequence: ['utility', 'light'], name: 'Bênção do Suporte', bonus: 'shield', duration: 4, msg: 'Proteção divina reforçada!' },
  { id: 'nature_earth', sequence: ['nature', 'earth'], name: 'Floresta Petrificada', bonus: 'damage', mult: 1.7, msg: 'A força da terra nas plantas!' },
  { id: 'physical_wind', sequence: ['physical', 'wind'], name: 'Golpe Vendaval', bonus: 'damage', mult: 1.6, msg: 'Ataque veloz como o vento!' },
  { id: 'fire_arcane', sequence: ['fire', 'arcane'], name: 'Chama de Prometeu', bonus: 'damage', mult: 2.0, msg: 'Fogo mágico proibido!' },

  // --- TIER 2: PRIMARY TRIPLES (3-Spells) ---
  { id: 'fire_3', sequence: ['fire', 'fire', 'fire'], name: 'Erupção Carmesim', bonus: 'damage', mult: 1.8, msg: 'A chama se intensifica!' },
  { id: 'water_3', sequence: ['water', 'water', 'water'], name: 'Fluxo Eterno', bonus: 'heal', mult: 1.6, msg: 'As águas te purificam!' },
  { id: 'thunder_3', sequence: ['thunder', 'thunder', 'thunder'], name: 'Juízo do Relâmpago', bonus: 'paralyze', duration: 2, msg: 'O trovão ruge!' },
  { id: 'light_3', sequence: ['light', 'light', 'light'], name: 'Aura do Redentor', bonus: 'shield', duration: 5, msg: 'Uma luz divina te protege!' },
  { id: 'physical_3', sequence: ['physical', 'physical', 'physical'], name: 'Combo Devastador', bonus: 'damage', mult: 2.2, msg: 'Uma sequência de golpes perfeitos!' },
  { id: 'nature_3', sequence: ['nature', 'nature', 'nature'], name: 'Dom da Floresta', bonus: 'regen', duration: 6, msg: 'A natureza pulsa em você!' },
  { id: 'arcane_3', sequence: ['arcane', 'arcane', 'arcane'], name: 'Supernova Arcana', bonus: 'damage', mult: 2.5, msg: 'Explosão de mana pura!' },
  { id: 'void_3', sequence: ['void', 'void', 'void'], name: 'Singularidade', bonus: 'damage', mult: 2.8, msg: 'Tudo é sugado pelo vazio!' },
  { id: 'ice_3', sequence: ['ice', 'ice', 'ice'], name: 'Zero Absoluto', bonus: 'paralyze', duration: 3, msg: 'O movimento cessa completamente!' },
  { id: 'earth_3', sequence: ['earth', 'earth', 'earth'], name: 'Sismo do Olimpo', bonus: 'damage', mult: 2.1, msg: 'O mundo se racha ao meio!' },
  { id: 'trinity', sequence: ['fire', 'water', 'thunder'], name: 'Trindade Elemental', bonus: 'damage', mult: 2.4, msg: 'O poder dos elementos converge!' },

  // --- TIER 3: COMPLEX COMBINATIONS (3-Spells Mix) ---
  { id: 'fire_water_ice', sequence: ['fire', 'water', 'ice'], name: 'Fúria do Vapor Frio', bonus: 'damage', mult: 2.0, msg: 'Mudança brusca de temperatura!' },
  { id: 'light_shield_regen', sequence: ['light', 'nature', 'light'], name: 'Santuário Vivo', bonus: 'shield', duration: 6, msg: 'Uma barreira que se cura sozinha!' },
  { id: 'time_void_arcane', sequence: ['time', 'void', 'arcane'], name: 'Fissão da Realidade', bonus: 'damage', mult: 2.7, msg: 'As leis da física se desfazem!' },
  { id: 'blood_arcane_void', sequence: ['blood', 'arcane', 'void'], name: 'Ritual do Abismo', bonus: 'damage', mult: 3.0, msg: 'Sacrifício por poder proibido!' },
  { id: 'metal_physical_thunder', sequence: ['metal', 'physical', 'thunder'], name: 'Maça de Mjolnir', bonus: 'damage', mult: 2.6, msg: 'Peso e eletricidade devastadores!' },
  { id: 'music_time_music', sequence: ['music', 'time', 'music'], name: 'Roda do Destino', bonus: 'reduce_cd', msg: 'A canção que volta no tempo!' },
  { id: 'cosmos_light_cosmos', sequence: ['cosmos', 'light', 'cosmos'], name: 'Big Bang Galático', bonus: 'damage', mult: 3.2, msg: 'Criação e destruição em um só golpe!' },
  { id: 'fire_earth_metal', sequence: ['fire', 'earth', 'metal'], name: 'Chuva de Magma', bonus: 'damage', mult: 2.3, msg: 'Metal derretido do núcleo da terra!' },
  { id: 'wind_ice_wind', sequence: ['wind', 'ice', 'wind'], name: 'Furacão Glacial', bonus: 'paralyze', duration: 2, msg: 'Frio cortante imparável!' },
  { id: 'nature_utility_nature', sequence: ['nature', 'utility', 'nature'], name: 'Éden Restaurado', bonus: 'regen', duration: 8, msg: 'Cura definitiva da floresta!' },
  
  // --- TIER 4: THEMATIC CHAINS (Specific mix) ---
  { id: 'physical_fire_physical', sequence: ['physical', 'fire', 'physical'], name: 'Punho do Dragão', bonus: 'damage', mult: 2.3, msg: 'Chamas nos golpes físicos!' },
  { id: 'water_thunder_wind', sequence: ['water', 'thunder', 'wind'], name: 'Ciclone Elétrico', bonus: 'damage', mult: 2.2, msg: 'Uma tempestade perfeita!' },
  { id: 'void_blood_time', sequence: ['void', 'blood', 'time'], name: 'Gênese Sombria', bonus: 'heal', mult: 2.0, msg: 'Vida extraída do próprio vácuo!' },
  { id: 'metal_metal_fire', sequence: ['metal', 'metal', 'fire'], name: 'Arsenal Infinito', bonus: 'damage', mult: 2.5, msg: 'Chuva de espadas incandescentes!' },
  { id: 'arcane_light_arcane', sequence: ['arcane', 'light', 'arcane'], name: 'Veredito Sagrado', bonus: 'damage', mult: 2.8, msg: 'O julgamento final do mago!' },
  { id: 'earth_water_nature', sequence: ['earth', 'water', 'nature'], name: 'Pântano Engolidor', bonus: 'paralyze', duration: 3, msg: 'O solo se torna uma armadilha!' },
  { id: 'thunder_thunder_void', sequence: ['thunder', 'thunder', 'void'], name: 'Relâmpago Negro', bonus: 'damage', mult: 2.6, msg: 'Eletricidade que consome a luz!' },
  { id: 'cosmos_arcane_time', sequence: ['cosmos', 'arcane', 'time'], name: 'Viagem Astral', bonus: 'reduce_cd', msg: 'Sua mente transcende as eras!' },
  { id: 'music_fire_music', sequence: ['music', 'fire', 'music'], name: 'Rapsódia Infernal', bonus: 'damage', mult: 2.2, msg: 'Música que queima a alma!' },
  { id: 'ice_nature_light', sequence: ['ice', 'nature', 'light'], name: 'Aurora Boreal', bonus: 'shield', duration: 5, msg: 'A beleza do gelo protege você!' },

  // --- TIER 5: THE REMAINING (Up to ~100) ---
  { id: 'wind_wind_physical', sequence: ['wind', 'wind', 'physical'], name: 'Passo de Lâmina', bonus: 'damage', mult: 2.0, msg: 'Cortes invisíveis no ar!' },
  { id: 'blood_blood_physical', sequence: ['blood', 'blood', 'physical'], name: 'Berserker Imortal', bonus: 'regen', duration: 4, msg: 'Sua dor se torna força!' },
  { id: 'metal_earth_void', sequence: ['metal', 'earth', 'void'], name: 'Caixão de Ferro', bonus: 'damage', mult: 2.4, msg: 'O inimigo é enterrado vivo!' },
  { id: 'time_time_light', sequence: ['time', 'time', 'light'], name: 'Rebelião do Passado', bonus: 'heal', mult: 2.2, msg: 'Suas feridas voltam a não existir!' },
  { id: 'arcane_arcane_nature', sequence: ['arcane', 'arcane', 'nature'], name: 'Quimera Elemental', bonus: 'damage', mult: 2.5, msg: 'Magia e natureza distorcidas!' },
  { id: 'fire_metal_fire', sequence: ['fire', 'metal', 'fire'], name: 'Metal Líquido', bonus: 'damage', mult: 2.2, msg: 'Um mar de ferro fervendo!' },
  { id: 'water_water_void', sequence: ['water', 'water', 'void'], name: 'Tsunami das Sombras', bonus: 'damage', mult: 2.3, msg: 'Água negra que afoga em desespero!' },
  { id: 'thunder_wind_thunder', sequence: ['thunder', 'wind', 'thunder'], name: 'Raio de Tempestade', bonus: 'damage', mult: 2.4, msg: 'Atingindo com a fúria do céu!' },
  { id: 'nature_blood_nature', sequence: ['nature', 'blood', 'nature'], name: 'Flores de Sangue', bonus: 'damage', mult: 2.6, msg: 'Plantas que se alimentam de vida!' },
  { id: 'light_cosmos_light', sequence: ['light', 'cosmos', 'light'], name: 'Nebulosa Sagrada', bonus: 'shield', duration: 7, msg: 'A luz das estrelas te envolve!' },
  { id: 'physical_physical_earth', sequence: ['physical', 'physical', 'earth'], name: 'Quebra-Montanhas', bonus: 'damage', mult: 2.4, msg: 'Um golpe que divide picos!' },
  { id: 'void_void_arcane', sequence: ['void', 'void', 'arcane'], name: 'Vento de Éter', bonus: 'damage', mult: 2.7, msg: 'O sopro do fim do mundo!' },
  { id: 'time_music_time', sequence: ['time', 'music', 'time'], name: 'Cronômetro Melódico', bonus: 'paralyze', duration: 2, msg: 'O compasso do tempo desestabilizado!' },
  { id: 'metal_light_metal', sequence: ['metal', 'light', 'metal'], name: 'Armadura da Fé', bonus: 'shield', duration: 8, msg: 'Metal abençoado impenetrável!' },
  { id: 'cosmos_cosmos_void', sequence: ['cosmos', 'cosmos', 'void'], name: 'Supervazio Estelar', bonus: 'damage', mult: 3.5, msg: 'O universo engolindo a si mesmo!' },
  { id: 'ice_ice_blood', sequence: ['ice', 'ice', 'blood'], name: 'Gelo Vampírico', bonus: 'damage', mult: 2.5, msg: 'Espinhos de gelo que drenam o alvo!' },
  { id: 'fire_fire_arcane', sequence: ['fire', 'fire', 'arcane'], name: 'Explosão Gnóstica', bonus: 'damage', mult: 2.6, msg: 'O fogo do conhecimento supremo!' },
  { id: 'nature_nature_utility', sequence: ['nature', 'nature', 'utility'], name: 'Jardim de Panacéia', bonus: 'regen', duration: 10, msg: 'Cura absoluta por turnos!' },
  { id: 'thunder_thunder_earth', sequence: ['thunder', 'thunder', 'earth'], name: 'Magnetismo Terrestre', bonus: 'damage', mult: 2.5, msg: 'Poder de atração esmagador!' },
  { id: 'water_water_light', sequence: ['water', 'water', 'light'], name: 'Fonte da Juventude', bonus: 'heal', mult: 3.0, msg: 'Água abençoada restauradora!' },
  { id: 'physical_physical_ice', sequence: ['physical', 'physical', 'ice'], name: 'Impacto de Geada', bonus: 'paralyze', duration: 1, msg: 'Punhos que congelam ao toque!' },
  { id: 'arcane_arcane_time', sequence: ['arcane', 'arcane', 'time'], name: 'Loop Teúrgico', bonus: 'reduce_cd', msg: 'Conhecimento infinito reciclado!' },
  { id: 'blood_blood_void', sequence: ['blood', 'blood', 'void'], name: 'Echarpe das Almas', bonus: 'damage', mult: 3.0, msg: 'Muitas vidas por um só golpe!' },
  { id: 'void_void_cosmos', sequence: ['void', 'void', 'cosmos'], name: 'Gênesis Reversa', bonus: 'damage', mult: 3.8, msg: 'Tudo volta ao ponto zero!' },
  { id: 'light_light_wind', sequence: ['light', 'light', 'wind'], name: 'Asas de Serafim', bonus: 'shield', duration: 6, msg: 'Proteção alada divina!' },
  { id: 'fire_fire_nature', sequence: ['fire', 'fire', 'nature'], name: 'Carvão de Fênix', bonus: 'regen', duration: 5, msg: 'Cinzas que dão vida!' },
  { id: 'water_water_earth', sequence: ['water', 'water', 'earth'], name: 'Dilúvio Detrítico', bonus: 'damage', mult: 2.2, msg: 'Uma avalanche de lama líquida!' },
  { id: 'thunder_thunder_light', sequence: ['thunder', 'thunder', 'light'], name: 'Relâmpago Glorioso', bonus: 'damage', mult: 2.8, msg: 'A luz que cega e destrói!' },
  { id: 'nature_nature_wind', sequence: ['nature', 'nature', 'wind'], name: 'Polinização Selvagem', bonus: 'regen', duration: 4, msg: 'Vida espalhada pelo vento!' },
  { id: 'physical_physical_metal', sequence: ['physical', 'physical', 'metal'], name: 'Gume Perfeito', bonus: 'damage', mult: 2.6, msg: 'Força física pura com gumes afiados!' },
  { id: 'arcane_arcane_blood', sequence: ['arcane', 'arcane', 'blood'], name: 'Pacto de Ichor', bonus: 'damage', mult: 3.2, msg: 'Magia reforçada por sangue vital!' },
  { id: 'blood_blood_light', sequence: ['blood', 'blood', 'light'], name: 'Redenção Escarlate', bonus: 'heal', mult: 2.5, msg: 'Sangue purificado pela luz!' },
  { id: 'void_void_time', sequence: ['void', 'void', 'time'], name: 'Cronos Inanimado', bonus: 'paralyze', duration: 4, msg: 'O congelamento eterno do tempo!' },
  { id: 'cosmos_cosmos_light', sequence: ['cosmos', 'cosmos', 'light'], name: 'Farol das Estrelas', bonus: 'shield', duration: 10, msg: 'Impenetrabilidade cósmica!' },
  { id: 'ice_ice_water', sequence: ['ice', 'ice', 'water'], name: 'Estalactite Profunda', bonus: 'damage', mult: 2.4, msg: 'Peso e frio das profundezas!' },
  { id: 'metal_metal_earth', sequence: ['metal', 'metal', 'earth'], name: 'Fortaleza Móvel', bonus: 'shield', duration: 12, msg: 'Proteção extrema movida pela terra!' },
  { id: 'music_music_cosmos', sequence: ['music', 'music', 'cosmos'], name: 'Harmonia das Esferas', bonus: 'reduce_cd', msg: 'A vibração secreta do universo!' },
  { id: 'fire_fire_blood', sequence: ['fire', 'fire', 'blood'], name: 'Chama Hemática', bonus: 'damage', mult: 3.0, msg: 'O calor que consome o corpo!' },
  { id: 'water_water_ice', sequence: ['water', 'water', 'ice'], name: 'Geada Mestra', bonus: 'paralyze', duration: 2, msg: 'O ápice do congelamento hídrico!' },
  { id: 'thunder_thunder_metal', sequence: ['thunder', 'thunder', 'metal'], name: 'Forja Galvânica', bonus: 'damage', mult: 2.7, msg: 'Metal fundido por raios!' },
  { id: 'nature_nature_earth', sequence: ['nature', 'nature', 'earth'], name: 'Gaia Desperta', bonus: 'regen', duration: 12, msg: 'O planeta cura você!' },
  { id: 'physical_physical_arcane', sequence: ['physical', 'physical', 'arcane'], name: 'Punho do Transcendente', bonus: 'damage', mult: 3.5, msg: 'Superando os limites humanos!' },
  { id: 'metal_metal_arcane', sequence: ['metal', 'metal', 'arcane'], name: 'Alquimia de Ouro', bonus: 'damage', mult: 3.0, msg: 'Transmutação bélica perfeita!' },
  { id: 'time_time_void', sequence: ['time', 'time', 'void'], name: 'Ponto de Inexistência', bonus: 'damage', mult: 4.0, msg: 'Onde o tempo e o espaço morrem!' },
  { id: 'music_music_time', sequence: ['music', 'music', 'time'], name: 'Réquiem sem Fim', bonus: 'paralyze', duration: 3, msg: 'Uma canção que prende o agora!' },
  { id: 'blood_blood_time', sequence: ['blood', 'blood', 'time'], name: 'Ciclo Vampírico', bonus: 'heal', mult: 3.5, msg: 'Eternidade através do sangue!' },
  { id: 'cosmos_cosmos_fire', sequence: ['cosmos', 'cosmos', 'fire'], name: 'Erupção Solar Mestra', bonus: 'damage', mult: 3.6, msg: 'O calor da estrela mais brilhante!' },
  { id: 'ice_ice_wind', sequence: ['ice', 'ice', 'wind'], name: 'Tundra Implacável', bonus: 'damage', mult: 2.5, msg: 'Vento que racha pedras pelo frio!' },
  { id: 'nature_nature_light', sequence: ['nature', 'nature', 'light'], name: 'Árvore do Mundo', bonus: 'shield', duration: 15, msg: 'A proteção mítica da Yggdrasil!' },
  { id: 'arcane_arcane_cosmos', sequence: ['arcane', 'arcane', 'cosmos'], name: 'Magia de Quasar', bonus: 'damage', mult: 4.5, msg: 'A energia mais densa do universo!' },
  { id: 'physical_physical_physical', sequence: ['physical', 'physical', 'physical'], name: 'Combo do Infinito', bonus: 'damage', mult: 4.2, msg: 'O limite da força bruta!' },
  { id: 'void_void_void', sequence: ['void', 'void', 'void'], name: 'O Nada Absoluto', bonus: 'paralyze', duration: 5, msg: 'Silêncio total.' },
  
  // --- THEMATIC EXPANSION (Combos 232+) ---
  { id: 'fire_metal_physical', sequence: ['fire', 'metal', 'physical'], name: 'Lâmina de Plasma', bonus: 'damage', mult: 3.2, msg: 'Corte que derrete a armadura!' },
  { id: 'water_nature_blood', sequence: ['water', 'nature', 'blood'], name: 'Drenagem de Seiva', bonus: 'regen', duration: 8, msg: 'A vida flui como rios!' },
  { id: 'thunder_wind_metal', sequence: ['thunder', 'wind', 'metal'], name: 'Turbina Elétrica', bonus: 'damage', mult: 2.9, msg: 'Velocidade e choque extremos!' },
  { id: 'light_utility_time', sequence: ['light', 'utility', 'time'], name: 'Refração do Destino', bonus: 'reduce_cd', msg: 'O tempo se curva à luz!' },
  { id: 'void_cosmos_blood', sequence: ['void', 'cosmos', 'blood'], name: 'Eclipse de Almas', bonus: 'damage', mult: 3.5, msg: 'O universo sangra!' },
  { id: 'arcane_music_arcane', sequence: ['arcane', 'music', 'arcane'], name: 'Cântico do Criador', bonus: 'shield', duration: 10, msg: 'A realidade se estabiliza!' },
  { id: 'ice_earth_physical', sequence: ['ice', 'earth', 'physical'], name: 'Avalanche de Pedras', bonus: 'damage', mult: 2.6, msg: 'Peso e frio esmagadores!' },
  { id: 'metal_blood_metal', sequence: ['metal', 'blood', 'metal'], name: 'Sacrifício de Ferro', bonus: 'damage', mult: 3.1, msg: 'O metal se nutre de vida!' },
  { id: 'nature_light_nature', sequence: ['nature', 'light', 'nature'], name: 'Fotossíntese Sagrada', bonus: 'regen', duration: 12, msg: 'Brilho que cura feridas!' },
  { id: 'time_void_time', sequence: ['time', 'void', 'time'], name: 'Erosão Temporal', bonus: 'paralyze', duration: 3, msg: 'O alvo envelhece séculos em segundos!' },
  { id: 'cosmos_void_cosmos', sequence: ['cosmos', 'void', 'cosmos'], name: 'Buraco Negro Mestre', bonus: 'damage', mult: 4.0, msg: 'Nada escapa deste horizonte!' },
  { id: 'music_wind_music', sequence: ['music', 'wind', 'music'], name: 'Eco do Vendaval', bonus: 'damage', mult: 2.4, msg: 'O som se amplifica no ar!' },
  { id: 'fire_arcane_fire', sequence: ['fire', 'arcane', 'fire'], name: 'Pillar de Ignis', bonus: 'damage', mult: 2.9, msg: 'Fogo purificado por mana!' },
  { id: 'water_ice_water', sequence: ['water', 'ice', 'water'], name: 'Corrente de Granizo', bonus: 'paralyze', duration: 2, msg: 'Água que perfura como gelo!' },
  { id: 'thunder_light_thunder', sequence: ['thunder', 'light', 'thunder'], name: 'Relâmpago do Éden', bonus: 'damage', mult: 3.0, msg: 'Julgamento elétrico divino!' },
  { id: 'earth_metal_earth', sequence: ['earth', 'metal', 'earth'], name: 'Tectonismo de Aço', bonus: 'shield', duration: 15, msg: 'O chão se torna uma couraça!' },
  { id: 'physical_blood_physical', sequence: ['physical', 'blood', 'physical'], name: 'Sede de Sangue', bonus: 'damage', mult: 3.3, msg: 'Cada golpe drena o oponente!' },
  { id: 'arcane_time_arcane', sequence: ['arcane', 'time', 'arcane'], name: 'Paradoxo de Mana', bonus: 'reduce_cd', msg: 'Conhecimento que precede o uso!' },
  { id: 'utility_nature_utility', sequence: ['utility', 'nature', 'utility'], name: 'Brotar Infinito', bonus: 'regen', duration: 10, msg: 'Suporte vital contínuo!' },
  { id: 'blood_cosmos_blood', sequence: ['blood', 'cosmos', 'blood'], name: 'Nebulosa Vermelha', bonus: 'damage', mult: 3.7, msg: 'Sangue estelar devastador!' },
  { id: 'cosmos_music_cosmos', sequence: ['cosmos', 'music', 'cosmos'], name: 'Cântico das Estrelas', bonus: 'shield', duration: 20, msg: 'A proteção da galáxia!' },
  { id: 'fire_earth_fire', sequence: ['fire', 'earth', 'fire'], name: 'Magma Líquido', bonus: 'damage', mult: 2.8, msg: 'Rocha derretida em ebulição!' },
  { id: 'water_void_water', sequence: ['water', 'void', 'water'], name: 'Abismo de Poseidon', bonus: 'damage', mult: 3.2, msg: 'Oceano que consome a alma!' },
  { id: 'thunder_thunder_music', sequence: ['thunder', 'thunder', 'music'], name: 'Ressoar de Trovão', bonus: 'damage', mult: 2.6, msg: 'O som que ensurdece e queima!' },
  { id: 'nature_nature_blood', sequence: ['nature', 'nature', 'blood'], name: 'Lótus Alucinógena', bonus: 'paralyze', duration: 2, msg: 'Venenos que paralisam o sangue!' },
  { id: 'light_light_cosmos', sequence: ['light', 'light', 'cosmos'], name: 'Supernova Divina', bonus: 'damage', mult: 3.8, msg: 'A luz que cria mundos!' },
  { id: 'void_void_physical', sequence: ['void', 'void', 'physical'], name: 'Golpe Fantasma', bonus: 'damage', mult: 3.0, msg: 'Um soco que vem de lugar nenhum!' },
  { id: 'arcane_arcane_light', sequence: ['arcane', 'arcane', 'light'], name: 'Cetro de Metatron', bonus: 'damage', mult: 3.4, msg: 'Magia angelical pura!' },
  { id: 'time_time_music', sequence: ['time', 'time', 'music'], name: 'Melodia da Eternidade', bonus: 'reduce_cd', msg: 'Ritmo que acelera o fluxo!' },
  { id: 'cosmos_cosmos_metal', sequence: ['cosmos', 'cosmos', 'metal'], name: 'Cometa de Platina', bonus: 'damage', mult: 3.6, msg: 'Impacto metálico sideral!' },
  { id: 'metal_metal_wind', sequence: ['metal', 'metal', 'wind'], name: 'Ciclone de Lâminas', bonus: 'damage', mult: 3.0, msg: 'Aço que voa com a brisa!' },
  { id: 'blood_blood_arcane', sequence: ['blood', 'blood', 'arcane'], name: 'Feitiço de Ichor', bonus: 'damage', mult: 3.5, msg: 'Poder arcano movido a sangue!' },
  { id: 'ice_ice_light', sequence: ['ice', 'ice', 'light'], name: 'Geada Sagrada', bonus: 'shield', duration: 10, msg: 'Reflexos que protegem do mal!' },
  { id: 'nature_utility_light', sequence: ['nature', 'utility', 'light'], name: 'Orvalho de Gaia', bonus: 'regen', duration: 15, msg: 'Cura divina da floresta!' },
  { id: 'physical_physical_fire', sequence: ['physical', 'physical', 'fire'], name: 'Impacto de Ignição', bonus: 'damage', mult: 3.1, msg: 'Golpes que geram chamas!' },
  { id: 'fire_void_time', sequence: ['fire', 'void', 'time'], name: 'Cinzas do Amanhã', bonus: 'damage', mult: 3.4, msg: 'O destino queima no vácuo!' },
  { id: 'water_metal_thunder', sequence: ['water', 'metal', 'thunder'], name: 'Tempestade Condutora', bonus: 'damage', mult: 3.0, msg: 'Tudo está eletrizado!' },
  { id: 'nature_earth_physical', sequence: ['nature', 'earth', 'physical'], name: 'Raiz de Titã', bonus: 'damage', mult: 2.9, msg: 'A terra e as plantas te esmagam!' },
  { id: 'light_arcane_void', sequence: ['light', 'arcane', 'void'], name: 'Prisma do Vazio', bonus: 'damage', mult: 3.8, msg: 'A luz que desaparece no escuro!' },
  { id: 'time_cosmos_time', sequence: ['time', 'cosmos', 'time'], name: 'Relógio de Galáxias', bonus: 'reduce_cd', msg: 'Eras inteiras em um piscar!' },
  { id: 'metal_fire_metal', sequence: ['metal', 'fire', 'metal'], name: 'Forja do Olimpo', bonus: 'damage', mult: 3.2, msg: 'Metal moldado pelo calor divino!' },
  { id: 'blood_thunder_blood', sequence: ['blood', 'thunder', 'blood'], name: 'Eletrochoque Hemático', bonus: 'damage', mult: 3.4, msg: 'O sangue ferve com relâmpagos!' },
  { id: 'arcane_wind_arcane', sequence: ['arcane', 'wind', 'arcane'], name: 'Vendaval Mágico', bonus: 'damage', mult: 2.8, msg: 'Mana empurrada pelo ar!' },
  { id: 'void_nature_void', sequence: ['void', 'nature', 'void'], name: 'Floresta Morta', bonus: 'damage', mult: 3.5, msg: 'A vida que seca no vazio!' },
  { id: 'cosmos_earth_cosmos', sequence: ['cosmos', 'earth', 'cosmos'], name: 'Meteorito de Gaia', bonus: 'damage', mult: 3.9, msg: 'Um pedaço do mundo que cai do céu!' },
  { id: 'music_blood_music', sequence: ['music', 'blood', 'music'], name: 'Ópera de Sangue', bonus: 'damage', mult: 3.3, msg: 'Notas que cortam as veias!' },
  { id: 'ice_metal_ice', sequence: ['ice', 'metal', 'ice'], name: 'Ferro Congelado', bonus: 'paralyze', duration: 3, msg: 'Frio que quebra o metal!' },
  { id: 'fire_light_fire', sequence: ['fire', 'light', 'fire'], name: 'Chama de Helios', bonus: 'damage', mult: 3.1, msg: 'O calor puro do sol!' },
  { id: 'water_time_water', sequence: ['water', 'time', 'water'], name: 'Oceano Retroativo', bonus: 'heal', mult: 3.5, msg: 'A água que volta no tempo!' },
  { id: 'thunder_cosmos_thunder', sequence: ['thunder', 'cosmos', 'thunder'], name: 'Raio de Pulsar', bonus: 'damage', mult: 3.7, msg: 'Energia de uma estrela de nêutrons!' },
  { id: 'nature_void_nature', sequence: ['nature', 'void', 'nature'], name: 'Raízes Estelares', bonus: 'regen', duration: 20, msg: 'Vida que vem do espaço vazio!' },
  { id: 'physical_light_physical', sequence: ['physical', 'light', 'physical'], name: 'Golpe do Paladino', bonus: 'damage', mult: 3.2, msg: 'Força e luz em cada punho!' },
  { id: 'arcane_blood_arcane', sequence: ['arcane', 'blood', 'arcane'], name: 'Necromancia Direta', bonus: 'damage', mult: 3.6, msg: 'O poder dos mortos no agora!' },
  { id: 'time_metal_time', sequence: ['time', 'metal', 'time'], name: 'Cronômetro de Aço', bonus: 'shield', duration: 18, msg: 'Proteção que nunca envelhece!' },
  { id: 'void_fire_void', sequence: ['void', 'fire', 'void'], name: 'Extinção Térmica', bonus: 'damage', mult: 4.2, msg: 'O calor que desaparece no nada!' },
  { id: 'cosmos_water_cosmos', sequence: ['cosmos', 'water', 'cosmos'], name: 'Nebulosa Aquática', bonus: 'heal', mult: 4.0, msg: 'Águas estelares purificadoras!' },
  { id: 'utility_thunder_utility', sequence: ['utility', 'thunder', 'utility'], name: 'Sobrecarga de Suporte', bonus: 'reduce_cd', msg: 'Energia extra para seus feitiços!' },
  { id: 'metal_cosmos_metal', sequence: ['metal', 'cosmos', 'metal'], name: 'Armadura Galáctica', bonus: 'shield', duration: 25, msg: 'O metal das estrelas te protege!' },
  { id: 'blood_nature_blood', sequence: ['blood', 'nature', 'blood'], name: 'Seiva de Ichor', bonus: 'regen', duration: 15, msg: 'Vida recuperada por rituais naturais!' },
  { id: 'arcane_void_arcane', sequence: ['arcane', 'void', 'arcane'], name: 'Mestra do Éter', bonus: 'damage', mult: 4.5, msg: 'A magia mestre do vazio!' },
  { id: 'time_light_time', sequence: ['time', 'light', 'time'], name: 'Eternidade Iluminada', bonus: 'shield', duration: 15, msg: 'A luz que brilha além do tempo!' },
  { id: 'cosmos_void_time', sequence: ['cosmos', 'void', 'time'], name: 'Big Bang Reverso', bonus: 'damage', mult: 5.0, msg: 'O universo voltando à origem!' },
  { id: 'music_utility_music', sequence: ['music', 'utility', 'music'], name: 'Himno Galvânico', bonus: 'reduce_cd', msg: 'Música que energiza tudo!' },
  { id: 'ice_blood_ice', sequence: ['ice', 'blood', 'ice'], name: 'Gelo Hemático', bonus: 'damage', mult: 3.2, msg: 'Espinhos que congelam o sangue!' },
  { id: 'metal_metal_metal', sequence: ['metal', 'metal', 'metal'], name: 'Muralha de Adamantino', bonus: 'shield', duration: 30, msg: 'Defesa absoluta de metal!' },
  { id: 'blood_blood_blood', sequence: ['blood', 'blood', 'blood'], name: 'Sacrifício Final', bonus: 'damage', mult: 5.0, msg: 'Todo o seu sangue em um golpe!' },
  { id: 'cosmos_cosmos_cosmos', sequence: ['cosmos', 'cosmos', 'cosmos'], name: 'Juízo do Universo', bonus: 'damage', mult: 5.5, msg: 'O cosmos exige seu fim!' },
  { id: 'fire_water_thunder', sequence: ['fire', 'water', 'thunder'], name: 'Explosão de Vapor Eletrificado', bonus: 'damage', mult: 3.2, msg: 'Vapor que conduz relâmpagos!' },
  { id: 'nature_wind_earth', sequence: ['nature', 'wind', 'earth'], name: 'Furacão de Detritos Fertilizantes', bonus: 'regen', duration: 10, msg: 'A terra e o ar alimentam as plantas!' },
  { id: 'light_void_cosmos', sequence: ['light', 'void', 'cosmos'], name: 'Nascimento de uma Estrela Sombria', bonus: 'damage', mult: 4.2, msg: 'O nascimento que destrói!' },
  { id: 'time_arcane_blood', sequence: ['time', 'arcane', 'blood'], name: 'Cronos-Magia Vital', bonus: 'heal', mult: 4.0, msg: 'Tempo e magia girando sua vida!' },
  { id: 'physical_metal_utility', sequence: ['physical', 'metal', 'utility'], name: 'Reforço de Ferro Bruto', bonus: 'shield', duration: 20, msg: 'Corpo endurecido pela alquimia!' },
  { id: 'music_ice_cosmos', sequence: ['music', 'ice', 'cosmos'], name: 'Serenata Gelada das Estrelas', bonus: 'paralyze', duration: 4, msg: 'Som que congela o espírito!' },
  { id: 'void_light_nature', sequence: ['void', 'light', 'nature'], name: 'Antimatéria Orgânica', bonus: 'damage', mult: 3.8, msg: 'O que existe contra o que não existe!' },
  { id: 'fire_music_blood', sequence: ['fire', 'music', 'blood'], name: 'Jazz do Inferno', bonus: 'damage', mult: 3.5, msg: 'Música quente e sangrenta!' },
  { id: 'water_time_utility', sequence: ['water', 'time', 'utility'], name: 'Fonte da Reversão', bonus: 'reduce_cd', msg: 'As águas limpam as recargas!' },
  { id: 'thunder_earth_void', sequence: ['thunder', 'earth', 'void'], name: 'Choque de Antimatéria', bonus: 'damage', mult: 4.0, msg: 'O solo explode em energia negativa!' },
  { id: 'arcane_nature_metal', sequence: ['arcane', 'nature', 'metal'], name: 'Golem Bio-Mecânico', bonus: 'shield', duration: 15, msg: 'A vida artificial te protege!' },
  { id: 'blood_music_time', sequence: ['blood', 'music', 'time'], name: 'Ritmo Cardíaco Eterno', bonus: 'regen', duration: 20, msg: 'Seu coração bate no compasso do universo!' },
  { id: 'cosmos_utility_light', sequence: ['cosmos', 'utility', 'light'], name: 'Auspício Galáctico', bonus: 'shield', duration: 25, msg: 'O céu está a seu favor!' },
  { id: 'metal_arcane_fire', sequence: ['metal', 'arcane', 'fire'], name: 'Fundição Planar', bonus: 'damage', mult: 3.6, msg: 'Metal derretido por energia pura!' },
  { id: 'ice_wind_time', sequence: ['ice', 'wind', 'time'], name: 'Erosão Glacial Acelerada', bonus: 'paralyze', duration: 5, msg: 'O gelo e o vento cortam o tempo!' },
  { id: 'utility_blood_cosmos', sequence: ['utility', 'blood', 'cosmos'], name: 'Pacto Sideral', bonus: 'damage', mult: 4.4, msg: 'Sua essência trocada por estrelas!' },
  { id: 'fire_earth_void', sequence: ['fire', 'earth', 'void'], name: 'Vulcão de Antimatéria', bonus: 'damage', mult: 4.8, msg: 'O coração do mundo explode em nada!' },
  { id: 'water_thunder_light', sequence: ['water', 'thunder', 'light'], name: 'Prisma Fluido', bonus: 'damage', mult: 3.4, msg: 'A luz brilha através da água eletrificada!' },
  { id: 'nature_metal_arcane', sequence: ['nature', 'metal', 'arcane'], name: 'Floresta Mecânica', bonus: 'shield', duration: 20, msg: 'Árvores de aço defendem você!' },
  { id: 'physical_time_void', sequence: ['physical', 'time', 'void'], name: 'Impacto de Entropia', bonus: 'damage', mult: 4.6, msg: 'Um soco que desfaz a matéria!' },
  { id: 'music_cosmos_blood', sequence: ['music', 'cosmos', 'blood'], name: 'Réquiem Estelar', bonus: 'damage', mult: 4.2, msg: 'O fim de uma era em sons!' },
  { id: 'light_earth_music', sequence: ['light', 'earth', 'music'], name: 'Ode à Terra Sagrada', bonus: 'regen', duration: 18, msg: 'A canção do solo que cura!' },
  { id: 'void_utility_void', sequence: ['void', 'utility', 'void'], name: 'Vácuo Utilitário', bonus: 'reduce_cd', msg: 'Nada resta para impedir suas magias!' },
  { id: 'arcane_arcane_arcane', sequence: ['arcane', 'arcane', 'arcane'], name: 'O Arcanum Máximo', bonus: 'damage', mult: 6.0, msg: 'O ápice absoluto da magia!' },
  { id: 'blood_blood_physical', sequence: ['blood', 'blood', 'physical'], name: 'Berserker Sangrento', bonus: 'damage', mult: 3.8, msg: 'Fúria alimentada por sua própria vida!' },
  { id: 'metal_metal_physical', sequence: ['metal', 'metal', 'physical'], name: 'Colosso de Ferro', bonus: 'shield', duration: 20, msg: 'Seu corpo se torna impenetrável!' },
  { id: 'time_time_time', sequence: ['time', 'time', 'time'], name: 'O Senhor do Tempo', bonus: 'paralyze', duration: 6, msg: 'Tudo para. Só você se move.' },
  { id: 'void_void_arcane', sequence: ['void', 'void', 'arcane'], name: 'O Fim da Magia', bonus: 'damage', mult: 5.5, msg: 'Toda essência convertida em nada!' },
  { id: 'light_light_light', sequence: ['light', 'light', 'light'], name: 'A Glória Final', bonus: 'heal', mult: 6.0, msg: 'A luz que restaura tudo!' },
  
  // --- ELEMENTAL MASTERY CHAINS ---
  { id: 'master_fire', sequence: ['fire', 'fire', 'fire'], name: 'Maestria de Fogo I', bonus: 'damage', mult: 2.5, msg: 'O domínio das chamas aumenta.' },
  { id: 'master_water', sequence: ['water', 'water', 'water'], name: 'Maestria de Água I', bonus: 'heal', mult: 2.2, msg: 'O domínio das águas aumenta.' },
  { id: 'master_thunder', sequence: ['thunder', 'thunder', 'thunder'], name: 'Maestria de Trovão I', bonus: 'paralyze', duration: 2, msg: 'O domínio dos raios aumenta.' },
  { id: 'master_wind', sequence: ['wind', 'wind', 'wind'], name: 'Maestria de Vento I', bonus: 'damage', mult: 2.3, msg: 'O domínio dos ventos aumenta.' },
  { id: 'master_nature', sequence: ['nature', 'nature', 'nature'], name: 'Maestria de Natureza I', bonus: 'regen', duration: 8, msg: 'O domínio da natureza aumenta.' },
  { id: 'master_physical', sequence: ['physical', 'physical', 'physical'], name: 'Maestria Física I', bonus: 'damage', mult: 2.4, msg: 'O domínio físico aumenta.' },
  { id: 'master_light', sequence: ['light', 'light', 'light'], name: 'Maestria de Luz I', bonus: 'shield', duration: 6, msg: 'O domínio da luz aumenta.' },
  { id: 'master_arcane', sequence: ['arcane', 'arcane', 'arcane'], name: 'Maestria Arcana I', bonus: 'damage', mult: 2.8, msg: 'O domínio arcano aumenta.' },
  { id: 'master_void', sequence: ['void', 'void', 'void'], name: 'Maestria do Vazio I', bonus: 'damage', mult: 3.0, msg: 'O domínio do vazio aumenta.' },
  { id: 'master_time', sequence: ['time', 'time', 'time'], name: 'Maestria do Tempo I', bonus: 'reduce_cd', msg: 'O domínio do tempo aumenta.' },
  { id: 'master_earth', sequence: ['earth', 'earth', 'earth'], name: 'Maestria de Terra I', bonus: 'damage', mult: 2.5, msg: 'O domínio da terra aumenta.' },
  { id: 'master_ice', sequence: ['ice', 'ice', 'ice'], name: 'Maestria de Gelo I', bonus: 'paralyze', duration: 3, msg: 'O domínio do gelo aumenta.' },
  { id: 'master_metal', sequence: ['metal', 'metal', 'metal'], name: 'Maestria de Metal I', bonus: 'shield', duration: 10, msg: 'O domínio do metal aumenta.' },
  { id: 'master_blood', sequence: ['blood', 'blood', 'blood'], name: 'Maestria de Sangue I', bonus: 'damage', mult: 3.2, msg: 'O domínio do sangue aumenta.' },
  { id: 'master_cosmos', sequence: ['cosmos', 'cosmos', 'cosmos'], name: 'Maestria do Cosmos I', bonus: 'damage', mult: 3.5, msg: 'O domínio do cosmos aumenta.' },
  { id: 'master_music', sequence: ['music', 'music', 'music'], name: 'Maestria da Música I', bonus: 'damage', mult: 2.4, msg: 'O domínio da música aumenta.' },
  { id: 'master_utility', sequence: ['utility', 'utility', 'utility'], name: 'Maestria de Suporte I', bonus: 'regen', duration: 10, msg: 'O domínio do suporte aumenta.' },

  // --- CROSS-BREED SERIES ---
  { id: 'cross_fire_water', sequence: ['fire', 'water', 'fire'], name: 'Dual de Vapor', bonus: 'damage', mult: 2.6, msg: 'Vapor escaldante!' },
  { id: 'cross_thunder_ice', sequence: ['thunder', 'ice', 'thunder'], name: 'Dual de Supercondução Fria', bonus: 'damage', mult: 2.7, msg: 'Raios no vácuo gélido!' },
  { id: 'cross_light_void', sequence: ['light', 'void', 'light'], name: 'Dual de Crepúsculo', bonus: 'shield', duration: 10, msg: 'Entre a luz e a escuridão!' },
  { id: 'cross_nature_metal', sequence: ['nature', 'metal', 'nature'], name: 'Dual de Floresta de Aço', bonus: 'regen', duration: 5, msg: 'Plantas reforçadas!' },
  { id: 'cross_physical_cosmos', sequence: ['physical', 'cosmos', 'physical'], name: 'Dual de Peso Estelar', bonus: 'damage', mult: 3.2, msg: 'Gravidade nos punhos!' },
  { id: 'cross_arcane_blood', sequence: ['arcane', 'blood', 'arcane'], name: 'Dual de Mana Vital', bonus: 'damage', mult: 3.4, msg: 'Magia que consome vida!' },
  { id: 'cross_time_music', sequence: ['time', 'music', 'time'], name: 'Dual de Metrônomo', bonus: 'reduce_cd', msg: 'Sincronia temporal perfeita!' },
  { id: 'cross_earth_wind', sequence: ['earth', 'wind', 'earth'], name: 'Dual de Tempestade de Areia', bonus: 'paralyze', duration: 2, msg: 'Visão obstruída por detritos!' },
  { id: 'cross_utility_utility_light', sequence: ['utility', 'utility', 'light'], name: 'Dual de Redenção', bonus: 'heal', mult: 3.0, msg: 'Suporte divino total!' },

  // --- REVERSED CHAINS ---
  { id: 'rev_fire_water_thunder', sequence: ['thunder', 'water', 'fire'], name: 'Inverso de Vapor', bonus: 'damage', mult: 2.8, msg: 'Energia liberada de trás para frente!' },
  { id: 'rev_nature_earth_metal', sequence: ['metal', 'earth', 'nature'], name: 'Inverso de Bioma', bonus: 'regen', duration: 10, msg: 'A ordem natural invertida!' },
  { id: 'rev_cosmos_void_time', sequence: ['time', 'void', 'cosmos'], name: 'Inverso de Entropia', bonus: 'damage', mult: 4.5, msg: 'O tempo voltando ao caos!' },
  { id: 'rev_light_arcane_music', sequence: ['music', 'arcane', 'light'], name: 'Inverso de Harmonia', bonus: 'shield', duration: 15, msg: 'O som precedendo a magia!' },
  { id: 'rev_blood_physical_ice', sequence: ['ice', 'physical', 'blood'], name: 'Inverso de Trauma', bonus: 'damage', mult: 3.5, msg: 'Frio que corta e sangra!' },

  // --- EXPERIMENTAL SLOTS (Getting to 500...) ---
  { id: 'exp_1', sequence: ['fire', 'nature', 'metal'], name: 'Alquimia de Combustão', bonus: 'damage', mult: 3.2, msg: 'Matéria orgânica em chamas metálicas!' },
  { id: 'exp_2', sequence: ['water', 'wind', 'ice'], name: 'Ciclone de Granizo', bonus: 'paralyze', duration: 3, msg: 'Clima extremo em um ponto!' },
  { id: 'exp_3', sequence: ['thunder', 'arcane', 'cosmos'], name: 'Pulsar Galvânico', bonus: 'damage', mult: 3.8, msg: 'A radiação do espaço elétrico!' },
  { id: 'exp_4', sequence: ['light', 'time', 'utility'], name: 'Auspício de Cronos', bonus: 'reduce_cd', msg: 'Suporte vindo do futuro!' },
  { id: 'exp_5', sequence: ['void', 'blood', 'physical'], name: 'Abismo de Dor', bonus: 'damage', mult: 4.0, msg: 'O sofrimento que alimenta o nada!' },
  { id: 'exp_6', sequence: ['music', 'earth', 'nature'], name: 'Ressoar da Terra', bonus: 'regen', duration: 12, msg: 'A música das raízes profundas!' },
  { id: 'exp_7', sequence: ['metal', 'light', 'void'], name: 'Espectro de Ferro', bonus: 'shield', duration: 20, msg: 'Metal e luz sumindo no vácuo!' },
  { id: 'exp_8', sequence: ['blood', 'fire', 'time'], name: 'Ciclo de Fogo Vital', bonus: 'damage', mult: 3.6, msg: 'A vida que queima no tempo!' },
  { id: 'exp_9', sequence: ['cosmos', 'thunder', 'water'], name: 'Nebulosa Condutora', bonus: 'damage', mult: 3.4, msg: 'Raios nas águas do espaço!' },
  { id: 'exp_10', sequence: ['arcane', 'physical', 'utility'], name: 'Transmutação de Impacto', bonus: 'damage', mult: 3.0, msg: 'Força bruta convertida em mana!' },
  { id: 'exp_11', sequence: ['fire', 'ice', 'fire'], name: 'Choque Térmico', bonus: 'damage', mult: 3.5, msg: 'Calor e frio extremos!' },
  { id: 'exp_12', sequence: ['water', 'earth', 'water'], name: 'Maré de Lama', bonus: 'paralyze', duration: 2, msg: 'Preso no solo molhado!' },
  { id: 'exp_13', sequence: ['thunder', 'nature', 'thunder'], name: 'Gavinhas Elétricas', bonus: 'damage', mult: 3.1, msg: 'Plantas energizadas!' },
  { id: 'exp_14', sequence: ['light', 'metal', 'light'], name: 'Armadura do Sol', bonus: 'shield', duration: 15, msg: 'Metal que reflete a divindade!' },
  { id: 'exp_15', sequence: ['void', 'music', 'void'], name: 'Cantos do Oblívio', bonus: 'damage', mult: 3.8, msg: 'Som que apaga a memória!' },
  { id: 'exp_16', sequence: ['time', 'blood', 'time'], name: 'Sangue de Cronos', bonus: 'heal', mult: 4.5, msg: 'Tempo extraído de cada gota!' },
  { id: 'exp_17', sequence: ['cosmos', 'physical', 'cosmos'], name: 'Supernova de Punho', bonus: 'damage', mult: 4.2, msg: 'Cada soco é uma explosão estelar!' },
  { id: 'exp_18', sequence: ['metal', 'utility', 'metal'], name: 'Arsenal de Suporte', bonus: 'shield', duration: 12, msg: 'Ferramentas de defesa rápida!' },
  { id: 'exp_19', sequence: ['nature', 'arcane', 'nature'], name: 'Bio-Arcano', bonus: 'regen', duration: 15, msg: 'Cura movida por mana natural!' },
  { id: 'exp_20', sequence: ['physical', 'void', 'physical'], name: 'Vácuo entre Golpes', bonus: 'damage', mult: 3.7, msg: 'Velocidade além da matéria!' },
  { id: 'exp_21', sequence: ['fire', 'thunder', 'fire'], name: 'Chama Galvânica', bonus: 'damage', mult: 3.3, msg: 'Fogo eletrizante!' },
  { id: 'exp_22', sequence: ['water', 'nature', 'water'], name: 'Oceano Verde', bonus: 'regen', duration: 8, msg: 'Toda a água é curativa!' },
  { id: 'exp_23', sequence: ['thunder', 'wind', 'thunder'], name: 'Tempestade de Íons', bonus: 'damage', mult: 3.5, msg: 'O ar está carregado!' },
  { id: 'exp_24', sequence: ['light', 'arcane', 'light'], name: 'Farol da Iluminação', bonus: 'reduce_cd', msg: 'Toda magia é instantânea!' },
  { id: 'exp_25', sequence: ['void', 'time', 'void'], name: 'Singularidade Temporal', bonus: 'paralyze', duration: 5, msg: 'Onde o tempo não existe.' },
  { id: 'exp_26', sequence: ['music', 'physical', 'music'], name: 'Melodia Marcial', bonus: 'damage', mult: 3.1, msg: 'A luta no ritmo certo!' },
  { id: 'exp_27', sequence: ['metal', 'fire', 'metal'], name: 'Ferro de Forja', bonus: 'damage', mult: 2.9, msg: 'Aço escaldante!' },
  { id: 'exp_28', sequence: ['blood', 'ice', 'blood'], name: 'Criogênese de Sangue', bonus: 'damage', mult: 3.4, msg: 'Drenagem congelante!' },
  { id: 'exp_29', sequence: ['cosmos', 'light', 'cosmos'], name: 'Sopro de Galáxia', bonus: 'shield', duration: 20, msg: 'A luz de bilhões de sóis!' },
  { id: 'exp_30', sequence: ['arcane', 'utility', 'arcane'], name: 'Fluxo Alquímico', bonus: 'reduce_cd', msg: 'Transmutação de custo zero!' },
  { id: 'exp_31', sequence: ['fire', 'cosmos', 'fire'], name: 'Fogo de Supernova', bonus: 'damage', mult: 4.8, msg: 'O calor da morte de uma estrela!' },
  { id: 'exp_32', sequence: ['water', 'music', 'water'], name: 'Canto da Sereia', bonus: 'paralyze', duration: 2, msg: 'O som que atrai ao abismo!' },
  { id: 'exp_33', sequence: ['thunder', 'metal', 'thunder'], name: 'Corrente de Alta Tensão', bonus: 'damage', mult: 3.2, msg: 'Condução perfeita e letal!' },
  { id: 'exp_34', sequence: ['light', 'nature', 'light'], name: 'Sol de Primavera', bonus: 'regen', duration: 10, msg: 'Tudo floresce sob este brilho!' },
  { id: 'exp_35', sequence: ['void', 'physical', 'void'], name: 'Punho da Inexistência', bonus: 'damage', mult: 4.1, msg: 'O golpe que remove o alvo da realidade!' },
  { id: 'exp_36', sequence: ['time', 'arcane', 'time'], name: 'Vórtice do Sábio', bonus: 'reduce_cd', msg: 'Conhecimento infinito reciclado no tempo!' },
  { id: 'exp_37', sequence: ['cosmos', 'void', 'cosmos'], name: 'Evento de Horizonte', bonus: 'damage', mult: 5.2, msg: 'O ponto de não retorno!' },
  { id: 'exp_38', sequence: ['music', 'time', 'music'], name: 'Sinfonia Perpétua', bonus: 'regen', duration: 18, msg: 'Uma nota que nunca deixa de curar!' },
  { id: 'exp_39', sequence: ['metal', 'blood', 'metal'], name: 'Engrenagens de Sacrifício', bonus: 'damage', mult: 4.4, msg: 'Máquinas movidas a alma!' },
  { id: 'exp_40', sequence: ['blood', 'cosmos', 'blood'], name: 'Radiação de Vida', bonus: 'damage', mult: 4.7, msg: 'Energia cósmica injetada nas veias!' },
  { id: 'exp_41', sequence: ['earth', 'earth', 'fire'], name: 'Placa Tectônica Ardente', bonus: 'damage', mult: 3.3, msg: 'O solo derretido se move!' },
  { id: 'exp_42', sequence: ['ice', 'ice', 'thunder'], name: 'Relâmpago de Geada', bonus: 'paralyze', duration: 3, msg: 'Frio que conduz a eletricidade!' },
  { id: 'exp_43', sequence: ['nature', 'nature', 'light'], name: 'Flor da Pureza', bonus: 'regen', duration: 12, msg: 'Vida extraída da luz pura!' },
  { id: 'exp_44', sequence: ['physical', 'physical', 'void'], name: 'Impacto de Colapso', bonus: 'damage', mult: 4.8, msg: 'Um golpe que cria vácuo!' },
  { id: 'exp_45', sequence: ['utility', 'utility', 'time'], name: 'Reforço Temporal', bonus: 'reduce_cd', msg: 'Todo o suporte agora é imediato!' },
  { id: 'exp_46', sequence: ['arcane', 'arcane', 'music'], name: 'Canto Arcana', bonus: 'shield', duration: 15, msg: 'Barreira sônica mágica!' },
  { id: 'exp_47', sequence: ['blood', 'blood', 'cosmos'], name: 'Sangue de Quasar', bonus: 'damage', mult: 5.1, msg: 'Inerção de energia estática vital!' },
  { id: 'exp_48', sequence: ['metal', 'metal', 'light'], name: 'Heliotrópico de Aço', bonus: 'shield', duration: 25, msg: 'O metal que busca a luz do sol!' },
  { id: 'exp_49', sequence: ['time', 'time', 'earth'], name: 'Erosão Geológica', bonus: 'damage', mult: 3.9, msg: 'Montanhas que se tornam pó em segundos!' },
  { id: 'exp_50', sequence: ['void', 'void', 'nature'], name: 'Vida do Abismo', bonus: 'regen', duration: 15, msg: 'Onde nada existia, agora há cura!' },
  { id: 'exp_51', sequence: ['fire', 'fire', 'metal'], name: 'Forja de Magma I', bonus: 'damage', mult: 3.1, msg: 'Metal fundido no calor do núcleo!' },
  { id: 'exp_52', sequence: ['fire', 'fire', 'ice'], name: 'Fusão Contraditória', bonus: 'paralyze', duration: 2, msg: 'Calor e frio extremos lutando!' },
  { id: 'exp_53', sequence: ['water', 'water', 'nature'], name: 'Oásis Sagrado', bonus: 'regen', duration: 10, msg: 'A vida floresce na água!' },
  { id: 'exp_54', sequence: ['water', 'water', 'metal'], name: 'Mercúrio Vivo', bonus: 'damage', mult: 2.8, msg: 'Metal líquido imparável!' },
  { id: 'exp_55', sequence: ['thunder', 'thunder', 'wind'], name: 'Tempestade de Raio', bonus: 'damage', mult: 3.0, msg: 'Vento carregado de voltagem!' },
  { id: 'exp_56', sequence: ['thunder', 'thunder', 'ice'], name: 'Eletricidade Estática Gélida', bonus: 'paralyze', duration: 3, msg: 'O frio fixa o choque!' },
  { id: 'exp_57', sequence: ['nature', 'nature', 'arcane'], name: 'Evolução Mágica', bonus: 'damage', mult: 3.2, msg: 'As plantas agora usam mana!' },
  { id: 'exp_58', sequence: ['nature', 'nature', 'void'], name: 'Semente do Vazio', bonus: 'damage', mult: 3.5, msg: 'A vida que consome a realidade!' },
  { id: 'exp_59', sequence: ['physical', 'physical', 'blood'], name: 'Fúria de Sangue', bonus: 'damage', mult: 3.8, msg: 'Golpes que alimentam a sede!' },
  { id: 'exp_60', sequence: ['physical', 'physical', 'time'], name: 'Golpe Eterno', bonus: 'damage', mult: 4.2, msg: 'Um impacto que se repete no tempo!' },
  { id: 'exp_61', sequence: ['arcane', 'arcane', 'void'], name: 'Nulidade Arcana', bonus: 'damage', mult: 4.8, msg: 'O fim de todo conhecimento!' },
  { id: 'exp_62', sequence: ['arcane', 'arcane', 'cosmos'], name: 'Big Bang de Bolso', bonus: 'damage', mult: 5.5, msg: 'Uma nova realidade criada para explodir!' },
  { id: 'exp_63', sequence: ['blood', 'blood', 'fire'], name: 'Sangue em Chamas', bonus: 'damage', mult: 3.4, msg: 'A vida que queima intensamente!' },
  { id: 'exp_64', sequence: ['blood', 'blood', 'ice'], name: 'Congelamento Hemático', bonus: 'paralyze', duration: 4, msg: 'O fluxo vital é interrompido!' },
  { id: 'exp_65', sequence: ['void', 'void', 'light'], name: 'Buraco Branco', bonus: 'damage', mult: 4.1, msg: 'A saída do vazio em forma de luz!' },
  { id: 'exp_66', sequence: ['void', 'void', 'time'], name: 'Parada Final', bonus: 'paralyze', duration: 6, msg: 'O nada absoluto e atemporal.' },
  { id: 'exp_67', sequence: ['cosmos', 'cosmos', 'wind'], name: 'Vento Interestelar', bonus: 'damage', mult: 3.3, msg: 'Radiação empurrada pelo vácuo!' },
  { id: 'exp_68', sequence: ['cosmos', 'cosmos', 'earth'], name: 'Poeira de Estrela', bonus: 'regen', duration: 12, msg: 'As bases da vida vindas do alto!' },
  { id: 'exp_69', sequence: ['time', 'time', 'water'], name: 'Fluxo Retrógrado', bonus: 'heal', mult: 4.0, msg: 'Seu estado de saúde volta ao passado!' },
  { id: 'exp_70', sequence: ['time', 'time', 'fire'], name: 'Combustão Eterna', bonus: 'damage', mult: 4.5, msg: 'O fogo que nunca apaga no tempo!' },
  { id: 'exp_71', sequence: ['ice', 'ice', 'fire'], name: 'Criovulcanismo', bonus: 'damage', mult: 3.6, msg: 'Gelo derretido por pressão interna!' },
  { id: 'exp_72', sequence: ['ice', 'ice', 'nature'], name: 'Permafrost', bonus: 'paralyze', duration: 5, msg: 'Vida preservada no gelo eterno.' },
  { id: 'exp_73', sequence: ['metal', 'metal', 'blood'], name: 'Armas Satânicas', bonus: 'damage', mult: 4.2, msg: 'Aço abençoado com sangue profano!' },
  { id: 'exp_74', sequence: ['metal', 'metal', 'void'], name: 'Antimatéria Bélica', bonus: 'damage', mult: 4.8, msg: 'Armas que não ocupam espaço!' },
  { id: 'exp_75', sequence: ['music', 'music', 'thunder'], name: 'Vibração Elétrica', bonus: 'damage', mult: 3.3, msg: 'Notas que carregam energia!' },
  { id: 'exp_76', sequence: ['music', 'music', 'arcane'], name: 'Ópera Cósmica', bonus: 'damage', mult: 3.8, msg: 'O som da magia pura!' },
  { id: 'exp_77', sequence: ['utility', 'utility', 'earth'], name: 'Reforço Geológico', bonus: 'shield', duration: 15, msg: 'A terra te sustenta!' },
  { id: 'exp_78', sequence: ['utility', 'utility', 'cosmos'], name: 'Suporte das Constelações', bonus: 'regen', duration: 20, msg: 'As estrelas guiam sua cura!' },
  { id: 'exp_79', sequence: ['fire', 'water', 'nature'], name: 'Ecossistema em Chamas', bonus: 'damage', mult: 3.4, msg: 'Toda a natureza queimando no mar!' },
  { id: 'exp_80', sequence: ['physical', 'metal', 'cosmos'], name: 'Armadura do Cometa', bonus: 'shield', duration: 25, msg: 'Poder físico interestelar!' },
  { id: 'exp_81', sequence: ['arcane', 'void', 'time'], name: 'Ponto Zero Arcana', bonus: 'damage', mult: 5.5, msg: 'Conhecimento além do fim dos tempos!' },
  { id: 'exp_82', sequence: ['blood', 'music', 'cosmos'], name: 'Sinfonia do Sangue Estelar', bonus: 'damage', mult: 4.4, msg: 'A música das veias galácticas!' },
  { id: 'exp_83', sequence: ['void', 'light', 'void'], name: 'Luz Negativa', bonus: 'damage', mult: 4.9, msg: 'Brilho que remove a visão e a vida!' },
  { id: 'exp_84', sequence: ['time', 'utility', 'time'], name: 'Recarga de Cronos', bonus: 'reduce_cd', msg: 'Suporte vindo de todas as eras!' },
  { id: 'exp_85', sequence: ['cosmos', 'fire', 'cosmos'], name: 'Sol Explosivo', bonus: 'damage', mult: 5.2, msg: 'Toda a energia solar em um ponto!' },
  { id: 'exp_86', sequence: ['nature', 'blood', 'nature'], name: 'Raízes de Ichor', bonus: 'regen', duration: 15, msg: 'Vida sugada e devolvida em dobro!' },
  { id: 'exp_87', sequence: ['metal', 'arcane', 'metal'], name: 'Alquimia Proibida', bonus: 'damage', mult: 4.0, msg: 'Transmutação bélica mestre!' },
  { id: 'exp_88', sequence: ['physical', 'time', 'physical'], name: 'Soco que Ecoa', bonus: 'damage', mult: 4.3, msg: 'Um golpe que atinge agora e no passado!' },
  { id: 'exp_89', sequence: ['fire', 'thunder', 'wind'], name: 'Tormenta de Plasma', bonus: 'damage', mult: 3.7, msg: 'Chamas, raios e ar em fúria!' },
  { id: 'exp_90', sequence: ['water', 'ice', 'void'], name: 'Zero Hidrolítico', bonus: 'damage', mult: 3.9, msg: 'Nada resta após o congelamento abissal!' },
  { id: 'exp_91', sequence: ['nature', 'earth', 'light'], name: 'Jardim Divino', bonus: 'regen', duration: 18, msg: 'Cura que emana da terra sagrada!' },
  { id: 'exp_92', sequence: ['cosmos', 'void', 'arcane'], name: 'Magia de Buraco Negro', bonus: 'damage', mult: 6.0, msg: 'O ápice da destruição mágica!' },
  { id: 'exp_93', sequence: ['music', 'utility', 'light'], name: 'Himno de Purificação', bonus: 'heal', mult: 5.0, msg: 'O som que limpa todas as feridas!' },
  { id: 'exp_94', sequence: ['time', 'blood', 'void'], name: 'Ciclo do Esquecimento', bonus: 'damage', mult: 4.8, msg: 'Onde vidas e eras desaparecem!' },
  { id: 'exp_95', sequence: ['metal', 'physical', 'arcane'], name: 'Exoesqueleto Mágico', bonus: 'shield', duration: 20, msg: 'Força aumentada por placas rúnicas!' },
  { id: 'exp_96', sequence: ['fire', 'water', 'arcane'], name: 'Mana Escaldante', bonus: 'damage', mult: 3.6, msg: 'Magia que ferve e derrete!' },
  { id: 'exp_97', sequence: ['thunder', 'wind', 'cosmos'], name: 'Pulsar Atmosférico', bonus: 'damage', mult: 3.9, msg: 'Radiação e vento elétricos!' },
  { id: 'exp_98', sequence: ['physical', 'light', 'utility'], name: 'Santuário do Guerreiro', bonus: 'shield', duration: 18, msg: 'Proteção para quem luta!' },
  { id: 'exp_99', sequence: ['void', 'nature', 'time'], name: 'Evolução Entrópica', bonus: 'damage', mult: 4.1, msg: 'A vida que morre e renasce em segundos!' },
  { id: 'exp_100', sequence: ['cosmos', 'cosmos', 'cosmos'], name: 'O Fim de Tudo', bonus: 'damage', mult: 7.0, msg: 'A morte térmica do universo.' },

  // --- UTILITY CATEGORY (40 Spells/Combos) ---
  { id: 'util_chishiki', sequence: ['light', 'utility'], name: 'Chishiki (Conhecimento)', bonus: 'reveal_combo', msg: 'Um segredo alquímico foi revelado!' },
  { id: 'util_kosa', sequence: ['arcane', 'utility', 'light'], name: 'Kōsa (Interseção)', bonus: 'reveal_2_combos', msg: 'Caminhos de poder se cruzam em sua mente.' },
  { id: 'util_mirai', sequence: ['void', 'utility', 'time'], name: 'Mirai (Futuro)', bonus: 'predict_attack', msg: 'Você vê o próximo golpe antes de acontecer.' },
  { id: 'util_jakuten', sequence: ['thunder', 'utility', 'arcane'], name: 'Jakuten (Ponto Fraco)', bonus: 'show_weakness', msg: 'A falha na defesa do inimigo brilha intensamente.' },
  { id: 'util_shingugan', sequence: ['cosmos', 'utility', 'void'], name: 'Shingugan (Olho da Verdade)', bonus: 'boss_eye', msg: 'Nenhum atributo pode ser escondido de você.' },
  { id: 'util_kioku', sequence: ['time', 'utility', 'time'], name: 'Kioku (Memória)', bonus: 'reduce_cd', msg: 'O passado retorna para ajudar o presente.' },
  { id: 'util_hirameki', sequence: ['light', 'utility', 'light'], name: 'Hirameki (Epifania)', bonus: 'hint', msg: 'Uma ideia brilhante surge do nada.' },
  { id: 'util_ryusei', sequence: ['wind', 'utility', 'cosmos'], name: 'Ryūsei (Estrela Cadente)', bonus: 'autocomplete_next', msg: 'A próxima magia voará com precisão estelar.' },
  { id: 'util_tateba', sequence: ['metal', 'utility', 'light'], name: 'Tateba (Escudo de Letras)', bonus: 'ignore_typo_next', msg: 'Seu foco é inquebrável, mesmo com pequenos erros.' },
  { id: 'util_eko', sequence: ['music', 'utility', 'music'], name: 'Eko (Eco)', bonus: 'echo_next', msg: 'As notas ressoam, prontas para se repetir.' },
  { id: 'util_hoshi', sequence: ['time', 'utility', 'cosmos'], name: 'Hoshi (Aceleração)', bonus: 'combo_window_up', msg: 'O tempo desacelera para suas mãos.' },
  { id: 'util_kiyome', sequence: ['water', 'utility', 'light'], name: 'Kiyome (Purificação)', bonus: 'cleanse', msg: 'Toda impureza é lavada pela luz.' },
  { id: 'util_hayasa', sequence: ['wind', 'utility', 'wind'], name: 'Hayasa (Velocidade)', bonus: 'reduce_cd', msg: 'Sua mente se move mais rápido que o vento.' },
  { id: 'util_mamori', sequence: ['earth', 'utility', 'metal'], name: 'Mamori (Proteção)', bonus: 'shield', duration: 5, msg: 'Uma guarda absoluta se manifesta.' },
  { id: 'util_yume', sequence: ['void', 'utility', 'music'], name: 'Yume (Sonho)', bonus: 'paralyze', duration: 2, msg: 'O inimigo mergulha em um sono profundo.' },
  { id: 'util_gakushu', sequence: ['arcane', 'utility', 'arcane'], name: 'Gakushu (Estudo)', bonus: 'reveal_combo', msg: 'Padrões mágicos se tornam claros.' },
  { id: 'util_bunseki', sequence: ['metal', 'utility', 'arcane'], name: 'Bunseki (Análise)', bonus: 'show_weakness', msg: 'Dados sobre a estrutura do inimigo processados.' },
  { id: 'util_keikai', sequence: ['wind', 'utility', 'time'], name: 'Keikai (Alerta)', bonus: 'shield', duration: 2, msg: 'Sentidos aguçados para evitar o perigo.' },
  { id: 'util_shuchu', sequence: ['physical', 'utility', 'physical'], name: 'Shūchū (Concentração)', bonus: 'damage_buff', duration: 2, msg: 'Foco total no próximo golpe.' },
  { id: 'util_reisei', sequence: ['ice', 'utility', 'water'], name: 'Reisei (Calma)', bonus: 'cleanse', msg: 'Mente fria, corpo restaurado.' },
  { id: 'util_kyoka', sequence: ['fire', 'utility', 'arcane'], name: 'Kyōka (Melhoria)', bonus: 'damage_buff', duration: 3, msg: 'Poder amplificado por runas de fogo.' },
  { id: 'util_tenji', sequence: ['light', 'utility', 'arcane'], name: 'Tenji (Exibição)', bonus: 'reveal_combo', msg: 'O conhecimento flutua ao seu redor.' },
  { id: 'util_sagase', sequence: ['nature', 'utility', 'wind'], name: 'Sagase (Busca)', bonus: 'reveal_combo', msg: 'Explorando as possibilidades do terreno.' },
  { id: 'util_jigen', sequence: ['void', 'utility', 'void'], name: 'Jigen (Dimensão)', bonus: 'paralyze', duration: 3, msg: 'O inimigo foi isolado em outra dimensão.' },
  { id: 'util_tenkei', sequence: ['cosmos', 'utility', 'light'], name: 'Tenkei (Revelação)', bonus: 'reveal_2_combos', msg: 'Uma mensagem divina traz clareza.' },
  { id: 'util_dokusho', sequence: ['music', 'utility', 'arcane'], name: 'Dokusho (Leitura)', bonus: 'hint', msg: 'As palavras do grimoire cantam para você.' },
  { id: 'util_honyaku', sequence: ['time', 'utility', 'arcane'], name: 'Honyaku (Tradução)', bonus: 'hint', msg: 'O idioma arcano se torna trivial.' },
  { id: 'util_fukushu', sequence: ['blood', 'utility', 'time'], name: 'Fukushu (Revisão)', bonus: 'reduce_cd', msg: 'Aprendendo com o sangue derramado.' },
  { id: 'util_shimei', sequence: ['light', 'utility', 'metal'], name: 'Shimei (Missão)', bonus: 'force_bonus', msg: 'Um objetivo traçado pela vontade divina.' },
  { id: 'util_kunren', sequence: ['physical', 'utility', 'earth'], name: 'Kunren (Treino)', bonus: 'damage_buff', duration: 4, msg: 'Anos de treino condensados em um instante.' },
  { id: 'util_enjo', sequence: ['nature', 'utility', 'water'], name: 'Enjo (Suporte)', bonus: 'regen', duration: 10, msg: 'A natureza sustenta sua jornada.' },
  { id: 'util_kyoyu', sequence: ['arcane', 'utility', 'void'], name: 'Kyōyū (Partilha)', bonus: 'reduce_cd', msg: 'Energia trocada entre os planos.' },
  { id: 'util_mugen', sequence: ['cosmos', 'utility', 'time'], name: 'Mugen (Infinito)', bonus: 'reduce_cd', msg: 'As algemas do tempo foram rompidas.' },
  { id: 'util_ketsumatsu', sequence: ['void', 'utility', 'cosmos'], name: 'Ketsumatsu (Final)', bonus: 'damage', mult: 5.0, msg: 'O capítulo final está sendo escrito.' },
  { id: 'util_hikari', sequence: ['light', 'utility', 'wind'], name: 'Hikari (Brilho)', bonus: 'blind', duration: 3, msg: 'Uma luz ofuscante cega a ameaça.' },
  { id: 'util_yosoku', sequence: ['time', 'utility', 'wind'], name: 'Yosoku (Previsão)', bonus: 'predict_attack', msg: 'O rastro do vento diz o que virá.' },
  { id: 'util_tsuyosa', sequence: ['physical', 'utility', 'fire'], name: 'Tsuyosa (Força)', bonus: 'damage_buff', duration: 1, msg: 'Músculos ardem com poder.' },
  { id: 'util_kiroku', sequence: ['metal', 'utility', 'time'], name: 'Kiroku (Registro)', bonus: 'boss_eye', msg: 'A história do inimigo é lida por você.' },
  { id: 'util_setsuna', sequence: ['time', 'utility', 'void'], name: 'Setsuna (Instante)', bonus: 'reduce_cd', msg: 'Em um piscar de olhos, tudo recarrega.' },
  { id: 'util_shinwa', sequence: ['cosmos', 'utility', 'arcane'], name: 'Shinwa (Mito)', bonus: 'reveal_2_combos', msg: 'Lendas antigas guiam seus dedos.' },
];

export const MONSTER_REACTION_TRIGGERS = {
  elements: {
    fire: ['Que calor! Pare com isso!', 'Isso arde! 🔥', 'Vai me cozinhar?'],
    water: ['Estou ficando ensopado...', 'Onde está minha toalha?', 'Glub glub... para com a água!'],
    thunder: ['ZAP! Isso doeu!', 'Meus pelos estão arrepiados!', 'Ei! Cuidado com essa voltagem!'],
    void: ['Sinto... o nada...', 'Para onde foi minha sanidade?', 'Isso é... assustador.'],
    ice: ['Brrr... que frio!', 'Vou virar um picolé!', 'Congelante!'],
    nature: ['Folhas por todo lado...', 'Sou alérgico a pólen!', 'A natureza está brava?'],
    metal: ['Isso é pesado!', 'Tinido metálico!', 'Ai! Me pegou em cheio!'],
    light: ['Dói os olhos!', 'Tanta luz...', 'Sou uma criatura das trevas, pare!'],
    logic: ['Não faz sentido!', 'Onde está meu script?', 'Erro 404: Monstro não encontrado.'],
    cosmos: ['Mundo... vasto...', 'Estrelas... tantas estrelas...', 'O universo é grande demais.'],
  },
  statuses: {
    burn: ['Estou em chamas! Alguém me ajude!', 'Fogo! Fogo! 🔥'],
    poison: ['Sinto-me... enjoado...', 'O que tinha nessa poção? 🤢'],
    freeze: ['T-tão... f-frio...', 'Não consigo... me m-mexer...'],
  },
  hp: {
    lethal: ['Este é o meu fim...', 'Você... é forte demais...', 'Não me esqueça!'],
    half: ['Ainda não acabou!', 'Estou só começando!', 'Você luta bem...'],
  }
};
