import { ElementType, StatusType } from './types';

export const ELEMENTS_INFO: Record<ElementType, { name: string; icon: string; color: string; bg: string; description: string }> = {
  fire: { name: 'Fogo', icon: '🔥', color: '#8b0000', bg: '#f9f3e5', description: 'Causa dano adicional ao longo do tempo (queimadura).' },
  water: { name: 'Água', icon: '🌊', color: '#1e3a8a', bg: '#f9f3e5', description: 'Fluxo contínuo, magias de ataque focadas.' },
  thunder: { name: 'Trovão', icon: '⚡', color: '#854d0e', bg: '#f9f3e5', description: 'Pode paralisar o inimigo, impedindo suas ações.' },
  wind: { name: 'Vento', icon: '🌪️', color: '#134e4a', bg: '#f9f3e5', description: 'Ataques rápidos e consistentes.' },
  nature: { name: 'Natureza', icon: '🌿', color: '#14532d', bg: '#f9f3e5', description: 'Ataques que podem usar veneno ou curar.' },
  physical: { name: 'Físico', icon: '⚔️', color: '#334155', bg: '#f9f3e5', description: 'Golpes marciais e poder cru. Pode causar sangramento.' },
  light: { name: 'Luz & Cura', icon: '✨', color: '#b45309', bg: '#f9f3e5', description: 'Magias focadas em cura, escudo e aumento de atributos.' },
  arcane: { name: 'Arcano', icon: '🔮', color: '#4c1d95', bg: '#f9f3e5', description: 'Magia pura, altera a realidade e causa alto dano.' },
  void: { name: 'Vazio & Tempo', icon: '🌌', color: '#312e81', bg: '#f9f3e5', description: 'Manipula o espaço-tempo para debuffs.' },
  utility: { name: 'Suporte', icon: '🌟', color: '#713f12', bg: '#f9f3e5', description: 'Magias focadas em purificar debuffs ou bônus.' },
  time: { name: 'Tempo', icon: '⏳', color: '#312e81', bg: '#f9f3e5', description: 'Altera o fluxo e as recargas das magias.' },
  music: { name: 'Música', icon: '🎵', color: '#4c1d95', bg: '#f9f3e5', description: 'Feitiços que causam status negativos e dano.' },
  earth: { name: 'Terra', icon: '🪨', color: '#57534e', bg: '#f9f3e5', description: 'Magias pesadas, de resistência, causar lentidão ou fraqueza.' },
  ice: { name: 'Gelo', icon: '❄️', color: '#0ea5e9', bg: '#f9f3e5', description: 'Pode congelar o alvo, impedindo a ação no turno.' },
  metal: { name: 'Metal', icon: '⚙️', color: '#71717a', bg: '#f9f3e5', description: 'Armas conjuradas, dano físico intenso.' },
  blood: { name: 'Sangue', icon: '🩸', color: '#991b1b', bg: '#f9f3e5', description: 'Sacrifícios ou feitiços necromânticos que sugam vida.' },
  cosmos: { name: 'Cosmos', icon: '🌌', color: '#1e1b4b', bg: '#f9f3e5', description: 'Feitiços de destruição massiva de alto nível.' }
};

export const STATUS_ICONS: Record<StatusType, string> = {
  burn: '🔥', bleed: '🩸', freeze: '❄️', paralyze: '⚡', weaken: '💧', shield: '🛡️', regen: '✨', poison: '🤢', blind: '👁️', silence: '🤐',
  hint: '💡', cleanse: '✨', reduce_cd: '⏳', force_bonus: '🎯', damage_buff: '💪'
};

export const STATUS_NAMES_PT: Record<StatusType, string> = {
  burn: 'Queimadura', bleed: 'Sangramento', freeze: 'Congelamento', paralyze: 'Paralisia', weaken: 'Fraqueza', shield: 'Escudo', regen: 'Regeneração', poison: 'Veneno', blind: 'Cegueira', silence: 'Selado',
  hint: 'Dica', cleanse: 'Purificação', reduce_cd: 'Recarga', force_bonus: 'Ponto Fraco', damage_buff: 'Aumento de Dano'
};

export const FLAVOR_WORDS: Record<string, { t: string; r: string }> = {
  'baka': { t: 'Idiota', r: 'Quem você está chamando de idiota?! 💢' },
  'aho': { t: 'Estúpido', r: 'Olhe para você antes de falar! 🙄' },
  'shine': { t: 'Morra', r: 'Vem tentar a sorte! 🔪' },
  'kuso': { t: 'Droga', r: 'Frustrado? Que pena... 😈' },
  'nani': { t: 'O quê?', r: 'Isso mesmo que você ouviu! 🗣️' },
  'yamete': { t: 'Pare', r: 'Eu nunca vou parar! ⚔️' },
  'tasukete': { t: 'Socorro', r: 'Ninguém virá te salvar! 🕸️' },
  'kawaii': { t: 'Fofo', r: 'N-Não me chame de fofo! 😳' },
  'gomen': { t: 'Desculpa', r: 'É tarde demais para perdão! 🗡️' },
  'omae': { t: 'Você', r: 'Eu?! O que tem eu?! 🤨' },
  'dorobou': { t: 'Ladrão', r: 'Achado não é roubado! 🏃‍♂️💨' },
  'yowai': { t: 'Fraco', r: 'Vou te mostrar quem é o fraco! 💥' },
  'konnichiwa': { t: 'Olá', r: 'Não temos tempo para cumprimentos! ⚔️' },
  'arigatou': { t: 'Obrigado', r: 'Não agradeça por sua ruína! 💀' },
  'sayounara': { t: 'Adeus', r: 'Adeus para sempre, herói tolo! 👋' },
  'kakkoii': { t: 'Legal', r: 'Humph, eu sei que sou estiloso! 😎' },
  'sugoi': { t: 'Incrível', r: 'Impressionado com o meu poder?! 🌠' },
  'yabai': { t: 'Perigoso', r: 'Você que corre perigo real! ⚠️' },
  'kimoi': { t: 'Nojento', r: 'Olha para a sua cara! 🤮' },
  'uzai': { t: 'Irritante', r: 'Vou ser ainda mais irritante! 🦟' },
  'urusai': { t: 'Barulhento', r: 'VOU GRITAR MAIS ALTO! 📢' },
  'damare': { t: 'Cale-se', r: 'Me obrigue a calar a boca! 🤐' },
  'chotto': { t: 'Um pouco', r: 'Nem um segundo de pausa! ⏱️' },
  'matte': { t: 'Espere', r: 'Monstros não esperam! 🏃‍♂️' },
  'hayaku': { t: 'Rápido', r: 'Estou indo te destruir! 🌪️' },
  'nigero': { t: 'Fuja', r: 'Não há para onde fugir! 🚪🔒' },
  'kowai': { t: 'Assustador', r: 'Sinta o terror! 👻' },
  'itai': { t: 'Dói', r: 'Vai doer muito mais! 🩸' },
  'kurushii': { t: 'Doloroso', r: 'Sofra sob o meu poder! 😈' },
  'sumimasen': { t: 'Com licença', r: 'Sem licença para fracos! 🛑' },
  'muda': { t: 'Inútil', r: 'MUDA MUDA MUDA! 👊' },
  'zako': { t: 'Lixo', r: 'Eu sou a elite das trevas! 👑' }
};

export const ENEMY_SKILLS_POOL: Record<string, any> = {
  'heal': { name: 'Cura Regenerativa', type: 'heal', mult: 0.2 }, 
  'burn': { name: 'Sopro de Fogo', type: 'status', effect: 'burn', duration: 3 },
  'poison': { name: 'Névoa Venenosa', type: 'status', effect: 'poison', duration: 4 },
  'paralyze': { name: 'Olhar Eletrizante', type: 'status', effect: 'paralyze', duration: 1 },
  'weaken': { name: 'Fraqueza', type: 'status', effect: 'weaken', duration: 3 },
  'shield': { name: 'Pele de Ferro', type: 'status', effect: 'shield', duration: 3 },
  'lifesteal': { name: 'Drenar Vida', type: 'lifesteal', mult: 1.0 }, 
  'critical': { name: 'Ataque Brutal', type: 'attack', mult: 2.0 }, 
  'summon': { name: 'Lacaio', type: 'summon', mult: 0.3 }, 
  'blind': { name: 'Cegueira', type: 'status', effect: 'blind', duration: 2 },
  'seal': { name: 'Selo do Conhecimento', type: 'status', effect: 'silence', duration: 4 },
  'silence_song': { name: 'Canção do Silêncio', type: 'status', effect: 'silence', duration: 2 },
  'heavy_strike': { name: 'Golpe Pesado', type: 'attack', mult: 1.8 },
  'void_gaze': { name: 'Olhar do Vazio', type: 'status', effect: 'weaken', duration: 4 },
  'freeze': { name: 'Nevasca', type: 'status', effect: 'freeze', duration: 2 },
  'corrupt': { name: 'Toque Corrupto', type: 'status', effect: 'poison', duration: 5 },
  'quake': { name: 'Terremoto', type: 'attack', mult: 1.5 },
  'tsunami': { name: 'Tsunami', type: 'attack', mult: 1.4 },
  'thunderstorm': { name: 'Tempestade de Raios', type: 'attack', mult: 1.6 },
  'tornado': { name: 'Tornado Destrutivo', type: 'attack', mult: 1.3 },
  'meteor': { name: 'Chuva de Meteoros', type: 'attack', mult: 2.5 },
  'light_ray': { name: 'Feixe de Luz', type: 'attack', mult: 1.2 },
  'mind_control': { name: 'Controle Mental', type: 'status', effect: 'paralyze', duration: 2 },
  'bleed_bite': { name: 'Mordida Profunda', type: 'status', effect: 'bleed', duration: 4 },
  'blood_rain': { name: 'Chuva de Sangue', type: 'lifesteal', mult: 1.5 },
  'time_stop': { name: 'Parar o Tempo', type: 'status', effect: 'freeze', duration: 3 },
  'acid_spit': { name: 'Cuspe Ácido', type: 'status', effect: 'weaken', duration: 5 },
  'inferno': { name: 'Inferno', type: 'status', effect: 'burn', duration: 6 },
  'frostbite': { name: 'Mordida Gélida', type: 'status', effect: 'freeze', duration: 1 },
  'earth_wall': { name: 'Parede de Terra', type: 'status', effect: 'shield', duration: 4 },
  'divine_shield': { name: 'Escudo Divino', type: 'status', effect: 'shield', duration: 5 },
  'dark_matter': { name: 'Matéria Escura', type: 'attack', mult: 2.2 },
  'solar_flare': { name: 'Erupção Solar', type: 'attack', mult: 1.9 },
  'lunar_eclipse': { name: 'Eclipse Lunar', type: 'status', effect: 'blind', duration: 4 },
  'venom_stinger': { name: 'Ferrão Venenoso', type: 'status', effect: 'poison', duration: 3 },
  'ghost_touch': { name: 'Toque Fantasma', type: 'status', effect: 'weaken', duration: 2 },
  'death_scythe': { name: 'Foice da Morte', type: 'attack', mult: 3.0 },
  'soul_drain': { name: 'Drenar Alma', type: 'lifesteal', mult: 2.0 },
  'illusion': { name: 'Ilusão', type: 'status', effect: 'blind', duration: 3 },
  'mirror_image': { name: 'Imagem Espelhada', type: 'status', effect: 'shield', duration: 2 },
  'roar': { name: 'Rugido Aterrorizante', type: 'status', effect: 'paralyze', duration: 1 },
  'sonic_boom': { name: 'Estrondo Sônico', type: 'attack', mult: 1.5 },
  'laser_beam': { name: 'Feixe de Laser', type: 'attack', mult: 1.7 },
  'crystal_prison': { name: 'Prisão de Cristal', type: 'status', effect: 'freeze', duration: 2 },
  'shadow_strike': { name: 'Golpe Sombrio', type: 'attack', mult: 1.4 },
  'holy_light': { name: 'Luz Sagrada', type: 'heal', mult: 0.5 },
  'demonic_aura': { name: 'Aura Demoníaca', type: 'status', effect: 'weaken', duration: 5 },
  'vampiric_bite': { name: 'Mordida Vampírica', type: 'lifesteal', mult: 1.2 },
  'toxic_spores': { name: 'Esporos Tóxicos', type: 'status', effect: 'poison', duration: 5 },
  'curse': { name: 'Maldição Profunda', type: 'status', effect: 'silence', duration: 3 },
  'nightmare': { name: 'Pesadelo', type: 'status', effect: 'weaken', duration: 4 }
};

export const SEQUENCE_BONUSES = [
  // --- TIER 1: ELEMENTAL PAIRS (2-Spells) ---
  { id: 'fire_wind', sequence: ['fire', 'wind'], name: 'Tempestade de Chamas', bonus: 'damage', mult: 1.6, msg: 'O vento alimenta o incêndio!' },
  { id: 'water_ice', sequence: ['water', 'ice'], name: 'Nevasca Prateada', bonus: 'paralyze', duration: 1, msg: 'A água congela instantaneamente!' },
  { id: 'earth_physical', sequence: ['earth', 'physical'], name: 'Impacto Vulcânico', bonus: 'damage', mult: 1.7, msg: 'A terra treme sob seus pés!' },
  { id: 'light_arcane', sequence: ['light', 'arcane'], name: 'Iluminação Arcana', bonus: 'reduce_cd', msg: 'Conhecimento puro flui em sua mente!' },
  { id: 'nature_water', sequence: ['nature', 'water'], name: 'Crescimento Acelerado', bonus: 'regen', duration: 4, msg: 'A umidade desperta as raízes!' },
  { id: 'thunder_metal', sequence: ['thunder', 'metal'], name: 'Supercondução', bonus: 'damage', mult: 1.8, msg: 'O metal amplifica o choque!' },
  { id: 'blood_fire', sequence: ['blood', 'fire'], name: 'Inferno de Sangue', bonus: 'damage', mult: 1.9, msg: 'O sangue ferve em chamas negras!' },
  { id: 'void_time', sequence: ['void', 'time'], name: 'Abismo Temporal', bonus: 'paralyze', duration: 2, msg: 'O tempo para no vácuo!' },
  { id: 'music_wind', sequence: ['music', 'wind'], name: 'Sinfonia dos Ventos', bonus: 'damage', mult: 1.5, msg: 'As notas viajam na brisa!' },
  { id: 'metal_fire', sequence: ['metal', 'fire'], name: 'Forja Ardente', bonus: 'damage', mult: 1.7, msg: 'Lâminas moldadas no calor!' },
  { id: 'ice_thunder', sequence: ['ice', 'thunder'], name: 'Choque Críptico', bonus: 'damage', mult: 1.6, msg: 'Eletricidade estática no gelo!' },
  { id: 'cosmos_void', sequence: ['cosmos', 'void'], name: 'Colapso Estelar', bonus: 'damage', mult: 2.1, msg: 'Uma estrela morre no vazio!' },
  { id: 'utility_light', sequence: ['utility', 'light'], name: 'Bênção do Suporte', bonus: 'shield', duration: 4, msg: 'Proteção divina reforçada!' },
  { id: 'nature_earth', sequence: ['nature', 'earth'], name: 'Floresta Petrificada', bonus: 'damage', mult: 1.7, msg: 'A força da terra nas plantas!' },
  { id: 'physical_wind', sequence: ['physical', 'wind'], name: 'Golpe Vendaval', bonus: 'damage', mult: 1.6, msg: 'Ataque veloz como o vento!' },
  { id: 'fire_arcane', sequence: ['fire', 'arcane'], name: 'Chama de Prometeu', bonus: 'damage', mult: 2.0, msg: 'Fogo mágico proibido!' },

  // --- TIER 2: PRIMARY TRIPLES (3-Spells) ---
  { id: 'fire_3', sequence: ['fire', 'fire', 'fire'], name: 'Erupção Carmesim', bonus: 'damage', mult: 1.8, msg: 'A chama se intensifica!' },
  { id: 'water_3', sequence: ['water', 'water', 'water'], name: 'Fluxo Eterno', bonus: 'heal', mult: 1.6, msg: 'As águas te purificam!' },
  { id: 'thunder_3', sequence: ['thunder', 'thunder', 'thunder'], name: 'Juízo do Relâmpago', bonus: 'paralyze', duration: 2, msg: 'O trovão ruge!' },
  { id: 'light_3', sequence: ['light', 'light', 'light'], name: 'Aura do Redentor', bonus: 'shield', duration: 5, msg: 'Uma luz divina te protege!' },
  { id: 'physical_3', sequence: ['physical', 'physical', 'physical'], name: 'Combo Devastador', bonus: 'damage', mult: 2.2, msg: 'Uma sequência de golpes perfeitos!' },
  { id: 'nature_3', sequence: ['nature', 'nature', 'nature'], name: 'Dom da Floresta', bonus: 'regen', duration: 6, msg: 'A natureza pulsa em você!' },
  { id: 'arcane_3', sequence: ['arcane', 'arcane', 'arcane'], name: 'Supernova Arcana', bonus: 'damage', mult: 2.5, msg: 'Explosão de mana pura!' },
  { id: 'void_3', sequence: ['void', 'void', 'void'], name: 'Singularidade', bonus: 'damage', mult: 2.8, msg: 'Tudo é sugado pelo vazio!' },
  { id: 'ice_3', sequence: ['ice', 'ice', 'ice'], name: 'Zero Absoluto', bonus: 'paralyze', duration: 3, msg: 'O movimento cessa completamente!' },
  { id: 'earth_3', sequence: ['earth', 'earth', 'earth'], name: 'Sismo do Olimpo', bonus: 'damage', mult: 2.1, msg: 'O mundo se racha ao meio!' },
  { id: 'trinity', sequence: ['fire', 'water', 'thunder'], name: 'Trindade Elemental', bonus: 'damage', mult: 2.4, msg: 'O poder dos elementos converge!' },

  // --- TIER 3: COMPLEX COMBINATIONS (3-Spells Mix) ---
  { id: 'fire_water_ice', sequence: ['fire', 'water', 'ice'], name: 'Fúria do Vapor Frio', bonus: 'damage', mult: 2.0, msg: 'Mudança brusca de temperatura!' },
  { id: 'light_shield_regen', sequence: ['light', 'nature', 'light'], name: 'Santuário Vivo', bonus: 'shield', duration: 6, msg: 'Uma barreira que se cura sozinha!' },
  { id: 'time_void_arcane', sequence: ['time', 'void', 'arcane'], name: 'Fissão da Realidade', bonus: 'damage', mult: 2.7, msg: 'As leis da física se desfazem!' },
  { id: 'blood_arcane_void', sequence: ['blood', 'arcane', 'void'], name: 'Ritual do Abismo', bonus: 'damage', mult: 3.0, msg: 'Sacrifício por poder proibido!' },
  { id: 'metal_physical_thunder', sequence: ['metal', 'physical', 'thunder'], name: 'Maça de Mjolnir', bonus: 'damage', mult: 2.6, msg: 'Peso e eletricidade devastadores!' },
  { id: 'music_time_music', sequence: ['music', 'time', 'music'], name: 'Roda do Destino', bonus: 'reduce_cd', msg: 'A canção que volta no tempo!' },
  { id: 'cosmos_light_cosmos', sequence: ['cosmos', 'light', 'cosmos'], name: 'Big Bang Galático', bonus: 'damage', mult: 3.2, msg: 'Criação e destruição em um só golpe!' },
  { id: 'fire_earth_metal', sequence: ['fire', 'earth', 'metal'], name: 'Chuva de Magma', bonus: 'damage', mult: 2.3, msg: 'Metal derretido do núcleo da terra!' },
  { id: 'wind_ice_wind', sequence: ['wind', 'ice', 'wind'], name: 'Furacão Glacial', bonus: 'paralyze', duration: 2, msg: 'Frio cortante imparável!' },
  { id: 'nature_utility_nature', sequence: ['nature', 'utility', 'nature'], name: 'Éden Restaurado', bonus: 'regen', duration: 8, msg: 'Cura definitiva da floresta!' },
  
  // --- TIER 4: THEMATIC CHAINS (Specific mix) ---
  { id: 'physical_fire_physical', sequence: ['physical', 'fire', 'physical'], name: 'Punho do Dragão', bonus: 'damage', mult: 2.3, msg: 'Chamas nos golpes físicos!' },
  { id: 'water_thunder_wind', sequence: ['water', 'thunder', 'wind'], name: 'Ciclone Elétrico', bonus: 'damage', mult: 2.2, msg: 'Uma tempestade perfeita!' },
  { id: 'void_blood_time', sequence: ['void', 'blood', 'time'], name: 'Gênese Sombria', bonus: 'heal', mult: 2.0, msg: 'Vida extraída do próprio vácuo!' },
  { id: 'metal_metal_fire', sequence: ['metal', 'metal', 'fire'], name: 'Arsenal Infinito', bonus: 'damage', mult: 2.5, msg: 'Chuva de espadas incandescentes!' },
  { id: 'arcane_light_arcane', sequence: ['arcane', 'light', 'arcane'], name: 'Veredito Sagrado', bonus: 'damage', mult: 2.8, msg: 'O julgamento final do mago!' },
  { id: 'earth_water_nature', sequence: ['earth', 'water', 'nature'], name: 'Pântano Engolidor', bonus: 'paralyze', duration: 3, msg: 'O solo se torna uma armadilha!' },
  { id: 'thunder_thunder_void', sequence: ['thunder', 'thunder', 'void'], name: 'Relâmpago Negro', bonus: 'damage', mult: 2.6, msg: 'Eletricidade que consome a luz!' },
  { id: 'cosmos_arcane_time', sequence: ['cosmos', 'arcane', 'time'], name: 'Viagem Astral', bonus: 'reduce_cd', msg: 'Sua mente transcende as eras!' },
  { id: 'music_fire_music', sequence: ['music', 'fire', 'music'], name: 'Rapsódia Infernal', bonus: 'damage', mult: 2.2, msg: 'Música que queima a alma!' },
  { id: 'ice_nature_light', sequence: ['ice', 'nature', 'light'], name: 'Aurora Boreal', bonus: 'shield', duration: 5, msg: 'A beleza do gelo protege você!' },

  // --- TIER 5: THE REMAINING (Up to ~100) ---
  { id: 'wind_wind_physical', sequence: ['wind', 'wind', 'physical'], name: 'Passo de Lâmina', bonus: 'damage', mult: 2.0, msg: 'Cortes invisíveis no ar!' },
  { id: 'blood_blood_physical', sequence: ['blood', 'blood', 'physical'], name: 'Berserker Imortal', bonus: 'regen', duration: 4, msg: 'Sua dor se torna força!' },
  { id: 'metal_earth_void', sequence: ['metal', 'earth', 'void'], name: 'Caixão de Ferro', bonus: 'damage', mult: 2.4, msg: 'O inimigo é enterrado vivo!' },
  { id: 'time_time_light', sequence: ['time', 'time', 'light'], name: 'Rebelião do Passado', bonus: 'heal', mult: 2.2, msg: 'Suas feridas voltam a não existir!' },
  { id: 'arcane_arcane_nature', sequence: ['arcane', 'arcane', 'nature'], name: 'Quimera Elemental', bonus: 'damage', mult: 2.5, msg: 'Magia e natureza distorcidas!' },
  { id: 'fire_metal_fire', sequence: ['fire', 'metal', 'fire'], name: 'Metal Líquido', bonus: 'damage', mult: 2.2, msg: 'Um mar de ferro fervendo!' },
  { id: 'water_water_void', sequence: ['water', 'water', 'void'], name: 'Tsunami das Sombras', bonus: 'damage', mult: 2.3, msg: 'Água negra que afoga em desespero!' },
  { id: 'thunder_wind_thunder', sequence: ['thunder', 'wind', 'thunder'], name: 'Raio de Tempestade', bonus: 'damage', mult: 2.4, msg: 'Atingindo com a fúria do céu!' },
  { id: 'nature_blood_nature', sequence: ['nature', 'blood', 'nature'], name: 'Flores de Sangue', bonus: 'damage', mult: 2.6, msg: 'Plantas que se alimentam de vida!' },
  { id: 'light_cosmos_light', sequence: ['light', 'cosmos', 'light'], name: 'Nebulosa Sagrada', bonus: 'shield', duration: 7, msg: 'A luz das estrelas te envolve!' },
  { id: 'physical_physical_earth', sequence: ['physical', 'physical', 'earth'], name: 'Quebra-Montanhas', bonus: 'damage', mult: 2.4, msg: 'Um golpe que divide picos!' },
  { id: 'void_void_arcane', sequence: ['void', 'void', 'arcane'], name: 'Vento de Éter', bonus: 'damage', mult: 2.7, msg: 'O sopro do fim do mundo!' },
  { id: 'time_music_time', sequence: ['time', 'music', 'time'], name: 'Cronômetro Melódico', bonus: 'paralyze', duration: 2, msg: 'O compasso do tempo desestabilizado!' },
  { id: 'metal_light_metal', sequence: ['metal', 'light', 'metal'], name: 'Armadura da Fé', bonus: 'shield', duration: 8, msg: 'Metal abençoado impenetrável!' },
  { id: 'cosmos_cosmos_void', sequence: ['cosmos', 'cosmos', 'void'], name: 'Supervazio Estelar', bonus: 'damage', mult: 3.5, msg: 'O universo engolindo a si mesmo!' },
  { id: 'ice_ice_blood', sequence: ['ice', 'ice', 'blood'], name: 'Gelo Vampírico', bonus: 'damage', mult: 2.5, msg: 'Espinhos de gelo que drenam o alvo!' },
  { id: 'fire_fire_arcane', sequence: ['fire', 'fire', 'arcane'], name: 'Explosão Gnóstica', bonus: 'damage', mult: 2.6, msg: 'O fogo do conhecimento supremo!' },
  { id: 'nature_nature_utility', sequence: ['nature', 'nature', 'utility'], name: 'Jardim de Panacéia', bonus: 'regen', duration: 10, msg: 'Cura absoluta por turnos!' },
  { id: 'thunder_thunder_earth', sequence: ['thunder', 'thunder', 'earth'], name: 'Magnetismo Terrestre', bonus: 'damage', mult: 2.5, msg: 'Poder de atração esmagador!' },
  { id: 'water_water_light', sequence: ['water', 'water', 'light'], name: 'Fonte da Juventude', bonus: 'heal', mult: 3.0, msg: 'Água abençoada restauradora!' },
  { id: 'physical_physical_ice', sequence: ['physical', 'physical', 'ice'], name: 'Impacto de Geada', bonus: 'paralyze', duration: 1, msg: 'Punhos que congelam ao toque!' },
  { id: 'arcane_arcane_time', sequence: ['arcane', 'arcane', 'time'], name: 'Loop Teúrgico', bonus: 'reduce_cd', msg: 'Conhecimento infinito reciclado!' },
  { id: 'blood_blood_void', sequence: ['blood', 'blood', 'void'], name: 'Echarpe das Almas', bonus: 'damage', mult: 3.0, msg: 'Muitas vidas por um só golpe!' },
  { id: 'void_void_cosmos', sequence: ['void', 'void', 'cosmos'], name: 'Gênesis Reversa', bonus: 'damage', mult: 3.8, msg: 'Tudo volta ao ponto zero!' },
  { id: 'light_light_wind', sequence: ['light', 'light', 'wind'], name: 'Asas de Serafim', bonus: 'shield', duration: 6, msg: 'Proteção alada divina!' },
  { id: 'fire_fire_nature', sequence: ['fire', 'fire', 'nature'], name: 'Carvão de Fênix', bonus: 'regen', duration: 5, msg: 'Cinzas que dão vida!' },
  { id: 'water_water_earth', sequence: ['water', 'water', 'earth'], name: 'Dilúvio Detrítico', bonus: 'damage', mult: 2.2, msg: 'Uma avalanche de lama líquida!' },
  { id: 'thunder_thunder_light', sequence: ['thunder', 'thunder', 'light'], name: 'Relâmpago Glorioso', bonus: 'damage', mult: 2.8, msg: 'A luz que cega e destrói!' },
  { id: 'nature_nature_wind', sequence: ['nature', 'nature', 'wind'], name: 'Polinização Selvagem', bonus: 'regen', duration: 4, msg: 'Vida espalhada pelo vento!' },
  { id: 'physical_physical_metal', sequence: ['physical', 'physical', 'metal'], name: 'Gume Perfeito', bonus: 'damage', mult: 2.6, msg: 'Força física pura com gumes afiados!' },
  { id: 'arcane_arcane_blood', sequence: ['arcane', 'arcane', 'blood'], name: 'Pacto de Ichor', bonus: 'damage', mult: 3.2, msg: 'Magia reforçada por sangue vital!' },
  { id: 'blood_blood_light', sequence: ['blood', 'blood', 'light'], name: 'Redenção Escarlate', bonus: 'heal', mult: 2.5, msg: 'Sangue purificado pela luz!' },
  { id: 'void_void_time', sequence: ['void', 'void', 'time'], name: 'Cronos Inanimado', bonus: 'paralyze', duration: 4, msg: 'O congelamento eterno do tempo!' },
  { id: 'cosmos_cosmos_light', sequence: ['cosmos', 'cosmos', 'light'], name: 'Farol das Estrelas', bonus: 'shield', duration: 10, msg: 'Impenetrabilidade cósmica!' },
  { id: 'ice_ice_water', sequence: ['ice', 'ice', 'water'], name: 'Estalactite Profunda', bonus: 'damage', mult: 2.4, msg: 'Peso e frio das profundezas!' },
  { id: 'metal_metal_earth', sequence: ['metal', 'metal', 'earth'], name: 'Fortaleza Móvel', bonus: 'shield', duration: 12, msg: 'Proteção extrema movida pela terra!' },
  { id: 'music_music_cosmos', sequence: ['music', 'music', 'cosmos'], name: 'Harmonia das Esferas', bonus: 'reduce_cd', msg: 'A vibração secreta do universo!' },
  { id: 'fire_fire_blood', sequence: ['fire', 'fire', 'blood'], name: 'Chama Hemática', bonus: 'damage', mult: 3.0, msg: 'O calor que consome o corpo!' },
  { id: 'water_water_ice', sequence: ['water', 'water', 'ice'], name: 'Geada Mestra', bonus: 'paralyze', duration: 2, msg: 'O ápice do congelamento hídrico!' },
  { id: 'thunder_thunder_metal', sequence: ['thunder', 'thunder', 'metal'], name: 'Forja Galvânica', bonus: 'damage', mult: 2.7, msg: 'Metal fundido por raios!' },
  { id: 'nature_nature_earth', sequence: ['nature', 'nature', 'earth'], name: 'Gaia Desperta', bonus: 'regen', duration: 12, msg: 'O planeta cura você!' },
  { id: 'physical_physical_arcane', sequence: ['physical', 'physical', 'arcane'], name: 'Punho do Transcendente', bonus: 'damage', mult: 3.5, msg: 'Superando os limites humanos!' },
  { id: 'metal_metal_arcane', sequence: ['metal', 'metal', 'arcane'], name: 'Alquimia de Ouro', bonus: 'damage', mult: 3.0, msg: 'Transmutação bélica perfeita!' },
  { id: 'time_time_void', sequence: ['time', 'time', 'void'], name: 'Ponto de Inexistência', bonus: 'damage', mult: 4.0, msg: 'Onde o tempo e o espaço morrem!' },
  { id: 'music_music_time', sequence: ['music', 'music', 'time'], name: 'Réquiem sem Fim', bonus: 'paralyze', duration: 3, msg: 'Uma canção que prende o agora!' },
  { id: 'blood_blood_time', sequence: ['blood', 'blood', 'time'], name: 'Ciclo Vampírico', bonus: 'heal', mult: 3.5, msg: 'Eternidade através do sangue!' },
  { id: 'cosmos_cosmos_fire', sequence: ['cosmos', 'cosmos', 'fire'], name: 'Erupção Solar Mestra', bonus: 'damage', mult: 3.6, msg: 'O calor da estrela mais brilhante!' },
  { id: 'ice_ice_wind', sequence: ['ice', 'ice', 'wind'], name: 'Tundra Implacável', bonus: 'damage', mult: 2.5, msg: 'Vento que racha pedras pelo frio!' },
  { id: 'nature_nature_light', sequence: ['nature', 'nature', 'light'], name: 'Árvore do Mundo', bonus: 'shield', duration: 15, msg: 'A proteção mítica da Yggdrasil!' },
  { id: 'arcane_arcane_cosmos', sequence: ['arcane', 'arcane', 'cosmos'], name: 'Magia de Quasar', bonus: 'damage', mult: 4.5, msg: 'A energia mais densa do universo!' },
  { id: 'physical_physical_physical', sequence: ['physical', 'physical', 'physical'], name: 'Combo do Infinito', bonus: 'damage', mult: 4.2, msg: 'O limite da força bruta!' },
  { id: 'void_void_void', sequence: ['void', 'void', 'void'], name: 'O Nada Absoluto', bonus: 'paralyze', duration: 5, msg: 'Silêncio total.' },
];

export const MONSTER_REACTION_TRIGGERS = {
  elements: {
    fire: ['Que calor! Pare com isso!', 'Isso arde! 🔥', 'Vai me cozinhar?'],
    water: ['Estou ficando ensopado...', 'Onde está minha toalha?', 'Glub glub... para com a água!'],
    thunder: ['ZAP! Isso doeu!', 'Meus pelos estão arrepiados!', 'Ei! Cuidado com essa voltagem!'],
    void: ['Sinto... o nada...', 'Para onde foi minha sanidade?', 'Isso é... assustador.'],
  },
  statuses: {
    burn: ['Estou em chamas! Alguém me ajude!', 'Fogo! Fogo! 🔥'],
    poison: ['Sinto-me... enjoado...', 'O que tinha nessa poção? 🤢'],
    freeze: ['T-tão... f-frio...', 'Não consigo... me m-mexer...'],
  },
  hp: {
    lethal: ['Este é o meu fim...', 'Você... é forte demais...', 'Não me esqueça!'],
    half: ['Ainda não acabou!', 'Estou só começando!', 'Você luta bem...'],
  }
};
