// Dicionário de respostas rápidas de Anime/Mangá (Foco em Vocabulário Romaji)
export const GENERIC_FLAVOR_PROGRESSION: Record<string, string[]> = {
  'baka': [
    'Quem você está chamando de *baka*?! 💢',
    'Eu já disse que não sou *baka*! 😡',
    'Só sabe usar essa *kotoba*? 🙄',
    'Tá bom, eu sou um *baka*. Feliz?! 😭',
    'Se eu sou *baka*, você é o dobro! 😜',
    'Você não tem *sukui* mesmo! 😤',
    'B-baka! Não olhe com esses *me*! 😳',
    'Acha que sou *baka* de cair nessa?',
    'Quanta burrice para um *ningen* só! 🤦‍♂️',
    'Vá ler um *hon* antes da luta! 📚',
    'Seu *atama* é uma ervilha! 🧠',
    'Não confunda paciência com idiotice!',
    'Não sou *baka*, você que é *osoi*! 🐢',
    'Hmph! Baka, baka, baka! 😡',
    'Quem te ensinou esse *tatakai*? 🌾'
  ],
  'aho': [
    'Olhe para o seu *karada* antes de falar! 🙄',
    'Estúpido é o seu *kami*! 💇',
    'Pare, isso magoa o meu *kokoro*! 😢',
    'Vou te mostrar quem é o *aho*! 💥',
    'Você não pode ser tão burro. 🤦‍♀️',
    'Seu *shoubu* é ridículo! 🤡',
    'O vazio nos seus *me* reflete a mente. 🕳️',
    'Aho! Preste atenção na *buki*! ⚔️',
    'Tropeçou no próprio *ashi*?! 😂',
    'Você é uma piada andante! 🎪',
    'Não vou perder *jikan* com um *aho*. 😒',
    'Sua ignorância é um presente! 🎁',
    'Sabe ao menos segurar a *ken*? 🗡️',
    'Sua estupidez atinge o *sora*! 🚀'
  ],
  'shine': [
    'Vem tentar a sorte no *shoubu*! 🔪',
    'Cuidado com as suas *kotoba*! ⚠️',
    'Palavras fortes para um *yowai*! 💀',
    'Minha *inochi* não é sua! 🛡️',
    'Sua agressividade é adorável! 😈',
    'Desapareça deste *sekai*! 🌑',
    'Vou te reduzir a *hai*! 🔥',
    'Essas são suas últimas palavras?! 🗣️',
    'Encontre o seu *owari*! 🗡️',
    'Vá direto para o *jigoku*! 👹',
    'Seu *jikan* acabou, lixo! ⏳',
    'Quebre, desabe, *shine*! 💥',
    'Hoje é o seu dia do *shi*! ☠️',
    'Vou pulverizar o seu *karada*! 🌪️',
    'Despeça-se do *taiyou*! ☀️🚫'
  ],
  'kuso': [
    'Frustrado com o *tatakai*? 😈',
    'Sua linguagem é muito *kitanai*! 🧼',
    'Xingar não ganha o *shoubu*! 😂',
    'O meu *teki* está irritadinho! 🤭',
    'Droga! Meu *karada* falhou! 🤬',
    'Seu maldito *akuma*! 💢',
    'Kuso... subestimei sua *chikara*. 🩸',
    'Que lixo de *mahou* é essa?! 🗑️',
    'Não conte com a sorte! 🍀',
    'Vou esfregar sua cara na *tsuchi*! 🧹',
    'Maldita seja sua *kazoku*! 🩸',
    'Engula essas *kotoba*! 👊',
    'Kuso! Não perderei para um *ningen*! 😤',
    'Vou devolver essa *itami* em dobro! 🔄'
  ],
  'nani': [
    'Ouviu bem com os seus *mimi*! 🗣️',
    'Tem problemas de audição?! 👂',
    'Não vou repetir a *kotoba*! 🙅‍♂️',
    'Seja mais criativo! 🎤',
    'O que é essa *chikara*?! 📈',
    'Como desviou tão *hayai*?! 💨',
    'Nani?! Esse *shoubu* é impossível! 🤯',
    'De onde tirou tanto *pawaa*?! 💪',
    'Minha *mahou* falhou?! 📉',
    'O que saiu da sua *kuchi*?! 👂',
    'Que feitiçaria oculta é essa?! 🪄',
    'Nani?! Meus *ashi* congelaram! 🧊',
    'Um ataque surpresa com a *ken*?! 🗡️',
    'Você escondeu isso nas *kage*?! 🎭'
  ],
  'yamete': [
    'Eu nunca vou parar o *tatakai*! ⚔️',
    'Pedindo clemência tão cedo?! 😂',
    'Implore! É *ongaku* para mim! 🎵',
    'Não conheço a palavra parar! 🛑',
    'Por favor, eu desisto! 🏳️',
    'Yamete! Meus *hone* vão quebrar! 🦴',
    'Tire essas *te* imundas de mim! 🛑',
    'Pare com isso, seu *bakemono*! 👹',
    'Isso dói demais... pare! 😭',
    'Chega de usar *mahou*! 🚫',
    'Não aguento mais essa *itami*! 🩸',
    'Yamete! Te dou todo o meu *kane*! 💰',
    'Se não parar, meus *me* vão chorar! 😢',
    'Chega! O meu *jikan* esgotou! ⏳'
  ],
  'tasukete': [
    'Nenhum *nakama* virá salvar você! 🕸️',
    'Ninguém escuta a sua *koe*! 🪦',
    'A ajuda não está a caminho! 🙅',
    'Você lutará este *shoubu* sozinho! 🗡️',
    'Alguém me ajude! 🆘',
    'Socorro! Esse *teki* é louco! 😱',
    'Por que ninguém vem me salvar?! 😭',
    'Tasukete! Não quero encontrar o *shi*! ☠️',
    'Um *yuusha* já teria chegado! 🦸‍♂️',
    'Me tirem deste lugar *kurai*! 🏃‍♂️',
    'Tenha piedade do meu *kokoro*! 🙏',
    'Alguém ouviu a minha *koe*?! 📢',
    'Vou ser devorado! Tasukete! 🐉',
    'Por favor, *kami*, me salve! ⚡'
  ],
  'kawaii': [
    'N-Não me chame de fofo! 😳',
    'Sou um *bakemono* assustador! 👻',
    'Pare de me olhar com esses *me*! 🫣',
    'V-Você também é... Baka! 🙈',
    'Ataques tão *yowai*, que fofo! 🌸',
    'Acha que sua *buki* machuca? 🥰',
    'Carinha linda para ser esmagada! 😈',
    'Posso te manter de *petto*? 🐶',
    'O *karada* tremendo, que gracinha! 🥶',
    'Mesmo bravo, seu rosto é fofo! 🧸',
    'Limpe essas *namida* do rosto! 🥺',
    'Fofura não ganha *tatakai*! ⚔️',
    'Que *yoroi* adorável de bebê! 👶',
    'Acha minha *mahou* fofa?! Morra! 💥'
  ],
  'gomen': [
    'Tarde demais para perdão! 🗡️',
    'Desculpas não curam o *karada*! 🩸',
    'Pensei que fosse um *yuusha*! 🐔',
    'Aceito o *gomen* após te esmagar! 💀',
    'Gomen, mas sua *inochi* acaba! 🗡️',
    'Bati forte com a *ken*? Gomen! 🤭',
    'Sujo a *tsuchi* com seu sangue! 🩸',
    'Gomen nasai! Não quis dar *itami*! 😂',
    'Perdão se a minha *chikara* assusta! 🛡️',
    'Meus *mimi* não ouviram você! 🙉',
    'Desculpe por ser um *ou* superior! 👑',
    'Gomen, eu acertei o seu *kokoro*? 🎯',
    'Estava falando? Eu fui pra outro *sekai*. 😴',
    'Perdão pela sua humilhação! 🪦'
  ],
  'omae': [
    'Eu?! O que tem o meu *karada*?! 🤨',
    'Você não sabe do meu *kokoro*! 👤',
    'Não use esse tom de voz! 🗣️',
    'Petulância de um mero *ningen*... 👺',
    'Omae wa mou *shindeiru*. 💀',
    'Omae! Solte essa *buki* agora! 👆',
    'Não se intrometa no *tatakai*! 🚧',
    'Destruirei seu amado *sekai*! 🔥',
    'Não subestime o meu *ikari*! 😡',
    'Quem cruza o olhar com meus *me*?! 👀',
    'Você é o próximo *teki* da lista! 📜',
    'É você quem eu procurava! 🔍',
    'Omae, sua *inochi* acaba hoje! 🌩️',
    'Nunca vou perdoar você! 🙅‍♂️'
  ],
  'dorobou': [
    'Achado não é roubado! 🏃‍♂️💨',
    'Só peguei esse *takara* emprestado!',
    'Ladrão de corações, talvez? 😂',
    'Devolva as moedas de *kin*! 💎',
    'Roubou a minha *shouri*! 🏆',
    'Pague o roubo com seu *chi*! 💰',
    'Não roube a minha cena! 🎭',
    'Levante essas *te*, ladrão! 👐',
    'Fugindo com a minha *buki*? 🎒',
    'Ladrões não entram no meu *shiro*! 🏰',
    'Devolva o *jikan* que perdi! ⌛',
    'Roubou a *mahou* da pessoa errada! 🔮',
    'Pague a dívida com sua *inochi*! 🩸'
  ],
  'yowai': [
    'Sua *chikara* é a mais fraca! 💥',
    'Você blefa com essas *uso*! 🃏',
    'Sou *tsuyoi* para te esmagar! ⚔️',
    'Observe meu verdadeiro *pawaa*! 🌌',
    'Ataque *yowai* me dá sono! 🥱',
    'É só isso que tem de *chikara*? 🤏',
    'Técnica de *ken* patética. 🛡️',
    'Me dá tédio essa fragilidade. 💤',
    'Sua existência é muito *yowai*. 🥀',
    'Um *oni* bateria mais forte! 👺',
    'Seres fracos curvarão o *atama*! 👑',
    'Não sou babá de aventureiros! 🍼',
    'Não aguenta um soco no *karada*! 🤏',
    'O *kaze* te derrubaria! 🌬️'
  ],
  'konnichiwa': [
    'Sem *jikan* para cumprimentos! ⚔️',
    'Levante o *tate* e lute!',
    'Saudações para a sua *shi*! 💀',
    'Konnichiwa! Pronto pro *jigoku*? 👹',
    'Vim ceifar a sua *tamashii*! 🪦',
    'Belo dia sob o *taiyou* para morrer! ☀️',
    'Konnichiwa, lixo humano! 👋',
    'Vim destruir seus *nakama*! 🎉🚫',
    'Olá, meu *teki* número um! 🎯',
    'Saudações, vermes! 🐛',
    'A recepção para o seu *owari*! 🏰',
    'Konnichiwa... e sayounara! ⚔️',
    'Entrei sem bater, problema? 🚪💥'
  ],
  'arigatou': [
    'Não agradeça pelo seu *owari*! 💀',
    'Agradecendo a quem tira sua *inochi*?',
    'Agradeça lá no *jigoku*!',
    'Treino grátis para minha *ken*! 📈',
    'Trouxe o *takara* até mim! 🎒',
    'Você tem muita *tairyoku*, arigatou! 🥊',
    'Vou testar a *buki* em você! 🗡️',
    'Facilitou meu trabalho! 🧹',
    'Sua técnica é muito *osoi*! 😂',
    'Seu *chi* será útil! 💀',
    'Arigatou, seu *baka*! 🤪',
    'Gritos de *itami* são presentes! 🎁',
    'Agradeço do meu *kokoro* gelado! 🧊'
  ],
  'sayounara': [
    'Adeus, *yuusha* tolo! 👋',
    'Perderá a *inochi* agora!',
    'Até o próximo *sekai*! 🌒',
    'Não sentirei falta da sua *koe*! 👋',
    'Despedida final antes do *shi*. 🌘',
    'Descanse em pedaços, sayounara! 🧩',
    'Tchauzinho, seu *aho*! 🚀',
    'O *shoubu* foi péssimo. Adeus! 👎',
    'Nos vemos no *jigoku*! 🔥',
    'Adeus ao seu *karada* físico! ⏳',
    'Bye bye, guerreiro inútil! 🦸‍♂️🚫',
    'A *itami* passa rápido. Sayounara! 🩸',
    'Sua *kioku* acaba nesta página. 📖'
  ],
  'kakkoii': [
    'Minha *chikara* é estilosa! 😎',
    'Admirando seu carrasco?',
    'Elogios não vão te salvar! ✨',
    'Minha *ken* é muito kakkoii! ✨',
    'Luto melhor que seu *karada*! 🕺',
    'Minha *mahou* é bela e letal! 🌺🗡️',
    'Esplêndido demais no *tatakai*! 👑',
    'Olhe para os meus *me*! 🤩',
    'Lindo até cheio de *tsuchi*! 🌪️',
    'Muito *pawaa* e estilo! 🌟',
    'Admita que você é fã! 📸',
    'Aprenda com o mestre! 🕶️',
    'Sua *yoroi* saiu de moda! 👚👎'
  ],
  'sugoi': [
    'Assustado com minha *mahou*?! 🌠',
    'Não usei nem 10% da *chikara*!',
    'Olhe minha *ken* e morra! 🌪️',
    'Sugoi! Você durou um minuto! ⏱️',
    'Não vence esse *shoubu*! 🌌',
    'A sua velocidade me fez suar! 💧',
    'Ataque mais *yowai* que já vi! 🪄😂',
    'Seu *atama* é incrivelmente vazio! 🧠',
    'Formidável para um lixo! 🗑️',
    'Palmas para o meu *teki*! 👏',
    'Boa *buki*, mas inútil. 🛡️',
    'Determinação no *kokoro* é vã! 💪🚫',
    'Sua estátua de *kouri* será linda! 🧊'
  ],
  'yabai': [
    'Perigo real neste *tatakai*! ⚠️',
    'Trema os *ashi* de medo! 🥶',
    'Tarde para proteger a *inochi*! ☠️',
    'O *honoo* esquentou! 🔥',
    'O nível do *teki* é perigoso... 😬',
    'Se acertar o *karada*, acabou! 🎮🚫',
    'Fugir! Yabai! 🏃‍♂️',
    'Aura assassina e sem *uso*! 👿',
    'Quanta energia de *yami*?! 🩸',
    'Irritei o *bakemono* errado! 😅',
    'Minhas *kioku* passaram nos meus olhos! 👀',
    'Nós devemos correr agora? 💨',
    'Magia perigosa até para mim! ⚠️'
  ],
  'kimoi': [
    'Olha esse seu rosto! 🤮',
    'Como ousa usar essa *kotoba*?! 🤬',
    'Engula com a própria *kuchi*! 👊',
    'Longe do meu *karada*, nojo! 🤢',
    'Você empesteia todo o ar! 💨',
    'Não lava o seu *kami*?! 🛁',
    'Que *bakemono* repulsivo! 🐛',
    'Olhar seus *me* dá arrepio! 🥶',
    'Tire essas gosmas de mim! 🧪',
    'Definição de algo nojento! 🤮',
    'Sujou a ponta da minha *ken*! 🥾',
    'Tragam um balde de *mizu*! 🪣',
    'Afaste-se, inseto imundo! 🦠'
  ],
  'urusai': [
    'Minha *koe* ecoará mais alto! 📢',
    'Aaaaaaaaaaaaah! 🗣️',
    'Eu domino o som do *sekai*! 🌩️',
    'Cubra bem os *mimi*! 🙉',
    'Calem a boca, barulhentos! 🤫',
    'Fazem o meu *atama* doer! 🤕',
    'Urusai! Ninguém pediu opinião! 🤐',
    'Fale menos e encontre a *shi*! 🗣️🚫',
    'Menos *kotoba*, mais ação! ⚔️',
    'Vou silenciar a sua *kuchi*! 🗡️',
    'Chega de discursos vazios! 💬❌',
    'Urusai, urusai, URUSAI! 🤬',
    'Frases irritantes nos meus *mimi*! 🪰',
    'Cortarei a sua *shita*! 👅✂️'
  ],
  'damare': [
    'Obrigue a fechar a *kuchi*! 🤐',
    'Uso a minha *koe* como quiser! 🗣️',
    'Não manda no meu *karada*! 👑',
    'Palavras que não escuto! 🤪',
    'Silêncio na presença do *ou*! 👑',
    'Damare! Alguém *yowai* não fala! 🤐',
    'Cale-se e aceite a *shi*! 💀',
    'Sua voz é uma ofensa! 🙉',
    'Quieto enquanto quebro seus *hone*! 🔨',
    'Suas *uso* me irritam. Damare! 🛑',
    'Costurarei essa *kuchi* insolente! 🧵',
    'Quem permitiu essas *kotoba*?! 🗑️',
    'Calado e aceite o destino! 🐛',
    'Enterrado em silêncio absoluto. 🪦'
  ],
  'chotto': [
    'Sem pausas no *shoubu*! ⏱️',
    'Sem intervalos no *tatakai*! ⚔️',
    'De jeito nenhum!',
    'Segura a *ken*! Chotto! ✋',
    'Só mais um *jikan*, por favor! ⏳',
    'Deixa vestir a *yoroi*! 🛡️',
    'Chotto matte! Injusto! ⚖️',
    'Meu *karada* não estava pronto! 🔄',
    'Isso é trapaça mágica?! 💻',
    'Foi só um arranhão superficial! 🤕',
    'Cinco minutos de paz no *kokoro*! 🕊️',
    'Calma com a melhor *mahou*! 💥',
    'Deixa eu beber essa poção! 🧪'
  ],
  'matte': [
    'Monstros não vão esperar! 🏃‍♂️',
    'Sem chance nenhuma!',
    'Os seus *ashi* são lentos! ⏱️',
    'Matte! Não lance a magia! 🛑',
    'Conversamos com *kotoba* civis! 🗣️',
    'Eu te dou moedas de *kin*! 💰',
    'Piedade da minha *inochi*! 🙏',
    'A bota no *ashi* desamarrou! 🥾',
    'Não atire o *honoo* ainda! 🪄',
    'Tanta pressa para a *shi*?! ☠️',
    'Aguarde minha verdadeira forma! 🦋',
    'Meu *karada* tropeçou! 🤸‍♂️',
    'Espere a minha *ken* final! 🗡️'
  ],
  'hayaku': [
    'Vou destruir seu *karada*! 🌪️',
    'Pressa para perder a *inochi*? 💀',
    'Já estou indo!',
    'Seja *hayai*! Fico entediado! 🥱',
    'Hayaku! A poção vai esfriar! ☕',
    'Pernas de lesma velha! 🐌',
    'Ataque com a *buki*! ⚔️',
    'Acelere, o *jikan* voa! 🦅',
    'Não tenho o dia todo pro *owari*! ⏳',
    'Quero ver a sua *chikara*! 💫',
    'Lentidão para soltar a *mahou*! 🪄',
    'Meus *me* fecham de sono. 💤',
    'Encerre logo o sofrimento! 🩸'
  ],
  'nigero': [
    'Sem *michi* para fuga! 🚪🔒',
    'Use os *ashi* enquanto pode! 🦿',
    'A *yami* sempre te alcança! 🌑',
    'Fugir é ótima escolha! 🏳️',
    'Corra para as montanhas! ⛰️',
    'Sua *inochi* depende disso! 🏃‍♂️',
    'Nigero! Salve seu *karada*! 🆘',
    'Fuga desonrosa é a opção! 🚪',
    'Adoro caçar o meu *teki*! 🏹',
    'Fuja para a mamãe! 😭',
    'Nigero! Corra pro seu *mirai*! 🏳️',
    'Vire as costas e a *ken* ataca! 🗡️',
    'Corra e te mato no *shoubu*! 👹',
    'Rasteje longe do meu poder! 🐛'
  ],
  'kowai': [
    'Sinta terror na *tamashii*! 👻',
    'Pesadelos são especialidade!',
    'Chore muito em desespero! 😭',
    'O *kokoro* teme as trevas. 🌑',
    'Kowai? Prelúdio do horror. 👻',
    'O suor cheira a medo puro. 👃',
    'Vejo seus *ashi* tremendo. 🦵',
    'Cenário traz *namida* aos olhos. 😭',
    'A densa *kage* vai te devorar. 🌌',
    'Aparência de terror absoluto! 👺',
    'Sem *hikari* no meu domínio! 🔦❌',
    'Feche os *me*, é menos pior. 🙈',
    'Gritos são a minha *ongaku*. 🎶'
  ],
  'itai': [
    'Destruirá o seu *karada*! 🩸',
    'Ataque *yowai* superficial!',
    'Grite sob a dor! 😈',
    'A *ken* me machucou! 🤕',
    'A *tairyoku* foi pro ralo! 📉',
    'Queimou como o *honoo*! 🩸',
    'Lascou a unha das *te*! 💅',
    'Reviravolta sem plano! 📜',
    'Ofensa machuca mais que *itami*. 💔',
    'Joga sujo no *tatakai*! 🪨',
    'Vai sentir o mesmo impacto! 🔄',
    'A cicatriz dura a vida toda... 🩹',
    'Respeite o *karada* de um idoso! 👴'
  ],
  'kurushii': [
    'Sofra com minha *chikara*! 😈',
    'Agonia na ponta da espada! ☠️',
    'Aceite esse final excruciante!',
    'Os músculos do *karada* queimam! 🔥',
    'O ar não entra nos pulmões... 🫁',
    'Kurushii... a dor atravessa! 🩸',
    'Drenar a *inochi* é tortura. ⏳',
    'Toxina alcançou o meu *chi*! 🧪',
    'Todo passo dos *ashi* é tortura! ☠️',
    'Faça parar, kurushii! 😭',
    'Sofrimento de *zetsubou*... 🌌',
    'Empurrado no poço profundo! 🕳️',
    'Encerre a *inochi* com a espada. 🗡️'
  ],
  'sumimasen': [
    'Passagem fechada para *yowai*! 🛑',
    'Meu orgulho não aceita desculpas!',
    'Suplique apenas aos deuses!',
    'Meus *ashi* pisaram no corpo? 🥾',
    'A *ken* vai decepar você. ✂️',
    'Perdão pela intromissão! 💣',
    'Morra em total silêncio! 🤫',
    'A mira foi no ponto crítico. 🎯',
    'Esta *tsuchi* é minha. 🗺️',
    'A *shouri* já estava reservada. 🏆',
    'Não imaginei a *chikara* fraca. 🤏',
    'Desculpas pela surra na cara. 🥊',
    'O corpo obstrui meu *michi*. 🚪'
  ],
  'muda': [
    'MUDA MUDA! É fútil! 👊',
    'Nada perfura o *karada*! 🎯',
    'Esforço inútil dos músculos! 🥱',
    'WRYYYYYYYY! É tudo inútil! 🦇',
    'Não resista à minha *chikara*! 🛡️',
    'Essa *yoroi* é papel, MUDA! 📄',
    'Não vai derramar meu *chi*. ❌',
    'Golpes das *te* em vão. 🍂',
    'Desista do seu *mirai*. ⏳',
    'Sua *mahou* não me afeta! 🪄🚫',
    'Sua *ken* não me arranha! 👊',
    'Cansaço físico patético! 🥱',
    'Quantas vezes gritarei que é inútil?! 🗣️',
    'Seu sangue e sacrifício pro lixo! 🪦'
  ],
  'zako': [
    'Sou lenda entre guerreiros! 👑',
    'Seu *karada* vai pro lixo! 🗑️',
    'Recicle as *kotoba* rasas! ♻️',
    'Revés humilhante e *yowai*... 😖',
    'Saia logo do meu *michi*! 🗑️',
    'Um Zako não atrai meus *me*. 👀',
    'Volte pro *doukutsu* agora! 🕳️',
    'Abater você dá preguiça. 🥱',
    'Sobras dos guerreiros! 👺',
    'Um *kaze* te sopraria! 🌬️',
    'Não suje minha *ken* com sangue 1! 🗡️',
    'Piso no lixo antes do café. 🍳',
    'Derrota não dá xp pro sistema! 📉',
    'Desperdício de ar nos pulmões! 🫁🚫'
  ]
};

export const MONSTER_SPECIFIC_FLAVORS: Record<string, string[]> = {
  'Slime': [
    'Puru puru! Não sou mau!',
    'Tem nojo do meu *karada*?',
    'Posso me esticar todo!',
    'Composto de *mizu* e sonhos!',
    'Tire o *ashi* de cima!',
    'Nós temos um *kokoro*!',
    'Boing! Boing!',
    'Abraço pegajoso letal...',
    'Absorverei sua *yoroi* inteira!',
    'Bloop bloop!',
    'Jello mortal, sou eu!',
    'Meu corpo na *tsuchi* é macio!',
    'Sua *ken* me dividiu em dois!',
    '10% do meu corpo é *zetsubou*!',
    'Cortar gelatina é *muda*!',
    'Vou dissolver seus *hone*!',
    'Suco escorregadio no chão!',
    'Doce com gosto de ácido!',
    'Plop plop... rastejando!',
    'Vai sujar sua roupa limpa!',
    'Não sou um monstro *yowai*!',
    'A *mizu* derreterá você!',
    'Sendo *chiisai*, sou ameaça!',
    'Usar *buki* não adianta!',
    'Movimentos tão *osoi* na poça!',
    'Engolido pela minha *kuchi*!'
  ],
  'Morcego': [
    'Não bebo sangue, é *uso*! 🦇',
    'O radar noturno não erra!',
    'O brilho da *hikari* queima!',
    'Amarre-se de ponta cabeça.',
    'Flap flap flap!',
    'Sussurro na *yami* total.',
    'Meus *mimi* captam tudo.',
    'Ninho de asas no cabelo.',
    'Interrompeu o meu sono!',
    'O medo ganha fortes asas!',
    'Sugarei seu *chi* escarlate!',
    'A *yoru* me pertence!',
    'Guinchos sônicos nos ouvidos!',
    'Não foca os *me* no escuro!',
    'Ninho na sua mochila!',
    'Rasante no seu rosto!',
    'Calada da noite mortal!',
    'Profundezas deste *doukutsu*.',
    'Presas afiadas e velozes!',
    'Contaminação fatal da raiva!',
    'A *yoru* é hora da caça!',
    'Calor do seu *chi* jorrado!',
    'Posso *tobu* muito rápido!',
    'Asas *kuroi* como a desolação!',
    'Ouço seu *kokoro* batendo!',
    'Dentes cerrados e *surudoi*!'
  ],
  'Aranha': [
    'Oito pernas abraçam o *karada*...',
    'Fios superam lâmina de aço!',
    'Vibração da teia invisível.',
    'Um grande inseto apetitoso.',
    'Tick tick tick... correndo.',
    'Minha velocidade é *hayai*.',
    'Fios ocultos no solo.',
    'A espera é bem comprida.',
    'Farto banquete enrolado!',
    'Oito *me* fitam sua figura.',
    'Caiu no centro da *wana*.',
    'Picada e sono eterno.',
    'Paredes prendem sem saída.',
    'Seda apertando o corpo.',
    'Preservado para o jantar!',
    'Seu pavor me dá *chikara*!',
    'Cerdas causam puro arrepio.',
    'Ninguém escapa da fiandeira!',
    'Grossa *ito* asfixiará você!',
    'Uma *kumo* não perde a refeição.',
    'Invadiu a minha *ie* tecida!',
    'Conjunto de *ashi* velozes!',
    'Sua *chikara* não romperá!',
    'Corpo vazio e *karappo*!'
  ],
  'Sapo Mutante': [
    'Quer beijar o *bakemono*?',
    'A língua chicoteia o rosto!',
    'Águas lodosas do castelo.',
    'Felino comeu a *shita*!',
    'Pele cheia de veneno letal!',
    'Engulo armadura feito mosca!',
    'Pustulentas verrugas temíveis.',
    'Meus *ashi* caem em cima!',
    'Aroma enxofrento e podre?',
    'Pele derrete ferro da *yoroi*.',
    'Chuveirada de lodo ácido!',
    'Invadiu minhas dependências!',
    'Estalo da longa língua!',
    'Pulos errados geram morte.',
    'Macio lanche de fim de tarde.',
    'O mais mortal *kaeru* aqui!',
    'Pele *midori* mascara armadilhas!',
    'Cheio de *doku* na boca!',
    'Densa *ame* vai te afogar!',
    'Grudenta *shita* no pescoço!'
  ],
  'Rato Gigante': [
    'Odor de queijo nos bolsos?',
    'Maré inesgotável e solitário!',
    'Tubulações das regras sujas.',
    'Dentes furam placas de ferro!',
    'Peste e vírus comigo...',
    'Rasparei os tenros *hone*!',
    'Aliados das sombras no beco!',
    'Hora de espalhar praga!',
    'Tornozelos exalam cheiro bom.',
    'Furam paredes e macia carne!',
    'Superfície tornou vocês fracos.',
    'Surpresa horripilante nas trevas.',
    'Chiado nos cantos da mente.',
    'Corrupção eliminando a arrogância.',
    'Não pise na cauda comprida!',
    'Nós, *nezumi*, comandamos aqui!',
    'Ambiente *kurai* beneficia instintos!',
    'Roer couro dessas botas *kitanai*!',
    'O *nigate* de bravos aventureiros!',
    'Mordida na base do *kubi*!'
  ],
  'Besouro': [
    'Casca natural e invulnerável!',
    'Muralha movida a patas.',
    'Cortes falham na casca dura.',
    'Uso força bruta total.',
    'Divindades e você é poeira.',
    'Avanço frontal impecável e letal!',
    'Escudo frontal arremessa você!',
    'Impossível dobrar a proteção exterior!',
    'Bote fatal na escuridão.',
    'Rei de todos os insetos.',
    'Avanço de grande rinoceronte!',
    'Peso desta carapaça resistente.',
    'Limites superam fraca estrutura.',
    'Carícias na minha pesada quitina.',
    'Amasso você como lata descartada.',
    'Nenhum *mushi* supera a couraça!',
    'Escudo protetor intensamente *tsuyoi*!',
    'Bater de *hane* imita terror!',
    'Não machuca meu grandioso *tsuno*!',
    'A *tsuchi* pisoteada é seu túmulo!'
  ],
  'Tengu': [
    'Ventos seguem meu comando.',
    'Presunção igual minha altivez!',
    'Dobre joelhos ou caia no abismo.',
    'Fatiadas imitam o relâmpago.',
    'Abandone este território místico.',
    'Não alcança velocidade de voo?',
    'Ciclones divinos caem repentinamente!',
    'Imagens falsas furam o coração.',
    'Vigilante das eternas elevações!',
    'Golpes lentos perante o furacão.',
    'Inalcançável técnica de yokai!',
    'Lâminas servem de tablado grácil.',
    'Castigos ao cruzar reduto superior.',
    'Plumas rasgam honra falsa!',
    'Vastidão do céu é herança.',
    'A força do *kaze* da *yama*!',
    'Fina *ken* dilacera correntes!',
    'Longe de ser *hayai* como corvo!',
    'Libero ira através do *ikari*!',
    'Aves caem como *karasu*!'
  ],
  'Lobo Selvagem': [
    'Irmãos focados totalmente em você.',
    'Profundeza do olhar denuncia fúria.',
    'Lamentos da alcateia são fúnebres.',
    'Fome ignora fronteiras humanas.',
    'Odor de terror na sua pele.',
    'Banquete caminhando paras as mandíbulas.',
    'Músculos sucumbem aos inúmeros dentes!',
    'Bosques pintados do seu sangue.',
    'Uivos ao prateado reluzente da morte.',
    'Incisão das presas destroça traqueia!',
    'Virar as costas aciona instinto!',
    'Suor atiça nossa digestão.',
    'Patrulhas limpam vestígios inúteis.',
    'Monstro acorda cheirando o medo.',
    'Deslocamento pesado de presa lenta.',
    'Nós *ookami* coordenamos cercos perfeitamente!',
    'As pontiagudas *kiba* destroçarão músculos!',
    'O ecossistema desta *mori* nos acolhe!',
    'O bando *nakama* rastreia fugitivos!',
    'A face da *tsuki* despeja ira!'
  ],
  'Centopeia': [
    'Membros rastejantes oferecem esmagamento.',
    'Percurso flui em pensamentos.',
    'Maquinário afiado na bocarra.',
    'Perninhas incessantes correndo velozes.',
    'Patas peludas deformam o juízo.',
    'Pinça espalha veneno e paralisia!',
    'Agilidade escapa da visão humana.',
    'Faltam 99 patas cortantes ainda.',
    'Armadilha na rocha cinzenta.',
    'Sapateado de agulha reflete tormento.',
    'Abraço sufocante estrangula garganta.',
    'Inseticida não afeta tamanho titânico!',
    'Ardência introduz podridão contínua!',
    'A estrutura extingue seus passos.',
    'Recortes de pontudas *ashi* nervosas!',
    'Tente fatiar corpo *nagai* repulsivo!',
    'Repugnância gera puro *kimochi warui*!',
    'Rachadura no *jimen* aponta manobras!',
    'Apertarei todo o seu tenso *karada*!'
  ],
  'Raposa Demônio': [
    'Balanço de nove caudas mortais.',
    'Truques coloridos do delírio.',
    'Labaredas devoram a ambição.',
    'Impérios desabam como pó.',
    'Majestades exigem culto absoluto!',
    'Viagem a abismos de ilusões.',
    'Calor profano absorve aura fraca.',
    'Redemoinho ígneo destrutivo.',
    'Raciocínios caem como moscas presas.',
    'Tormento assombra em tempo real.',
    'Pergaminho oprime antigas certezas!',
    'Pelagem vermelha é só ilusão.',
    'Passos fantasmagóricos no cemitério.',
    'Gargalhar julga meros mortais.',
    'Elegância letal nos felpudos abanos.',
    'Faísca de *hi* exaure combustível vivo.',
    'Nove reluzentes *shippo* de feitiços!',
    'Cor de sangue pinta o seu *chi*!',
    'As fracas *kioku* sofrerão erosão!',
    'Um *ningen* tolo jogando com a eternidade.'
  ],
  'Goblin': [
    'Moedas de prêmios brilhando fortes!',
    'Aroma evoca aglomerado suculento enchendo!',
    'Parceiros feios cercando sua presença.',
    'Destruição trituradora da cabeça heroica!',
    'Entregue a localização de ouro?',
    'Lâmina enferrujada corta textura sedosa.',
    'Valentia atropela bípede inútil!',
    'Visual espanta olhos nojentos!',
    'Gargalhadas escandalosas da emboscada hilária!',
    'Solado reluzente tem gosto borrachudo.',
    'Botas chiques de aventureiro abatido!',
    'Tática arrasta pernas do invasor!',
    'Esvazie pratas ou perfuramos baixo-ventre!',
    'Dentes arrancam dolorosas tiras curtas!',
    'Armadilhas ocultas explodem sua burrice!',
    'Palhaço pateta no truque das costas!',
    'Fogo espalha cheirinho de banquete!',
    'Aventureiros fedorentos gritam carnes e moedas!',
    'Trevas amparam nativos nas brechas!',
    'Facada cirúrgica corta doces dinheiros!',
    'Transfira as montanhas de *kane* e *kin*!',
    'Cresci adorando ser totalmente *warui*!',
    'Lógica de unir em forte *mure*!',
    'Surrupiar toda a letalidade da *buki*!',
    'Rochas místicas do profundo *doukutsu*!'
  ],
  'Gato Fantasma': [
    'Miado sussurrado arrepia a coluna.',
    'Sou tragédia pairando e furtando.',
    'Patas garantem pousos pós quedas.',
    'Brinco com novelo de lã carmesim.',
    'Extensões peludas esmagam medos lúdicos.',
    'Lamento soturno estanca o sangue.',
    'Barricadas falham contra mim.',
    'Jogos felinos enlouquecem mentes completamente.',
    'Trevas engolem a caminhada ignorante.',
    'Curiosidade ceifa quem ousar invadir.',
    'Patas translúcidas colhem de fininho.',
    'Globos reflexivos cravam impressões últimas.',
    'Emanações nefastas queimam coragem fúnebre!',
    'Silêncio eterno embalando sono inerte.',
    'Um ser *yuurei* ri do seu *karada*!',
    'Clima macabro gelado e *samui* venerado.',
    'O olhar assustador de único *me*!',
    'A alta *koe* aterrorizante perpassa!',
    'Misteriosos traços dos seus *ashiato*!'
  ],
  'Esqueleto': [
    'Tétrico atrito ósseo fúnebre.',
    'Risada desprovida de pulmões!',
    'Ossos farão parte da legião.',
    'Fim mortalidade inicia alistamento eterno.',
    'Força macabra ignora feixes musculares.',
    'Calafrio seco corta a espinha.',
    'Restará apenas pó e ossada.',
    'Desprenda as falanges da haste!',
    'Fratura exposta como galho seco.',
    'Ranger macabro do crânio pálido.',
    'Ressentimentos antigos clamam acerto final!',
    'Perfurar o vazio com lâmina cega.',
    'Despedaçado levanto com ódio contínuo!',
    'Poeira dos séculos alimenta fúria.',
    'Ritmo cadenciado da marcha esquelética.',
    'Aperto fúnebre arranca derme inteira.',
    'Articulações frescas repletas de tutano.',
    'Tédio tumular encerrado na chacina.',
    'Aço gélido exalando morte fria.',
    'Costelas vazadas desviam pontas duplas.',
    'Meus *hone* secos quebram armas duras!',
    'Já estou *shindeiru*, como vai me parar?!',
    'Conheci o rosto do eterno *shi*.',
    'Você andará como um oco *gaikotsu*!',
    'Não tenho *kinniku* e bato forte!'
  ],
  'Espectro': [
    'Silêncio sepulcral deforma sanidade alheia.',
    'Vigor drenado sabe doce ambrosia.',
    'Funda derme na neblina cinzenta.',
    'Murmúrios tortos forjados da verdade.',
    'Abraço astral drena fagulha quente.',
    'Culpa oculta projeta sombras reais.',
    'Lâmina varre vácuo e fumaça.',
    'Coro lamentoso instiga queda brusca.',
    'Casca oca será meu receptáculo.',
    'Festim gélido jantando pulsações mortais.',
    'Grite alto, pânico nutre ocos.',
    'Feição vazia espelha sua morte.',
    'Companhia forçada nos corredores negros.',
    'Tecido material rompe perante ilusão.',
    'Uma *kage* que ri da lâmina!',
    'Sugarei vagarosamente a sua *tamashii*!',
    'Habito as entranhas da escura *yami*.',
    'Ataques não cortam quem não tem *katachi*!',
    'Seu pífio *inochi* escapará nas mãos!'
  ],
  'Minotauro': [
    'Saída bloqueada nos corredores sujos!',
    'Lâmina pesada dita fim esmagador.',
    'Cascos furiosos estremecem fundações rasas.',
    'Monstro bestial devorador de heróis!',
    'Fumaça quente jorra das narinas!',
    'Reféns perdidos nos becos tortos.',
    'Corte brutal parte couraças grossas.',
    'Chifres empaladores dilaceram derme macia.',
    'Paredes suadas lavadas de sangue.',
    'Passo em falso acarreta morte.',
    'Ira bestial anuncia matança desenfreada.',
    'Músculos tensos de pura pedreira.',
    'Linha de resgate rompida brutalmente.',
    'Adentre salão do açougue final!',
    'Pedaços carnudos servindo besta bovina!',
    'No escuro *meiro*, o *ushi* dita a lei!',
    'Avanço de patas absurdamente *tsuyoi*!',
    'A sólida *kabe* cederá junto com escudo!',
    'O pesado *ono* parte o tronco ao meio!',
    'Advinha? Você perdeu o *michi* da saída!'
  ],
  'Ogre': [
    'Roncando fome, esmagando petisco mole!',
    'Amassei latarias chatas de soldados.',
    'Ossos quebrados servem ótimo tempero.',
    'Cara feia, braço forte matador!',
    'Tora grossa racha cabeça mole!',
    'Fogueira assa carne heroica fresca.',
    'Picada fina dá apenas coceira!',
    'Bicho burro, mas braço esmaga!',
    'Palito dente feito de ossada.',
    'Bota gigante pisoteia barata aventureira.',
    'Correr não salva caça lenta!',
    'Almoço farto andando no prato.',
    'Grito alto estoura ouvidos fracos!',
    'Dentes podres mastigam aço frio.',
    'O grande *oni* lendas parou na frente!',
    'Não fuja, guerreiro pequeno, sou *ooki*!',
    'Aceite a sua derrota final, seu *baka*!',
    'Luto apenas porque tenho intensa *harahetta*!',
    'Esmago o frágil *atama* como abóbora!'
  ],
  'Harpia': [
    'Refrão mortal rasga garganta fina!',
    'Garras rasantes despencam céu turbulento.',
    'Forma bela, instinto assassino divino.',
    'Lufadas trazem ruína em penas.',
    'Furacão afiado corta rochas brutas.',
    'Rosto belo esconde sorriso rasgado.',
    'Melodia lúgubre anuncia fim próximo.',
    'Caçadoras cruéis dos picos altos.',
    'Queda livre rumo penhascos fundos!',
    'Chuva de aço em penas.',
    'Face divina, coração de águia.',
    'Grito supersônico estoura sistema nervoso!',
    'Abutres choram falta carniça fresca.',
    'Lançado frouxo nas nuvens rasgadas.',
    'O *tori* domina o alto do *sora*!',
    'Ouça atentamente enquanto me escuta *utau*!',
    'Minhas *tsume* não falham presa macia!',
    'Sinta a *arashi* das minhas asas!',
    'Grito agudo faz os *mimi* sangrarem!'
  ],
  'Serpente': [
    'Abraço anaconda aperta costelas duras.',
    'Veias fervem com néctar mortal.',
    'Sangue gelado bate devagar hoje.',
    'Maxilar deslocado engole peça inteira.',
    'Sssshh... chocalho avisa morte próxima.',
    'Corpo elástico quebra espinha dorsal.',
    'Íris fenda hipnotiza mentes tolas.',
    'Soro cura inútil contra peçonha.',
    'Grama camufla bote sorrateiro mortal.',
    'Esperança apodrece junto tecido mole.',
    'Grossa escama quebra fio metálico.',
    'Língua dupla prova medo cru.',
    'Flexão rápida imita bote relâmpago.',
    'Sucos gástricos dissolvem meses calmos.',
    'A *hebi* desliza aguardando o bote!',
    'Quando o *doku* circular, você trava!',
    'Corpo *nagai* asfixiará presa frágil!',
    'Rastejando silenciosa por entre a *kusa*.',
    'O *me* foca onde o coração bate!'
  ],
  'Golem de Pedra': [
    'IKITEIRU... KOUZOU... MEZAMETA.',
    'IWA WA... NIKU WO... TSUBUSU.',
    'OMAE WA... CHIISAI... NINGEN.',
    'EIEN NO... BANZIN... ME WO... AKERU.',
    'ITAMI WA... KOKO NI... NAI.',
    'MAHOU WA... ISHI NO... MUNE NI... MUDA.',
    'KOBUSHI... OCHIRU... SOSHITE... OWARI.',
    'KATAI... IWA... KATACHI WO... TSUKURU.',
    'MASUTAA NO... MEIREI... TEKI WO... HAKAI SURU.',
    'KEN WA... KABE NI... KUDAKERU.',
    'OMOSA... JURYOKU... HONE WO... TSUBUSU.',
    'YASUMI WA... KINSHI... EIEN NO... IWA.',
    'ARUKU... TABI NI... JISHIN GA... OKIRU.',
    'MORI WA... ORE NO... ASHIOTO KARA... NIGERU.',
    'ORE WA... INISHIE NO... ISHI.',
    'UGOKI WA... OMOI... SHIKASHI... TOMARANAI.',
    'ORE NO... BOUGYO WA... TOTEMO... KATAI.',
    'KEIKOKU... ORE WA... KIWAMETE... ABUNAI.',
    'MUGEN NO... CHIKARA... TSUCHI KARA... WAITEKURU.',
    'ISHI NO... GOOREMU WA... KESSHITE... TAORENAI.'
  ],
  'Mago Negro': [
    'Conhecimento arcano proibido nas mãos.',
    'Livrinho barato brincadeira criança fraca.',
    'Manto obscuro abafa gritos secos.',
    'Palavras mortas derretem mente sã.',
    'Círculo ritual exige sacrifícios de sangue!',
    'Fogo maldito engoliu mestre tolo.',
    'Fagulha divina afogada no vazio.',
    'Fórmula transforma ossada em pó!',
    'Falsos deuses tremem perante o poço.',
    'Vozes rasgadas sussurram fim agudo.',
    'Relâmpago podre vindo dos abismos!',
    'Mistura nefasta pede ingrediente novo.',
    'Luz nenhuma afasta selo antigo.',
    'Tecido realidade rasgado nas pontas!',
    'A *mahou* de magia *kuro* triunfa!',
    'Nada apaga o *honoo* das almas.',
    'Feitiços de *kouri* esfriam a espinha.',
    'Tolos acham que *hikari* traz esperança.',
    'Sua perdição escrita neste velho *hon*.'
  ],
  'Cavaleiro das Trevas': [
    'Placas forjadas em abismo profundo.',
    'Honra morta, vácuo absoluto resta.',
    'Fio profano bebe vitalidade rubra.',
    'Luz apagada pela capa pesada.',
    'Juramento quebrado, vazio abraçado eterno.',
    'Lâmina corrompida rasga alma nua!',
    'Código cavalaria apodreceu nos ossos.',
    'Sentença letal dada pelo decaído.',
    'Montaria fantasma pisoteia crentes cegos.',
    'Aço obscuro engole faíscas fracas.',
    'Mestre caótico empunhando chumbo denso!',
    'Frio cortante beija nuca suada.',
    'Tombado perante realeza das sombras.',
    'Corte fende luz em metades!',
    'A *ken* de um *kishi* não volta!',
    'A *yoroi* absorve qualquer pacto hostil!',
    'Abandone a claridade, *yami* te acompanha.',
    'Tente furar meu *tate* de ferro.',
    'A *inochi* descansa na minha lança!'
  ],
  'Kraken': [
    'Fossa abissal será túmulo afogado.',
    "Pressão d'água esmaga pulmões rasos.",
    'Madeira naufraga no abraço cego.',
    'Espuma manchada carmesim boiando rala.',
    'Galeões engolidos na bocarra escura.',
    'Trono salgado julga mortais secos.',
    'Falta ar no peito gelado!',
    'Cordas musculosas puxam abismo abaixo.',
    'Nuvem tinta cega olhos ardidos.',
    'Madeira partindo soa doce música!',
    'Monstro esquecido acorda furioso.',
    'Leviatãs servem de aperitivo leve.',
    'Arpão inútil contra couro borrachudo.',
    'Gravidade afoga esperança flutuante.',
    'Todo o *umi* segue minha vontade!',
    'Oculto na *mizu* turva aguardando.',
    'Meus tentáculos são *ooki* e letais.',
    'Ira destrói navios com grandes *nami*.',
    'Mastros do *fune* viraram palitos!'
  ],
  'Hidra': [
    'Corte inútil duplica praga rastejante!',
    'Miasma podre derrete narinas frágeis.',
    'Cem olhos focam preza trêmula.',
    'Carne podre volta ser forte!',
    'Sorrisos cheios dentes caindo múltiplos!',
    'Bafo chamas veneno ataque duplo!',
    'Corpo gigante esmaga formiga fraca.',
    'Corte todas pescoços num giro!',
    'Baba ácida fura chão duro.',
    'Gargantas apostam quem engole antes.',
    'Sangue ferve e derrama toxinas.',
    'Vida infinita criada no erro!',
    'Maxilares trincam ferro em farrapos!',
    'Mãe natureza criou anomalia perfeita!',
    'Corte uma *atama*, o dobro aparecerá!',
    'Forte para *kiru* tecidos que regeneram!',
    'Sufocado pelo nosso terrível *doku*!',
    'Somos *takusan* cabeças, uma vontade!',
    'A *kemuri* não oculta seu pavor!'
  ],
  'Dragão': [
    'Rugido fende rochas vulcânicas duras!',
    'Couraça prata derrete feito cera!',
    'Poeira inútil suja meus salões.',
    'Tesouros antigos desdenham moedas sujas.',
    'Diamante quebra contra minha escama!',
    'Ajoelhe perante realeza voando alto!',
    'Churrasco rápido armadura assa carne!',
    'Nuvens abrem alas para majestade.',
    'Sonhos cinzas voam no vento.',
    'Rugido gutural abala montanhas.',
    'Invasor minúsculo cheirando ouro roubado.',
    'Chamas fundem ossos ao solo.',
    'Milênios observando formigas brincarem guerra.',
    'Vendaval violento segue minhas asas.',
    'Escudo forte derrete nas beiradas.',
    'Realeza draconiana cega olhos tolos.',
    'Ouro empilhado amacia cama real.',
    'Vermes torram na panela fornalha.',
    'Soprando chamas na latinha fraca.',
    'Calamidade alada esconde sol nascente.',
    'Curve-se perante o *ryuu* supremo, *ou* dos céus!',
    'Fúria de meu *honoo* consome montanhas.',
    'Nuvens do *sora* fogem das *tsubasa*.',
    'O calor do *taiyou* é frio perto de mim!',
    'Todo este esplêndido *takara* me pertence.'
  ],
  'Lich': [
    'Carne apodrece, alma sofre eterno.',
    'Vidas mortais piscam e apagam.',
    'Runas sangue exigem preço alto.',
    'Domínio gélido acolhe pranto mudo.',
    'Morte física foi apenas começo.',
    'Estalo ósseo paralisa pulsações fracas.',
    'Carcaça servirá legião decaída.',
    'Lâmina enferruja contra magia ancestral.',
    'Toque nulo congela tempo curto.',
    'Grimórios levam séculos decifrando pó.',
    'Forma física rasga, eu retorno.',
    'Filactério bebe pranto salgado quente.',
    'Anos magia humana somam nada.',
    'Nevasca mágica congela coragem falsa.',
    'A marca *fushi* domina toda *mahou*.',
    'Da sua carcaça sobram *hone* carbonizados.',
    'Quando o *shi* chegar, sentirá pavor.',
    'O seu conhecimento das arcanas é *asai*.',
    'Você se tornará um obediente *dorei*.'
  ],
  'Rei Demônio': [
    'Trono aguarda sua queda heroica.',
    'Petulância rasteja no tapete rubro.',
    'Cortina trevas desce mundo fraco.',
    'Esperança quebra feito vidro fino.',
    'Luta rápida traz diversão fraca.',
    'Fagulhas magos somem na noite.',
    'Curve espinha antes coroa pesar.',
    'Pavor nutre poço sem fundo.',
    'Desafio medíocre morre no berço.',
    'Engolido sombras, alma apaga só.',
    'Erguer lâmina dita sentença final.',
    'Sacrifício vazio não muda lendas.',
    'Corpos estragados servem como adubo.',
    'Ossário real decorando meu salão.',
    'Purificado chamas poço inferno abissal.',
    'Servo demônio se ajoelhar raso.',
    'Suprema magia manchou capa limpa.',
    'Pior pesadelo encarnado na frente.',
    'Vocês lutam, eu sento rindo.',
    'Resistência rala engolida portão dor.',
    'Eu sou o *maou*, a *yami* dita as regras!',
    'Hoje marca o *owari* de suas lendas!',
    'Sinta o abismo da nossa *chikara*.',
    'Sua carne sentirá uma *itami* indescritível!',
    'Trevas trazem o *zetsubou* absoluto.'
  ],
  'Deus da Destruição': [
    'O ciclo da vida chegou ao seu fim.',
    'A minha *hakai* apaga este *sekai*.',
    'Tudo retornará ao *mu* absoluto.',
    'Eu sou o *kami* do fim de tudo!',
    'O apocalipse não pode ser evitado.',
    'As estrelas choram perante meu *ikari*.',
    'Este *hoshi* virará pó cósmico.',
    'O *mirai* da sua *kazoku* não existe.',
    'O julgamento divino caiu sobre você!',
    'A *tsuchi* sob seus *ashi* vai sumir!',
    'Ajoelhe-se diante do criador do fim.',
    'Eu apago a luz de todo *taiyou*.',
    'Não há *kibou* contra a minha *chikara*.',
    'O *jikan* parou de correr no universo!',
    'Curve-se, pois o seu *owari* chegou.',
    'Reduzirei tudo ao silêncio eterno.',
    'A criação inteira clama pela *shi*.',
    'Meu poder engole a própria existência!',
    'Você é apenas poeira voando na *yami*.',
    'Nenhuma *mahou* supera o deus supremo!'
  ]
};
// Generates an array from 0 to max so we can fallback
export function getGenericFlavor(word: string, usageCount: number): string | null {
  const list = GENERIC_FLAVOR_PROGRESSION[word];
  if (!list) return null;
  const index = Math.min(usageCount, list.length - 1);
  return list[index];
}

export function getMonsterFlavor(monsterName: string, interactionCount: number): string | null {
  const genericMonsterResponses = [
    'Grrr... Que som é esse que você faz?',
    'Acha que pode me confundir com palavras?',
    'Pare de tagarelar e lute!',
    'Você vai virar meu almoço logo, logo!',
    'Seu fim está próximo, herói de araque...',
    'Eu vou esmagar você e o seu livrinho mágico!'
  ];

  const list = MONSTER_SPECIFIC_FLAVORS[monsterName];
  if (!list) {
    const index = Math.min(interactionCount, genericMonsterResponses.length - 1);
    return genericMonsterResponses[index];
  }
  
  const index = Math.min(interactionCount, list.length - 1);
  return list[index];
}
