export function getMonsterVariation(baseName: string): { name: string; translation?: string } {
  const variations: Record<string, { name: string; translation?: string }[]> = {
        "Slime": [
      { name: "Slime, o grudento" },
      { name: "Jorge, o Slime" },
      { name: "Slime de Água Doce" },
      { name: "Pudim Mutante" },
      { name: "Slime Azedo" },
      { name: "Gota Colossal" },
      { name: "ベトベト (Betobeto)", translation: "O Pegajoso" },
      { name: "スライム太郎 (Slime Tarou)", translation: "Tarou, o Slime" },
      { name: "Slime Ancestral" },
      { name: "Geleia Amaldiçoada" }
    ],
    "Morcego": [
      { name: "Morcego da Noite Escura" },
      { name: "Vlad, o Morceguinho" },
      { name: "Morcego Míope" },
      { name: "Sugador de Tintas" },
      { name: "Aspirador Alado" },
      { name: "Morcego das Cavernas Uivantes" },
      { name: "ブラッドサッカー (Buraddosakkaa)", translation: "Sugador de Sangue" },
      { name: "夜の影 (Yoru no Kage)", translation: "Sombra da Noite" },
      { name: "Morcego Cego" },
      { name: "Asa da Perdição" }
    ],
    "Aranha": [
      { name: "Aranha Pernilonga" },
      { name: "Maria, a Aranha" },
      { name: "Tecedora de Pesadelos" },
      { name: "Aranha Saltadora" },
      { name: "Viúva Desolada" },
      { name: "Aranha Caçadora" },
      { name: "八本足 (Happon-ashi)", translation: "Oito Pernas" },
      { name: "毒蜘蛛 (Dokugumo)", translation: "Aranha Venenosa" },
      { name: "Aranha de Pelúcia Esquisita" },
      { name: "Senhora das Teias" }
    ],
    "Sapo Mutante": [
      { name: "Sapo Gosmento" },
      { name: "Cururu Tóxico" },
      { name: "Príncipe Amaldiçoado" },
      { name: "Sapo-Boi Gigante" },
      { name: "Rã Venenosa" },
      { name: "Sapo Caolho" },
      { name: "Sapo Hipnótico" },
      { name: "毒蛙 (Dokugaeru)", translation: "Sapo Venenoso" },
      { name: "Saltador Sombrio" },
      { name: "Sapo Bolha" }
    ],
    "Rato Gigante": [
      { name: "Rato de Esgoto" },
      { name: "Roedor de Ossos" },
      { name: "Ratazana Pestilenta" },
      { name: "Rei dos Ratos" },
      { name: "Rato Mutante" },
      { name: "Rato Caçador" },
      { name: "Rato de Porão" },
      { name: "巨大鼠 (Kyodai Nezumi)", translation: "Rato Gigante" },
      { name: "Rato Rabudo" },
      { name: "Pestinha Espalhadora" }
    ],
    "Besouro": [
      { name: "Besouro Rola-Bosta Gigante" },
      { name: "Escaravelho de Ouro" },
      { name: "Besouro Rinoceronte Feroz" },
      { name: "Cascudo Ameaçador" },
      { name: "Besouro Bombardeiro" },
      { name: "Chifrudo Implacável" },
      { name: "甲虫 (Kabutomushi)", translation: "Besouro de Armadura" },
      { name: "Inseto Colossal" },
      { name: "Besouro Metálico" },
      { name: "Quebra-Nozes Ambulante" }
    ],
    "Tengu": [
      { name: "Tengu do Nariz Longo" },
      { name: "Corvo Místico" },
      { name: "Guardião da Montanha" },
      { name: "Tengu Brincalhão" },
      { name: "Ventania Escarlate" },
      { name: "Tengu Ancião" },
      { name: "天狗 (Tengu)", translation: "Demônio Corvo" },
      { name: "Bico de Aço" },
      { name: "Mestre dos Ventos" },
      { name: "Tengu Caído" }
    ],
    "Lobo Selvagem": [
      { name: "Lobo Solitário" },
      { name: "Fenrir Filhote" },
      { name: "Presas de Prata" },
      { name: "Uivador da Lua Cheia" },
      { name: "Lobo Raivoso" },
      { name: "Caçador Noturno" },
      { name: "狼 (Ookami)", translation: "Lobo Divino" },
      { name: "Lobo das Neves" },
      { name: "Fera Feroz" },
      { name: "Cão do Mato Sombrio" }
    ],
    "Centopeia": [
      { name: "Centopeia Rastejante" },
      { name: "Mil Pernas Venenosas" },
      { name: "Verme Rastejante" },
      { name: "Lacraia Gigante" },
      { name: "Horror do Subterrâneo" },
      { name: "Centopeia Couraçada" },
      { name: "大百足 (Oomukade)", translation: "Centopeia Gigante" },
      { name: "Devoradora de Terra" },
      { name: "Abraço Venenoso" },
      { name: "Inseto Deslizante" }
    ],
    "Raposa Demônio": [
      { name: "Kitsune de Nove Caudas" },
      { name: "Raposa Enganadora" },
      { name: "Chama Azul" },
      { name: "Raposa Sorrateira" },
      { name: "Ilusionista Peluda" },
      { name: "Raposa da Meia-Noite" },
      { name: "妖狐 (Youko)", translation: "Raposa Espectral" },
      { name: "Sedutora Selvagem" },
      { name: "Brincalhona Mística" },
      { name: "Besta das Sombras" }
    ],
    "Goblin": [
      { name: "Goblin Risonho" },
      { name: "Bob, o Saqueador" },
      { name: "Goblin da Faca Cega" },
      { name: "Guarda-Costas Goblin" },
      { name: "Goblin Mesquinho" },
      { name: "Atirador Cego" },
      { name: "緑の悪魔 (Midori no Akuma)", translation: "Demônio Verde" },
      { name: "ゴブリン王 (Goburin-ou)", translation: "Rei Goblin" },
      { name: "Goblin Sedento" },
      { name: "Ladrão de Ouro" }
    ],
    "Gato Fantasma": [
      { name: "Gato Preto Azarento" },
      { name: "Bichano Translúcido" },
      { name: "Miado Sombrio" },
      { name: "Felino Assombroso" },
      { name: "Gato de Botas Rotas" },
      { name: "Ronronar Fantasmagórico" },
      { name: "化け猫 (Bakeneko)", translation: "Gato Monstro" },
      { name: "Caçador de Ratos Espectrais" },
      { name: "Patas Silenciosas" },
      { name: "Gato das Nove Vidas" }
    ],
    "Esqueleto": [
      { name: "Ossos Ruidosos" },
      { name: "Skelly, o Calvo" },
      { name: "Guerreiro de Cálcio" },
      { name: "Pilha de Ossos" },
      { name: "Esqueleto sem Mandíbula" },
      { name: "Guardião da Tumba" },
      { name: "骸骨 (Gaikotsu)", translation: "Caveira Animada" },
      { name: "死の騎士 (Shi no Kishi)", translation: "Cavaleiro da Morte" },
      { name: "Esqueleto Dançarino" },
      { name: "Sentinela de Marfim" }
    ],
    "Espectro": [
      { name: "Vulto Gélido" },
      { name: "Assombração Tímida" },
      { name: "Alma Perdida" },
      { name: "Aparição Sinistra" },
      { name: "Eco do Passado" },
      { name: "Espectro Choroso" },
      { name: "精霊 (Seirei)", translation: "Espírito Sombrio" },
      { name: "Sombra Errante" },
      { name: "Vingador Invisível" },
      { name: "Sopro da Morte" }
    ],
    "Fantasminha": [
      { name: "Casper, o Chato" },
      { name: "Fantasma do Lençol Furado" },
      { name: "Assombração Infantil" },
      { name: "Ectoplasma Pegajoso" },
      { name: "Poltergeist Brincalhão" },
      { name: "Alma Penada" },
      { name: "お化け (Obake)", translation: "Assombração" },
      { name: "Espírito Bagunceiro" },
      { name: "Visão Esfumaçada" },
      { name: "Chorão Invisível" }
    ],
    "Gárgula": [
      { name: "Estátua Viva" },
      { name: "Gárgula de Mármore" },
      { name: "Demônio de Pedra" },
      { name: "Vigia Noturno" },
      { name: "Asas de Granito" },
      { name: "Observador do Telhado" },
      { name: "ガーゴイル (Gaagoiru)", translation: "Sentinela de Pedra" },
      { name: "Monstro Petrificado" },
      { name: "Cuspidor de Água" },
      { name: "Defensor do Castelo" }
    ],
    "Zumbi": [
      { name: "Morto-Vivo Faminto" },
      { name: "Andarilho Lento" },
      { name: "Zumbi sem Braço" },
      { name: "Comedor de Cérebros" },
      { name: "Carniçal Fedorento" },
      { name: "Defunto Animado" },
      { name: "ゾンビ (Zonbi)", translation: "Cadáver Errante" },
      { name: "Putrefato" },
      { name: "Infectado Desajeitado" },
      { name: "Renascido das Trevas" }
    ],
    "Minotauro": [
      { name: "Touro Furioso" },
      { name: "Guardião do Labirinto" },
      { name: "Chifres de Sangue" },
      { name: "Fera Bípede" },
      { name: "Destruidor de Paredes" },
      { name: "Minotauro Cego de Raiva" },
      { name: "牛頭 (Gozu)", translation: "Cabeça de Touro" },
      { name: "Açougueiro Selvagem" },
      { name: "Esmagador de Crânios" },
      { name: "Besta Taurina" }
    ],
    "Ogre": [
      { name: "Ogro Guloso" },
      { name: "Gigante Feio" },
      { name: "Quebra-Ossos" },
      { name: "Ogro de Duas Cabeças" },
      { name: "Brutamontes Bestial" },
      { name: "Monstro Pantanoso" },
      { name: "鬼 (Oni)", translation: "Demônio de Chifres" },
      { name: "Comedor de Homens" },
      { name: "Titã Esverdeado" },
      { name: "Ogro Claviculário" }
    ],
    "Harpia": [
      { name: "Mulher-Pássaro" },
      { name: "Cantora da Morte" },
      { name: "Penas Cortantes" },
      { name: "Bruxa Alada" },
      { name: "Senhora dos Ventos" },
      { name: "Predadora dos Céus" },
      { name: "ハーピー (Haapii)", translation: "Demônio Alado" },
      { name: "Rasga-Céus" },
      { name: "Voo Rasante" },
      { name: "Caçadora Aérea" }
    ],
    "Serpente": [
      { name: "Cobra Rastejante" },
      { name: "Víbora Venenosa" },
      { name: "Abraço Mortal" },
      { name: "Serpente de Escamas Negras" },
      { name: "Cuspidora de Peçonha" },
      { name: "Naja Hipnótica" },
      { name: "大蛇 (Orochi)", translation: "Serpente Gigante" },
      { name: "Língua Bifurcada" },
      { name: "Asfixiadora Silenciosa" },
      { name: "Serpente Ancestral" }
    ],
    "Golem de Pedra": [
      { name: "Golem de Cascalho" },
      { name: "Montanha que Anda" },
      { name: "Sentinela de Argila" },
      { name: "Golem Inacabado" },
      { name: "Punhos de Granito" },
      { name: "Guardião de Ferro" },
      { name: "石の巨人 (Ishi no Kyojin)", translation: "Gigante de Pedra" },
      { name: "Monólito Errante" },
      { name: "Pilar de Runas" },
      { name: "Punhos da Terra" }
    ],
    "Golem de Gelo": [
      { name: "Estátua de Neve" },
      { name: "Sentinela Glacial" },
      { name: "Congelador de Almas" },
      { name: "Golem de Cristal" },
      { name: "Nevasca Ambulante" },
      { name: "Gigante de Frio" },
      { name: "氷の魔像 (Koori no Mazou)", translation: "Golem Gelado" },
      { name: "Estalactite Viva" },
      { name: "Punhos de Gelo" },
      { name: "Guardião do Inverno" }
    ],
    "Mago Negro": [
      { name: "Aprendiz de Trevas" },
      { name: "Mago que Erra" },
      { name: "Sombra do Grimório" },
      { name: "Bruxo Solitário" },
      { name: "Mago Rejeitado" },
      { name: "Senhor do Caos" },
      { name: "黒魔道士 (Kuromadoushi)", translation: "Mestre das Trevas" },
      { name: "Ocultista Sinistro" },
      { name: "Invocador Maldito" },
      { name: "Feiticeiro Profano" }
    ],
    "Golem de Fogo": [
      { name: "Fornalha Ambulante" },
      { name: "Gigante de Lava" },
      { name: "Queimador de Mundos" },
      { name: "Golem Incandescente" },
      { name: "Sentinela de Magma" },
      { name: "Brasa Viva" },
      { name: "炎の巨人 (Honoo no Kyojin)", translation: "Titã de Fogo" },
      { name: "Fúria Vulcânica" },
      { name: "Núcleo Ardente" },
      { name: "Estátua Flamejante" }
    ],
    "Cavaleiro Fantasma": [
      { name: "Armadura Vazia" },
      { name: "Cavaleiro Sem Cabeça" },
      { name: "Espírito Templário" },
      { name: "Lâmina Gélida" },
      { name: "Defensor Morto-Vivo" },
      { name: "Paladino Caído" },
      { name: "幽霊騎士 (Yuurei Kishi)", translation: "Cavaleiro Espectral" },
      { name: "Sentinela Fantasmagórica" },
      { name: "Eco de Batalha" },
      { name: "Alma de Ferro" }
    ],
    "Orc Guerreiro": [
      { name: "Orc Sangrento" },
      { name: "Líder da Horda" },
      { name: "Pele-Verde Feroz" },
      { name: "Machado Cego" },
      { name: "Orc Esmagador" },
      { name: "Berserker Selvagem" },
      { name: "豚鬼 (Butaoni)", translation: "Demônio Porco" },
      { name: "Matador de Elfos" },
      { name: "Campeão da Tribo" },
      { name: "Grito de Guerra Orc" }
    ],
    "Urso Feroz": [
      { name: "Urso-Coruja" },
      { name: "Patas de Chumbo" },
      { name: "Devorador de Mel" },
      { name: "Abraço de Urso" },
      { name: "Besta Parda" },
      { name: "Defensor da Floresta" },
      { name: "凶熊 (Kyouguma)", translation: "Urso Assassino" },
      { name: "Fúria Hibernal" },
      { name: "Monstro Felpudo" },
      { name: "Urso Primordial" }
    ],
    "Wyvern": [
      { name: "Dragão Falso" },
      { name: "Cuspidor de Veneno" },
      { name: "Asas de Morcego Escamoso" },
      { name: "Caçador das Montanhas" },
      { name: "Lagarto Alado" },
      { name: "Wyvern Rastejante" },
      { name: "飛竜 (Hiryuu)", translation: "Dragão Voador" },
      { name: "Terror dos Céus" },
      { name: "Predador Escamoso" },
      { name: "Serpente com Asas" }
    ],
    "Quimera": [
      { name: "Besta Misturada" },
      { name: "Leão-Cabra-Cobra" },
      { name: "Aberração Mágica" },
      { name: "Experimento Falho" },
      { name: "Mutante Selvagem" },
      { name: "Três Cabeças" },
      { name: "合成獣 (Gouseijuu)", translation: "Besta Sintética" },
      { name: "Fúria Polimórfica" },
      { name: "Terror da Alquimia" },
      { name: "Aberração de Sangue" }
    ],
    "Basilisco": [
      { name: "Rei das Cobras" },
      { name: "Olhar Petrificante" },
      { name: "Lagarto Venenoso" },
      { name: "Rastejador Mortal" },
      { name: "Escamas de Pedra" },
      { name: "Serpente de Fogo" },
      { name: "邪視のトカゲ (Jashi no Tokage)", translation: "Lagarto de Olho Maligno" },
      { name: "Transformador em Pedra" },
      { name: "Basilisco Ancestral" },
      { name: "Olhos da Morte" }
    ],
    "Behemoth": [
      { name: "Besta do Apocalipse" },
      { name: "Rei das Feras" },
      { name: "Pisada Terremoto" },
      { name: "Esmagador de Montanhas" },
      { name: "Chifres Colossais" },
      { name: "Monstro Inabalável" },
      { name: "巨獣 (Kyojuu)", translation: "Besta Gigante" },
      { name: "Tanque Vivo" },
      { name: "Força da Natureza" },
      { name: "Behemoth Furioso" }
    ],
    "Cavaleiro das Trevas": [
      { name: "Espada Negra" },
      { name: "Senhor dos Vampiros" },
      { name: "Terror Encouraçado" },
      { name: "Executor Sombrio" },
      { name: "Guardião do Abismo" },
      { name: "Lâmina Amaldiçoada" },
      { name: "暗黒騎士 (Ankoku Kishi)", translation: "Cavaleiro Sombrio" },
      { name: "Mestre do Medo" },
      { name: "Sem Piedade" },
      { name: "Tirano de Aço" }
    ],
    "Kraken": [
      { name: "Terror dos Mares" },
      { name: "Lula Gigante" },
      { name: "Devorador de Navios" },
      { name: "Tentáculos da Profundeza" },
      { name: "Monstro do Abismo" },
      { name: "Senhor das Marés" },
      { name: "海の悪魔 (Umi no Akuma)", translation: "Demônio do Mar" },
      { name: "Abraço Afogado" },
      { name: "Olho do Oceano" },
      { name: "Kraken Ancião" }
    ],
    "Hidra": [
      { name: "Besta de Várias Cabeças" },
      { name: "Cabeças Imortais" },
      { name: "Regeneradora de Veneno" },
      { name: "Pesadelo do Pântano" },
      { name: "Serpente Multiplicadora" },
      { name: "Hidra Cuspidora" },
      { name: "多頭蛇 (Tatouda)", translation: "Serpente de Muitas Cabeças" },
      { name: "Terror Tóxico" },
      { name: "Fúria Escamosa" },
      { name: "Hidra de Lerna" }
    ],
    "Dragão": [
      { name: "Lagarto que Cospe Fogo" },
      { name: "Dragão Preguiçoso" },
      { name: "Sombra das Nuvens" },
      { name: "Asa da destruição" },
      { name: "Terror dos Céus" },
      { name: "Dragão de Cobre" },
      { name: "竜 (Ryuu)", translation: "Dragão Rei" },
      { name: "Senhor das Chamas" },
      { name: "Wyrm Esmeralda" },
      { name: "Dragão de Ouro" }
    ],
    "Lich": [
      { name: "Rei dos Mortos" },
      { name: "Mago Esqueleto" },
      { name: "Senhor Necromante" },
      { name: "Alma Filactéria" },
      { name: "Bruxo Imortal" },
      { name: "Feiticeiro Decrépito" },
      { name: "不死の王 (Fushi no Ou)", translation: "Rei Imortal" },
      { name: "Mestre dos Zumbis" },
      { name: "Lich Ancião" },
      { name: "Guardião das Almas" }
    ],
    "Anjo Caído": [
      { name: "Asas Negras" },
      { name: "Querubim Corrompido" },
      { name: "Serafim Desterrado" },
      { name: "Luz Obscurecida" },
      { name: "Portador do Pecado" },
      { name: "Santo Caído" },
      { name: "堕天使 (Datenshi)", translation: "Anjo das Trevas" },
      { name: "Penas de Sangue" },
      { name: "Vingador Divino" },
      { name: "Anjo do Apocalipse" }
    ],
    "Dragão Ancião": [
      { name: "Avô dos Dragões" },
      { name: "Sábio Escamoso" },
      { name: "Guardião do Tempo" },
      { name: "Respiração Cósmica" },
      { name: "Asas de Galáxia" },
      { name: "Dragão Milenar" },
      { name: "古竜 (Koryuu)", translation: "Dragão Antigo" },
      { name: "Soberano dos Céus" },
      { name: "Protetor do Mundo" },
      { name: "Dragão Primordial" }
    ],
    "Ceifador": [
      { name: "A Morte em Pessoa" },
      { name: "Foice Sombria" },
      { name: "Colecionador de Almas" },
      { name: "Capuz Negro" },
      { name: "Senhor do Fim" },
      { name: "Sussurro Fúnebre" },
      { name: "死神 (Shinigami)", translation: "Deus da Morte" },
      { name: "Ceifador de Vidas" },
      { name: "Sombra Condenadora" },
      { name: "O Único Destino" }
    ],
    "Titã": [
      { name: "Colosso de Carne" },
      { name: "Esmagador de Deuses" },
      { name: "Titã Desperto" },
      { name: "Gigante Ancestral" },
      { name: "Passos de Terremoto" },
      { name: "Senhor da Terra" },
      { name: "巨人 (Kyojin)", translation: "Gigante Titânico" },
      { name: "Força Absoluta" },
      { name: "Monólito Vivo" },
      { name: "Conquistador de Mundos" }
    ],
    "Dragão do Vazio": [
      { name: "Devorador de Estrelas" },
      { name: "Buraco Negro Alado" },
      { name: "Entidade Cósmica" },
      { name: "Respiração de Antimatéria" },
      { name: "Dragão Nebuloso" },
      { name: "Ameaça Galáctica" },
      { name: "虚無竜 (Kyomuryuu)", translation: "Dragão do Nada" },
      { name: "Sombra do Espaço" },
      { name: "O Fim do Tempo" },
      { name: "Besta do Horizonte" }
    ],
    "Rei Demônio": [
      { name: "Soberano do Inferno" },
      { name: "Tirano Demoníaco" },
      { name: "Chifres da Ruína" },
      { name: "Liderança Profana" },
      { name: "Mestre do Caos" },
      { name: "Imperador das Trevas" },
      { name: "魔王 (Maou)", translation: "Rei dos Demônios" },
      { name: "Senhor da Destruição" },
      { name: "Mal Encarnado" },
      { name: "O Antagonista" }
    ],
    "Avatar do Caos": [
      { name: "Tempestade de Entropia" },
      { name: "Forma Indescritível" },
      { name: "Loucura Encarnada" },
      { name: "Distorção de Realidade" },
      { name: "Arauto da Confusão" },
      { name: "Olhos Mutáveis" },
      { name: "混沌の化身 (Konton no Keshin)", translation: "Encarnação do Caos" },
      { name: "Mestre da Desordem" },
      { name: "Anomalia Viva" },
      { name: "Paradoxo Ambulante" }
    ],
    "Serpente do Mundo": [
      { name: "Ouroboros Infinito" },
      { name: "Jörmungandr" },
      { name: "Abraço Global" },
      { name: "Serpente que Circunda a Terra" },
      { name: "Escamas Oceânicas" },
      { name: "Devoradora de Continentes" },
      { name: "世界蛇 (Sekai Hebi)", translation: "Cobra Mundial" },
      { name: "Fim dos Tempos" },
      { name: "Guardiã do Horizonte" },
      { name: "Serpente Eterna" }
    ],
    "Arauto da Perdição": [
      { name: "Mensageiro do Fim" },
      { name: "Cometa de Sangue" },
      { name: "Previsão Ruim" },
      { name: "Cavaleiro do Apocalipse" },
      { name: "Voz do Abismo" },
      { name: "Despertador de Males" },
      { name: "破滅の使者 (Hametsu no Shisha)", translation: "Emissário da Ruína" },
      { name: "Estrela Cadente Negra" },
      { name: "Sinal do Juízo" },
      { name: "Portador da Morte" }
    ],
    "Deus da Destruição": [
      { name: "O Fim de Tudo" },
      { name: "Destruidor de Galáxias" },
      { name: "Vazio Encarnado" },
      { name: "Aquele que não se nomeia" },
      { name: "Eternidade Sombria" },
      { name: "A Ruína" },
      { name: "破壊神 (Hakaishin)", translation: "Deus da Destruição" },
      { name: "絶対神 (Zettaishin)", translation: "Deus Absoluto" },
      { name: "Devorador de Mundos" },
      { name: "Apocalipse Vivo" }
    ]
  };

  const genericVariations = [
    { prefix: "", suffix: ", o Implacável" },
    { prefix: "Grande ", suffix: "" },
    { prefix: "", suffix: " Esfomeado" },
    { prefix: "Filhote de ", suffix: "" },
    { prefix: "Velho ", suffix: "" },
    { prefix: "", suffix: " de Sangue Mágico" },
    { prefix: "暗黒の (Ankoku no) ", suffix: "", translation: "Líder das Trevas {name}" },
    { prefix: "伝説の (Densetsu no) ", suffix: "", translation: "{name} Lendário" },
    { prefix: "", suffix: " Assustado" },
    { prefix: "Rei ", suffix: "" }
  ];

  if (variations[baseName]) {
    const list = variations[baseName];
    return list[Math.floor(Math.random() * list.length)];
  }

  // Fallback para outros monstros (10 combinações processadas)
  const genericList = genericVariations.map(gen => {
    let resultName = `${gen.prefix}${baseName}${gen.suffix}`;
    let resultTrans = gen.translation ? gen.translation.replace("{name}", baseName) : undefined;
    return { name: resultName, translation: resultTrans };
  });

  return genericList[Math.floor(Math.random() * genericList.length)];
}
