import { MonsterTemplate } from './types';

export const MONSTERS_LIST: MonsterTemplate[] = [
  { name: "Slime", romaji: "suraimu", kana: "すらいむ", kanji: "スライム", emoji: "💧", hp: 120, attack: 15, color: "text-blue-700", skills: ['weaken'], xpReward: 50 },
  { name: "Morcego", romaji: "koumori", kana: "こうもり", kanji: "蝙蝠", emoji: "🦇", hp: 150, attack: 18, color: "text-gray-700", skills: ['lifesteal'], xpReward: 60 },
  { name: "Aranha", romaji: "kumo", kana: "くも", kanji: "蜘蛛", emoji: "🕷️", hp: 180, attack: 20, color: "text-purple-700", skills: ['poison'], xpReward: 70 },
  { name: "Sapo Mutante", romaji: "kaeru", kana: "かえる", kanji: "蛙", emoji: "🐸", hp: 200, attack: 22, color: "text-green-700", skills: ['poison'], xpReward: 75 },
  { name: "Rato Gigante", romaji: "nezumi", kana: "ねずみ", kanji: "鼠", emoji: "🐀", hp: 250, attack: 25, color: "text-gray-800", skills: ['poison'], xpReward: 80 },
  { name: "Besouro", romaji: "kabutomushi", kana: "かぶとむし", kanji: "兜虫", emoji: "🪲", hp: 300, attack: 30, color: "text-yellow-700", skills: ['shield'], xpReward: 95 },
  { name: "Tengu", romaji: "tengu", kana: "てんぐ", kanji: "天狗", emoji: "👺", hp: 350, attack: 35, color: "text-red-700", skills: ['blind'], xpReward: 105 },
  { name: "Lobo Selvagem", romaji: "ookami", kana: "おおかみ", kanji: "狼", emoji: "🐺", hp: 450, attack: 40, color: "text-gray-600", skills: ['critical'], xpReward: 120 },
  { name: "Centopeia", romaji: "mukade", kana: "むかで", kanji: "百足", emoji: "🐛", hp: 500, attack: 45, color: "text-orange-700", skills: ['poison', 'weaken'], xpReward: 140 },
  { name: "Raposa Demônio", romaji: "youko", kana: "ようこ", kanji: "妖狐", emoji: "🦊", hp: 600, attack: 50, color: "text-yellow-600", skills: ['burn', 'blind'], xpReward: 160 },
  { name: "Goblin", romaji: "goburin", kana: "ごぶりん", kanji: "ゴブリン", emoji: "👹", hp: 700, attack: 60, color: "text-green-800", skills: ['poison', 'lifesteal'], xpReward: 200 },
  { name: "Gato Fantasma", romaji: "bakeneko", kana: "ばけねこ", kanji: "化け猫", emoji: "🐈‍⬛", hp: 850, attack: 70, color: "text-gray-900", skills: ['blind', 'critical'], xpReward: 250 },
  { name: "Esqueleto", romaji: "gaikotsu", kana: "がいこつ", kanji: "骸骨", emoji: "💀", hp: 1000, attack: 80, color: "text-gray-500", skills: ['shield'], xpReward: 300 },
  { name: "Espectro", romaji: "seirei", kana: "せいれい", kanji: "精霊", emoji: "🧚", hp: 1200, attack: 95, color: "text-blue-500", skills: ['weaken', 'heal'], xpReward: 380 },
  { name: "Fantasminha", romaji: "obake", kana: "おばけ", kanji: "お化け", emoji: "👻", hp: 1400, attack: 110, color: "text-purple-600", skills: ['blind', 'weaken'], xpReward: 450 },
  { name: "Gárgula", romaji: "gaagoiru", kana: "がーごいる", kanji: "ガーゴイル", emoji: "🗿", hp: 1600, attack: 130, color: "text-gray-600", skills: ['shield', 'critical'], xpReward: 520 },
  { name: "Zumbi", romaji: "zonbi", kana: "ぞんび", kanji: "ゾンビ", emoji: "🧟", hp: 1900, attack: 150, color: "text-green-800", skills: ['poison', 'lifesteal'], xpReward: 600 },
  { name: "Minotauro", romaji: "minotaurosu", kana: "みのたうろす", kanji: "ミノタウロス", emoji: "🐮", hp: 2200, attack: 175, color: "text-yellow-800", skills: ['critical', 'paralyze'], xpReward: 700 },
  { name: "Ogre", romaji: "oni", kana: "おに", kanji: "鬼", emoji: "👹", hp: 2500, attack: 200, color: "text-red-700", skills: ['critical', 'shield'], xpReward: 800 },
  { name: "Harpia", romaji: "haapii", kana: "はーぴー", kanji: "ハーピー", emoji: "🦅", hp: 2800, attack: 220, color: "text-blue-600", skills: ['blind', 'bleed'], xpReward: 950 },
  { name: "Serpente", romaji: "hebi", kana: "へび", kanji: "蛇", emoji: "🐍", hp: 3100, attack: 240, color: "text-green-700", skills: ['poison', 'weaken'], xpReward: 1050 },
  { name: "Golem de Pedra", romaji: "gooremu", kana: "ごーれむ", kanji: "ゴーレム", emoji: "🪨", hp: 3500, attack: 260, color: "text-gray-700", skills: ['shield', 'paralyze'], xpReward: 1200 },
  { name: "Golem de Gelo", romaji: "koori no gooremu", kana: "こおりのごーれむ", kanji: "氷のゴーレム", emoji: "🧊", hp: 4000, attack: 300, color: "text-blue-600", skills: ['shield'], xpReward: 1400 },
  { name: "Mago Negro", romaji: "kuromadou", kana: "くろまどう", kanji: "黒魔道", emoji: "🧙‍♂️", hp: 5500, attack: 350, color: "text-purple-700", skills: ['burn', 'blind', 'heal'], xpReward: 1800 },
  { name: "Golem de Fogo", romaji: "honoo no gooremu", kana: "ほのおのごーれむ", kanji: "炎のゴーレム", emoji: "🔥", hp: 6500, attack: 400, color: "text-red-800", skills: ['burn', 'critical'], xpReward: 2100 },
  { name: "Cavaleiro Fantasma", romaji: "yuurei kishi", kana: "ゆうれいきし", kanji: "幽霊騎士", emoji: "👻", hp: 7200, attack: 420, color: "text-gray-600", skills: ['lifesteal', 'weaken'], xpReward: 2300 },
  { name: "Orc Guerreiro", romaji: "ooku", kana: "おーく", kanji: "オーク", emoji: "🧌", hp: 8000, attack: 450, color: "text-green-900", skills: ['critical', 'summon'], xpReward: 2500 },
  { name: "Urso Feroz", romaji: "kuma", kana: "くま", kanji: "熊", emoji: "🐻", hp: 9500, attack: 550, color: "text-yellow-900", skills: ['critical', 'paralyze'], xpReward: 2900 },
  { name: "Wyvern", romaji: "waibaan", kana: "わいばーん", kanji: "ワイバーン", emoji: "🐉", hp: 10500, attack: 600, color: "text-green-600", skills: ['poison', 'bleed'], xpReward: 3200 },
  { name: "Quimera", romaji: "kimera", kana: "きめら", kanji: "キメラ", emoji: "🦁", hp: 12000, attack: 650, color: "text-yellow-700", skills: ['burn', 'poison', 'paralyze'], xpReward: 3500 },
  { name: "Basilisco", romaji: "bashirisuku", kana: "ばしりすく", kanji: "バジリスク", emoji: "🦎", hp: 14000, attack: 750, color: "text-green-800", skills: ['poison', 'weaken'], xpReward: 4200 },
  { name: "Behemoth", romaji: "behemosu", kana: "べへもす", kanji: "ベヒーモス", emoji: "🦏", hp: 16000, attack: 850, color: "text-gray-800", skills: ['critical', 'shield'], xpReward: 4600 },
  { name: "Cavaleiro das Trevas", romaji: "ankokukishi", kana: "あんこくきし", kanji: "暗黒騎士", emoji: "🤺", hp: 18000, attack: 900, color: "text-gray-900", skills: ['lifesteal', 'shield', 'blind'], xpReward: 5000, isBoss: true },
  { name: "Kraken", romaji: "kuraaken", kana: "くらーけん", kanji: "クラーケン", emoji: "🦑", hp: 21000, attack: 1050, color: "text-blue-800", skills: ['paralyze', 'blind'], xpReward: 6000 },
  { name: "Hidra", romaji: "hidora", kana: "ひどら", kanji: "ヒドラ", emoji: "🐉", hp: 25000, attack: 1150, color: "text-green-900", skills: ['poison', 'heal', 'summon'], xpReward: 7000, isBoss: true },
  { name: "Dragão", romaji: "ryuu", kana: "りゅう", kanji: "竜", emoji: "🐲", hp: 30000, attack: 1300, color: "text-red-700", skills: ['burn', 'critical', 'summon'], xpReward: 8000 },
  { name: "Lich", romaji: "ritchi", kana: "りっち", kanji: "リッチ", emoji: "🧟‍♂️", hp: 35000, attack: 1500, color: "text-purple-800", skills: ['lifesteal', 'weaken', 'blind'], xpReward: 10000, isBoss: true },
  { name: "Anjo Caído", romaji: "datenshi", kana: "だてんし", kanji: "堕天使", emoji: "🪽", hp: 42000, attack: 1750, color: "text-gray-600", skills: ['shield', 'heal', 'critical'], xpReward: 12000 },
  { name: "Dragão Ancião", romaji: "koryuu", kana: "こりゅう", kanji: "古竜", emoji: "🦖", hp: 50000, attack: 2000, color: "text-green-900", skills: ['burn', 'paralyze', 'heal', 'summon'], xpReward: 15000, isBoss: true },
  { name: "Ceifador", romaji: "shinigami", kana: "しにがみ", kanji: "死神", emoji: "💀", hp: 60000, attack: 2200, color: "text-gray-900", skills: ['lifesteal', 'blind', 'critical'], xpReward: 18000 },
  { name: "Titã", romaji: "kyojin", kana: "きょじん", kanji: "巨人", emoji: "🏔️", hp: 80000, attack: 2600, color: "text-yellow-800", skills: ['shield', 'paralyze'], xpReward: 22000 },
  { name: "Dragão do Vazio", romaji: "kyomuryuu", kana: "きょむりゅう", kanji: "虚無竜", emoji: "🌌", hp: 110000, attack: 3000, color: "text-indigo-900", skills: ['blind', 'weaken', 'summon'], xpReward: 26000, isBoss: true },
  { name: "Rei Demônio", romaji: "maou", kana: "まおう", kanji: "魔王", emoji: "👾", hp: 150000, attack: 3500, color: "text-purple-900", skills: ['blind', 'lifesteal', 'summon', 'heal', 'critical'], xpReward: 30000, isBoss: true },
  { name: "Avatar do Caos", romaji: "konton no keshin", kana: "こんとんのけしん", kanji: "混沌の化身", emoji: "🌪️", hp: 200000, attack: 4500, color: "text-gray-800", skills: ['paralyze', 'blind', 'weaken'], xpReward: 40000, isBoss: true },
  { name: "Serpente do Mundo", romaji: "sekai hebi", kana: "せかいへび", kanji: "世界蛇", emoji: "🐍", hp: 280000, attack: 5800, color: "text-green-950", skills: ['poison', 'shield', 'heal'], xpReward: 55000, isBoss: true },
  { name: "Arauto da Perdição", romaji: "hametsu no shisha", kana: "はめつのししゃ", kanji: "破滅の使者", emoji: "☄️", hp: 380000, attack: 7000, color: "text-red-900", skills: ['burn', 'critical', 'summon'], xpReward: 75000, isBoss: true },
  { name: "Deus da Destruição", romaji: "hakaishin", kana: "はかいしん", kanji: "破壊神", emoji: "🌌", hp: 500000, attack: 8000, color: "text-white text-shadow-md", skills: ['blind', 'paralyze', 'burn', 'critical', 'lifesteal'], xpReward: 99999, isBoss: true },
  { name: "Pégaso", romaji: "pegasasu", kana: "ぺがさす", kanji: "天馬", emoji: "🦄", hp: 1700, attack: 140, color: "text-blue-400", skills: ['light_ray', 'holy_light'], xpReward: 550 },
  { name: "Sereia", romaji: "ningyo", kana: "にんぎょ", kanji: "人魚", emoji: "🧜‍♀️", hp: 2000, attack: 160, color: "text-blue-500", skills: ['silence_song', 'tsunami'], xpReward: 650 },
  { name: "Ent", romaji: "ento", kana: "えんと", kanji: "樹人", emoji: "🌳", hp: 3200, attack: 210, color: "text-green-800", skills: ['earth_wall', 'toxic_spores'], xpReward: 1000 },
  { name: "Vampiro", romaji: "kyuuketsuki", kana: "きゅうけつき", kanji: "吸血鬼", emoji: "🧛", hp: 3800, attack: 280, color: "text-red-900", skills: ['vampiric_bite', 'blood_rain'], xpReward: 1300 },
  { name: "Wendigo", romaji: "wendigo", kana: "うぇんでぃご", kanji: "悪霊", emoji: "🦌", hp: 4200, attack: 320, color: "text-gray-400", skills: ['frostbite', 'roar'], xpReward: 1500 },
  { name: "Esfinge", romaji: "sufinkusu", kana: "すふぃんくす", kanji: "獅子身", emoji: "🦁", hp: 4800, attack: 340, color: "text-yellow-600", skills: ['mind_control', 'illusion'], xpReward: 1650 },
  { name: "Cérbero", romaji: "keruberosu", kana: "けるべろす", kanji: "三頭犬", emoji: "🐕", hp: 6000, attack: 380, color: "text-red-800", skills: ['inferno', 'bite', 'roar'], xpReward: 2000 },
  { name: "Gênio", romaji: "majin", kana: "まじん", kanji: "魔神", emoji: "🧞", hp: 6800, attack: 410, color: "text-indigo-600", skills: ['mirror_image', 'time_stop'], xpReward: 2200, isBoss: true },
  { name: "Múmia", romaji: "miira", kana: "みいら", kanji: "木乃伊", emoji: "🧟", hp: 7500, attack: 430, color: "text-yellow-800", skills: ['curse', 'toxic_spores'], xpReward: 2400 },
  { name: "Súcubo", romaji: "sakubasu", kana: "さきゅばす", kanji: "夢魔", emoji: "🦇", hp: 8200, attack: 480, color: "text-pink-700", skills: ['mind_control', 'nightmare'], xpReward: 2600 },
  { name: "Banshee", romaji: "banshii", kana: "ばんしー", kanji: "精霊", emoji: "👻", hp: 9000, attack: 520, color: "text-gray-500", skills: ['sonic_boom', 'silence_song'], xpReward: 2800 },
  { name: "Dullahan", romaji: "durahan", kana: "でゅらはん", kanji: "首無騎士", emoji: "🏇", hp: 10000, attack: 580, color: "text-blue-900", skills: ['death_scythe', 'shadow_strike'], xpReward: 3000 },
  { name: "Manticora", romaji: "mantikoa", kana: "まんてぃこあ", kanji: "魔獣", emoji: "🦁", hp: 11000, attack: 620, color: "text-orange-900", skills: ['venom_stinger', 'roar'], xpReward: 3300 },
  { name: "Cíclope", romaji: "saikuropusu", kana: "さいくろぷす", kanji: "単眼巨人", emoji: "👁️", hp: 13000, attack: 700, color: "text-gray-800", skills: ['heavy_strike', 'quake'], xpReward: 3800 },
  { name: "Leviatã", romaji: "rivaiasan", kana: "りう゛ぁいあさん", kanji: "海神", emoji: "🐋", hp: 15000, attack: 800, color: "text-blue-800", skills: ['tsunami', 'freeze'], xpReward: 4400, isBoss: true },
  { name: "Phoenix", romaji: "fushichou", kana: "ふしちょう", kanji: "不死鳥", emoji: "🦅", hp: 17000, attack: 880, color: "text-red-600", skills: ['inferno', 'solar_flare', 'heal'], xpReward: 4800 },
  { name: "Slime Real", romaji: "kingu suraimu", kana: "きんぐすらいむ", kanji: "王スライム", emoji: "👑", hp: 19000, attack: 950, color: "text-yellow-500", skills: ['acid_spit', 'summon'], xpReward: 5200 },
  { name: "Vorme da Areia", romaji: "sando waamu", kana: "さんどうぁーむ", kanji: "砂虫", emoji: "🐛", hp: 22000, attack: 1100, color: "text-yellow-900", skills: ['quake', 'blind'], xpReward: 6500 },
  { name: "Valquíria", romaji: "warukyuure", kana: "わるきゅーれ", kanji: "戦乙女", emoji: "🤺", hp: 24000, attack: 1200, color: "text-yellow-400", skills: ['divine_shield', 'light_ray'], xpReward: 6800 },
  { name: "Samurai das Sombras", romaji: "kage musha", kana: "かげむしゃ", kanji: "影武者", emoji: "🗡️", hp: 27000, attack: 1250, color: "text-gray-900", skills: ['shadow_strike', 'mirror_image'], xpReward: 7500 },
  { name: "Senhor dos Vampiros", romaji: "vanpaia roodo", kana: "ゔぁんぱいあろーど", kanji: "吸血鬼の王", emoji: "🧛‍♂️", hp: 32000, attack: 1400, color: "text-red-950", skills: ['blood_rain', 'bat_swarm', 'mind_control'], xpReward: 9000, isBoss: true },
  { name: "Senhor dos Dragões", romaji: "ryuuou", kana: "りゅうおう", kanji: "竜王", emoji: "🐉", hp: 38000, attack: 1600, color: "text-red-800", skills: ['meteor', 'roar', 'inferno'], xpReward: 11000 },
  { name: "Guardião Celestial", romaji: "ten no shugosha", kana: "てんのしゅごしゃ", kanji: "天の守護者", emoji: "👼", hp: 45000, attack: 1850, color: "text-yellow-600", skills: ['holy_light', 'divine_shield', 'time_stop'], xpReward: 13000 },
  { name: "Espírito da Natureza", romaji: "shizen no seirei", kana: "しぜんのせいれい", kanji: "自然の精霊", emoji: "🌱", hp: 55000, attack: 2100, color: "text-green-600", skills: ['earth_wall', 'tornado', 'heal'], xpReward: 16000 },
  { name: "Leviatã do Vazio", romaji: "kyomu no rivaiasan", kana: "きょむのりう゛ぁいあさん", kanji: "虚無海神", emoji: "🌌", hp: 70000, attack: 2400, color: "text-indigo-800", skills: ['void_gaze', 'tsunami', 'dark_matter'], xpReward: 20000, isBoss: true },
  { name: "Anomalia Espacial", romaji: "jikuu no hizumi", kana: "じくうのひずみ", kanji: "時空の歪み", emoji: "🌀", hp: 95000, attack: 2800, color: "text-purple-600", skills: ['time_stop', 'meteor', 'black_hole'], xpReward: 24000 },
  { name: "Colosso de Metal", romaji: "hagane no kyojin", kana: "はがねのきょじん", kanji: "鋼鉄の巨人", emoji: "🤖", hp: 120000, attack: 3200, color: "text-gray-400", skills: ['laser_beam', 'heavy_strike', 'shield'], xpReward: 28000, isBoss: true },
  { name: "Serpente Galáctica", romaji: "ginga hebi", kana: "ぎんがへび", kanji: "銀河蛇", emoji: "☄️", hp: 180000, attack: 4000, color: "text-blue-900", skills: ['dark_matter', 'solar_flare', 'lunar_eclipse'], xpReward: 35000 },
  { name: "Arauto do Vazio", romaji: "kyomu no shisha", kana: "きょむのししゃ", kanji: "虚無の使者", emoji: "🌑", hp: 250000, attack: 5200, color: "text-purple-950", skills: ['void_gaze', 'soul_drain', 'time_stop'], xpReward: 50000, isBoss: true },
  { name: "Manifestação do Medo", romaji: "kyoufu no keshin", kana: "きょうふのけしん", kanji: "恐怖の化身", emoji: "👁️", hp: 320000, attack: 6500, color: "text-black", skills: ['mind_control', 'nightmare', 'illusion', 'roar'], xpReward: 65000, isBoss: true },
  { name: "Criador Cósmico", romaji: "uchuu no souzoushu", kana: "うちゅうのそうぞうしゅ", kanji: "宇宙の創造主", emoji: "✨", hp: 450000, attack: 7500, color: "text-indigo-300", skills: ['meteor', 'divine_shield', 'holy_light', 'time_stop', 'dark_matter'], xpReward: 85000, isBoss: true },
];
