import { MonsterTemplate } from './types';

export const MONSTERS_LIST: MonsterTemplate[] = [
  { name: "Slime", romaji: "suraimu", kana: "すらいむ", kanji: "スライム", emoji: "💧", hp: 120, attack: 15, color: "text-blue-700", skills: ['weaken'], xpReward: 50 },
  { name: "Morcego", romaji: "koumori", kana: "こうもり", kanji: "蝙蝠", emoji: "🦇", hp: 150, attack: 18, color: "text-gray-700", skills: ['lifesteal'], xpReward: 60 },
  { name: "Aranha", romaji: "kumo", kana: "くも", kanji: "蜘蛛", emoji: "🕷️", hp: 180, attack: 20, color: "text-purple-700", skills: ['poison'], xpReward: 70 },
  { name: "Sapo Mutante", romaji: "kaeru", kana: "かえる", kanji: "蛙", emoji: "🐸", hp: 200, attack: 22, color: "text-green-700", skills: ['poison'], xpReward: 75 },
  { name: "Rato Gigante", romaji: "nezumi", kana: "ねずみ", kanji: "鼠", emoji: "🐀", hp: 250, attack: 25, color: "text-gray-800", skills: ['poison'], xpReward: 80 },
  { name: "Besouro", romaji: "kabutomushi", kana: "かぶとむし", kanji: "兜虫", emoji: "🪲", hp: 300, attack: 30, color: "text-yellow-700", skills: ['shield'], xpReward: 95 },
  { name: "Tengu", romaji: "tengu", kana: "てんぐ", kanji: "天狗", emoji: "👺", hp: 350, attack: 35, color: "text-red-700", skills: ['blind'], xpReward: 105 },
  { name: "Lobo Selvagem", romaji: "ookami", kana: "おおかみ", kanji: "狼", emoji: "🐺", hp: 450, attack: 40, color: "text-gray-600", skills: ['critical'], xpReward: 120 },
  { name: "Centopeia", romaji: "mukade", kana: "むかで", kanji: "百足", emoji: "🐛", hp: 500, attack: 45, color: "text-orange-700", skills: ['poison', 'weaken'], xpReward: 140 },
  { name: "Raposa Demônio", romaji: "youko", kana: "ようこ", kanji: "妖狐", emoji: "🦊", hp: 600, attack: 50, color: "text-yellow-600", skills: ['burn', 'blind'], xpReward: 160 },
  { name: "Goblin", romaji: "goburin", kana: "ごぶりん", kanji: "ゴブリン", emoji: "👹", hp: 700, attack: 60, color: "text-green-800", skills: ['poison', 'lifesteal'], xpReward: 200 },
  { name: "Gato Fantasma", romaji: "bakeneko", kana: "ばけねこ", kanji: "化け猫", emoji: "🐈‍⬛", hp: 850, attack: 70, color: "text-gray-900", skills: ['blind', 'critical'], xpReward: 250 },
  { name: "Esqueleto", romaji: "gaikotsu", kana: "がいこつ", kanji: "骸骨", emoji: "💀", hp: 1000, attack: 80, color: "text-gray-500", skills: ['shield'], xpReward: 300 },
  { name: "Espectro", romaji: "seirei", kana: "せいれい", kanji: "精霊", emoji: "🧚", hp: 1200, attack: 95, color: "text-blue-500", skills: ['weaken', 'heal'], xpReward: 380 },
  { name: "Fantasminha", romaji: "obake", kana: "おばけ", kanji: "お化け", emoji: "👻", hp: 1400, attack: 110, color: "text-purple-600", skills: ['blind', 'weaken'], xpReward: 450 },
  { name: "Gárgula", romaji: "gaagoiru", kana: "がーごいる", kanji: "ガーゴイル", emoji: "🗿", hp: 1600, attack: 130, color: "text-gray-600", skills: ['shield', 'critical'], xpReward: 520 },
  { name: "Zumbi", romaji: "zonbi", kana: "ぞんび", kanji: "ゾンビ", emoji: "🧟", hp: 1900, attack: 150, color: "text-green-800", skills: ['poison', 'lifesteal'], xpReward: 600 },
  { name: "Minotauro", romaji: "minotaurosu", kana: "みのたうろす", kanji: "ミノタウロス", emoji: "🐮", hp: 2200, attack: 175, color: "text-yellow-800", skills: ['critical', 'paralyze'], xpReward: 700 },
  { name: "Ogre", romaji: "oni", kana: "おに", kanji: "鬼", emoji: "👹", hp: 2500, attack: 200, color: "text-red-700", skills: ['critical', 'shield'], xpReward: 800 },
  { name: "Harpia", romaji: "haapii", kana: "はーぴー", kanji: "ハーピー", emoji: "🦅", hp: 2800, attack: 220, color: "text-blue-600", skills: ['blind', 'bleed'], xpReward: 950 },
  { name: "Serpente", romaji: "hebi", kana: "へび", kanji: "蛇", emoji: "🐍", hp: 3100, attack: 240, color: "text-green-700", skills: ['poison', 'weaken'], xpReward: 1050 },
  { name: "Golem de Pedra", romaji: "gooremu", kana: "ごーれむ", kanji: "ゴーレム", emoji: "🪨", hp: 3500, attack: 260, color: "text-gray-700", skills: ['shield', 'paralyze'], xpReward: 1200 },
  { name: "Golem de Gelo", romaji: "koori no gooremu", kana: "こおりのごーれむ", kanji: "氷のゴーレム", emoji: "🧊", hp: 4000, attack: 300, color: "text-blue-600", skills: ['shield'], xpReward: 1400 },
  { name: "Mago Negro", romaji: "kuromadou", kana: "くろまどう", kanji: "黒魔道", emoji: "🧙‍♂️", hp: 5500, attack: 350, color: "text-purple-700", skills: ['burn', 'blind', 'heal'], xpReward: 1800 },
  { name: "Golem de Fogo", romaji: "honoo no gooremu", kana: "ほのおのごーれむ", kanji: "炎のゴーレム", emoji: "🔥", hp: 6500, attack: 400, color: "text-red-800", skills: ['burn', 'critical'], xpReward: 2100 },
  { name: "Cavaleiro Fantasma", romaji: "yuurei kishi", kana: "ゆうれいきし", kanji: "幽霊騎士", emoji: "👻", hp: 7200, attack: 420, color: "text-gray-600", skills: ['lifesteal', 'weaken'], xpReward: 2300 },
  { name: "Orc Guerreiro", romaji: "ooku", kana: "おーく", kanji: "オーク", emoji: "🧌", hp: 8000, attack: 450, color: "text-green-900", skills: ['critical', 'summon'], xpReward: 2500 },
  { name: "Urso Feroz", romaji: "kuma", kana: "くま", kanji: "熊", emoji: "🐻", hp: 9500, attack: 550, color: "text-yellow-900", skills: ['critical', 'paralyze'], xpReward: 2900 },
  { name: "Wyvern", romaji: "waibaan", kana: "わいばーん", kanji: "ワイバーン", emoji: "🐉", hp: 10500, attack: 600, color: "text-green-600", skills: ['poison', 'bleed'], xpReward: 3200 },
  { name: "Quimera", romaji: "kimera", kana: "きめら", kanji: "キメラ", emoji: "🦁", hp: 12000, attack: 650, color: "text-yellow-700", skills: ['burn', 'poison', 'paralyze'], xpReward: 3500 },
  { name: "Basilisco", romaji: "bashirisuku", kana: "ばしりすく", kanji: "バジリスク", emoji: "🦎", hp: 14000, attack: 750, color: "text-green-800", skills: ['poison', 'weaken'], xpReward: 4200 },
  { name: "Behemoth", romaji: "behemosu", kana: "べへもす", kanji: "ベヒーモス", emoji: "🦏", hp: 16000, attack: 850, color: "text-gray-800", skills: ['critical', 'shield'], xpReward: 4600 },
  { name: "Cavaleiro das Trevas", romaji: "ankokukishi", kana: "あんこくきし", kanji: "暗黒騎士", emoji: "🤺", hp: 18000, attack: 900, color: "text-gray-900", skills: ['lifesteal', 'shield', 'blind'], xpReward: 5000, isBoss: true },
  { name: "Kraken", romaji: "kuraaken", kana: "くらーけん", kanji: "クラーケン", emoji: "🦑", hp: 21000, attack: 1050, color: "text-blue-800", skills: ['paralyze', 'blind'], xpReward: 6000 },
  { name: "Hidra", romaji: "hidora", kana: "ひどら", kanji: "ヒドラ", emoji: "🐉", hp: 25000, attack: 1150, color: "text-green-900", skills: ['poison', 'heal', 'summon'], xpReward: 7000, isBoss: true },
  { name: "Dragão", romaji: "ryuu", kana: "りゅう", kanji: "竜", emoji: "🐲", hp: 30000, attack: 1300, color: "text-red-700", skills: ['burn', 'critical', 'summon'], xpReward: 8000 },
  { name: "Lich", romaji: "ritchi", kana: "りっち", kanji: "リッチ", emoji: "🧟‍♂️", hp: 35000, attack: 1500, color: "text-purple-800", skills: ['lifesteal', 'weaken', 'blind'], xpReward: 10000, isBoss: true },
  { name: "Anjo Caído", romaji: "datenshi", kana: "だてんし", kanji: "堕天使", emoji: "🪽", hp: 42000, attack: 1750, color: "text-gray-600", skills: ['shield', 'heal', 'critical'], xpReward: 12000 },
  { name: "Dragão Ancião", romaji: "koryuu", kana: "こりゅう", kanji: "古竜", emoji: "🦖", hp: 50000, attack: 2000, color: "text-green-900", skills: ['burn', 'paralyze', 'heal', 'summon'], xpReward: 15000, isBoss: true },
  { name: "Ceifador", romaji: "shinigami", kana: "しにがみ", kanji: "死神", emoji: "💀", hp: 60000, attack: 2200, color: "text-gray-900", skills: ['lifesteal', 'blind', 'critical'], xpReward: 18000 },
  { name: "Titã", romaji: "kyojin", kana: "きょじん", kanji: "巨人", emoji: "🏔️", hp: 80000, attack: 2600, color: "text-yellow-800", skills: ['shield', 'paralyze'], xpReward: 22000 },
  { name: "Dragão do Vazio", romaji: "kyomuryuu", kana: "きょむりゅう", kanji: "虚無竜", emoji: "🌌", hp: 110000, attack: 3000, color: "text-indigo-900", skills: ['blind', 'weaken', 'summon'], xpReward: 26000, isBoss: true },
  { name: "Rei Demônio", romaji: "maou", kana: "まおう", kanji: "魔王", emoji: "👾", hp: 150000, attack: 3500, color: "text-purple-900", skills: ['blind', 'lifesteal', 'summon', 'heal', 'critical'], xpReward: 30000, isBoss: true },
  { name: "Avatar do Caos", romaji: "konton no keshin", kana: "こんとんのけしん", kanji: "混沌の化身", emoji: "🌪️", hp: 200000, attack: 4500, color: "text-gray-800", skills: ['paralyze', 'blind', 'weaken'], xpReward: 40000, isBoss: true },
  { name: "Serpente do Mundo", romaji: "sekai hebi", kana: "せかいへび", kanji: "世界蛇", emoji: "🐍", hp: 280000, attack: 5800, color: "text-green-950", skills: ['poison', 'shield', 'heal'], xpReward: 55000, isBoss: true },
  { name: "Arauto da Perdição", romaji: "hametsu no shisha", kana: "はめつのししゃ", kanji: "破滅の使者", emoji: "☄️", hp: 380000, attack: 7000, color: "text-red-900", skills: ['burn', 'critical', 'summon'], xpReward: 75000, isBoss: true },
  { name: "Deus da Destruição", romaji: "hakaishin", kana: "はかいしん", kanji: "破壊神", emoji: "🌌", hp: 500000, attack: 8000, color: "text-white text-shadow-md", skills: ['blind', 'paralyze', 'burn', 'critical', 'lifesteal'], xpReward: 99999, isBoss: true }
];
