export const monstersDatabase: Record<string, { name: string; translation?: string }[]> = {
  "Slime": [
    { name: "Slime, o grudento" },
    { name: "Jorge, o Slime" },
    { name: "Slime de Água Doce" },
    { name: "Pudim Mutante" },
    { name: "Slime Azedo" },
    { name: "Gota Colossal" },
    { name: "ベトベト (Betobeto)", translation: "O Pegajoso" },
    { name: "スライム太郎 (Slime Tarou)", translation: "Tarou, o Slime" },
    { name: "Slime Ancestral" },
    { name: "Geleia Amaldiçoada" },
    { name: "Slime de Magma" },
    { name: "Slime Metálico" },
    { name: "Slime Prismático" },
    { name: "Slime Tóxico" },
    { name: "Slime de Cristal" },
    { name: "Rei dos Slimes" },
    { name: "Rainha Slime" },
    { name: "Slime Corrosivo" },
    { name: "Slime Devorador" },
    { name: "Slime Elétrico" },
    { name: "Slime Ilusionista" },
    { name: "Slime das Profundezas" },
    { name: "Slime Sanguinário" },
    { name: "Slime Blindado" },
    { name: "Slime Gigante" },
    { name: "Slime Explosivo" },
    { name: "Slime de Gelo" },
    { name: "Slime Voador" },
    { name: "Slime Dourado" },
    { name: "Slime Curandeiro" },
    { name: "Slime Sombrio" },
    { name: "Slime Espinhoso" },
    { name: "Slime de Lama" },
    { name: "Slime Parasita" },
    { name: "Slime Radiante" },
    { name: "Slime Titânico" },
    { name: "黄金スライム (Ougon Suraimu)", translation: "Slime Dourado" },
    { name: "氷スライム (Koori Suraimu)", translation: "Slime de Gelo" },
    { name: "闇スライム (Yami Suraimu)", translation: "Slime das Trevas" },
    { name: "鉄スライム (Tetsu Suraimu)", translation: "Slime de Ferro" }
  ],
  "Morcego": [
    { name: "Morcego da Noite Escura" },
    { name: "Vlad, o Morceguinho" },
    { name: "Morcego Míope" },
    { name: "Sugador de Tintas" },
    { name: "Aspirador Alado" },
    { name: "Morcego das Cavernas Uivantes" },
    { name: "ブラッドサッカー (Buraddosakkaa)", translation: "Sugador de Sangue" },
    { name: "夜の影 (Yoru no Kage)", translation: "Sombra da Noite" },
    { name: "Morcego Cego" },
    { name: "Asa da Perdição" },
    { name: "Morcego Gigante" },
    { name: "Vampiro Menor" },
    { name: "Morcego de Fogo" },
    { name: "Morcego de Gelo" },
    { name: "Morcego Sanguinário" },
    { name: "Asa de Navalha" },
    { name: "Eco Sombrio" },
    { name: "Morcego Ilusionista" },
    { name: "Caçador de Veias" },
    { name: "Terror Noturno" },
    { name: "Morcego Espectral" },
    { name: "Morcego Espinhoso" },
    { name: "Morcego de Prata" },
    { name: "Morcego Dourado" },
    { name: "Morcego de Cristal" },
    { name: "Rei Morcego" },
    { name: "Morcego Pestilento" },
    { name: "Asa Rasgada" },
    { name: "Olhos Vermelhos" },
    { name: "Morcego Trovejante" },
    { name: "Morcego das Profundezas" },
    { name: "Morcego Camuflado" },
    { name: "Sombra Voadora" },
    { name: "Devorador de Insetos" },
    { name: "Morcego Venenoso" },
    { name: "Morcego Canibal" },
    { name: "吸血コウモリ (Kyuuketsu Koumori)", translation: "Morcego Vampiro" },
    { name: "炎の翼 (Honoo no Tsubasa)", translation: "Asas de Fogo" },
    { name: "巨大コウモリ (Kyodai Koumori)", translation: "Morcego Gigante" },
    { name: "鋼の翼 (Hagane no Tsubasa)", translation: "Asas de Aço" }
  ],
  "Aranha": [
    { name: "Aranha Pernilonga" },
    { name: "Maria, a Aranha" },
    { name: "Tecedora de Pesadelos" },
    { name: "Aranha Saltadora" },
    { name: "Viúva Desolada" },
    { name: "Aranha Caçadora" },
    { name: "八本足 (Happon-ashi)", translation: "Oito Pernas" },
    { name: "毒蜘蛛 (Dokugumo)", translation: "Aranha Venenosa" },
    { name: "Aranha de Pelúcia Esquisita" },
    { name: "Senhora das Teias" },
    { name: "Aranha Gigante" },
    { name: "Viúva Negra" },
    { name: "Aranha de Gelo" },
    { name: "Aranha de Fogo" },
    { name: "Tecedora de Ouro" },
    { name: "Aranha Espectral" },
    { name: "Aranha Blindada" },
    { name: "Aranha das Cavernas" },
    { name: "Aranha Assassina" },
    { name: "Aranha Rei" },
    { name: "Aranha Rainha" },
    { name: "Aranha Camuflada" },
    { name: "Aranha Espinhosa" },
    { name: "Aranha de Cristal" },
    { name: "Aranha Elétrica" },
    { name: "Aranha Sanguinária" },
    { name: "Devoradora de Homens" },
    { name: "Aranha do Pântano" },
    { name: "Aranha Metálica" },
    { name: "Aranha Ilusionista" },
    { name: "Aranha do Deserto" },
    { name: "Aranha Mutante" },
    { name: "Aranha Tóxica" },
    { name: "Aranha Voadora" },
    { name: "Teia Mortal" },
    { name: "Aranha Sombria" },
    { name: "巨大蜘蛛 (Kyodai Gumo)", translation: "Aranha Gigante" },
    { name: "糸の主 (Ito no Nushi)", translation: "Mestre das Teias" },
    { name: "氷蜘蛛 (Koorigumo)", translation: "Aranha de Gelo" },
    { name: "炎蜘蛛 (Honoo Gumo)", translation: "Aranha de Fogo" }
  ],
  "Sapo Mutante": [
    { name: "Sapo Gosmento" },
    { name: "Cururu Tóxico" },
    { name: "Príncipe Amaldiçoado" },
    { name: "Sapo-Boi Gigante" },
    { name: "Rã Venenosa" },
    { name: "Sapo Caolho" },
    { name: "Sapo Hipnótico" },
    { name: "毒蛙 (Dokugaeru)", translation: "Sapo Venenoso" },
    { name: "Saltador Sombrio" },
    { name: "Sapo Bolha" },
    { name: "Sapo de Fogo" },
    { name: "Sapo de Gelo" },
    { name: "Sapo Metálico" },
    { name: "Sapo Rei" },
    { name: "Sapo Curandeiro" },
    { name: "Sapo Ilusionista" },
    { name: "Sapo Camuflado" },
    { name: "Sapo Espinhoso" },
    { name: "Sapo de Cristal" },
    { name: "Sapo Elétrico" },
    { name: "Sapo Devorador" },
    { name: "Sapo do Pântano Sombrio" },
    { name: "Sapo Mutante Acelerado" },
    { name: "Sapo de Sangue" },
    { name: "Sapo Encouraçado" },
    { name: "Sapo Voador" },
    { name: "Sapo das Cavernas" },
    { name: "Sapo Venenoso Gigante" },
    { name: "Sapo Hipnotizador Menor" },
    { name: "Sapo de Lama" },
    { name: "Sapo de Pedra" },
    { name: "Sapo Dourado" },
    { name: "Sapo Fantasma" },
    { name: "Sapo Ancestral" },
    { name: "Sapo de Magma" },
    { name: "Sapo Místico" },
    { name: "炎蛙 (Honoo Gaeru)", translation: "Sapo de Fogo" },
    { name: "氷蛙 (Koori Gaeru)", translation: "Sapo de Gelo" },
    { name: "鉄蛙 (Tetsu Gaeru)", translation: "Sapo de Ferro" },
    { name: "巨大蛙 (Kyodai Gaeru)", translation: "Sapo Gigante" }
  ],
  "Rato Gigante": [
    { name: "Rato de Esgoto" },
    { name: "Roedor de Ossos" },
    { name: "Ratazana Pestilenta" },
    { name: "Rei dos Ratos" },
    { name: "Rato Mutante" },
    { name: "Rato Caçador" },
    { name: "Rato de Porão" },
    { name: "巨大鼠 (Kyodai Nezumi)", translation: "Rato Gigante" },
    { name: "Rato Rabudo" },
    { name: "Pestinha Espalhadora" },
    { name: "Rato de Fogo" },
    { name: "Rato de Gelo" },
    { name: "Rato Metálico" },
    { name: "Rato Assassino" },
    { name: "Rato Camuflado" },
    { name: "Rato Espinhoso" },
    { name: "Rato de Cristal" },
    { name: "Rato Elétrico" },
    { name: "Rato Sanguinário" },
    { name: "Rato Devorador" },
    { name: "Rato do Esgoto Profundo" },
    { name: "Rato Mutante Rápido" },
    { name: "Rato das Cavernas" },
    { name: "Rato Tóxico" },
    { name: "Rato Ilusionista" },
    { name: "Rato Voador" },
    { name: "Rato de Lama" },
    { name: "Rato de Pedra" },
    { name: "Rato Dourado" },
    { name: "Rato Fantasma" },
    { name: "Rato Ancestral" },
    { name: "Rato Cego" },
    { name: "Rato de Magma" },
    { name: "Rato de Prata" },
    { name: "Rato de Cemitério" },
    { name: "Rato Carniceiro" },
    { name: "炎鼠 (Honoo Nezumi)", translation: "Rato de Fogo" },
    { name: "氷鼠 (Koori Nezumi)", translation: "Rato de Gelo" },
    { name: "鉄鼠 (Tesshu)", translation: "Rato de Ferro" },
    { name: "暗黒鼠 (Ankoku Nezumi)", translation: "Rato Sombrio" }
  ],
  "Besouro": [
    { name: "Besouro Rola-Bosta Gigante" },
    { name: "Escaravelho de Ouro" },
    { name: "Besouro Rinoceronte Feroz" },
    { name: "Cascudo Ameaçador" },
    { name: "Besouro Bombardeiro" },
    { name: "Chifrudo Implacável" },
    { name: "甲虫 (Kabutomushi)", translation: "Besouro de Armadura" },
    { name: "Inseto Colossal" },
    { name: "Besouro Metálico" },
    { name: "Quebra-Nozes Ambulante" },
    { name: "Besouro de Cristal" },
    { name: "Besouro de Fogo" },
    { name: "Besouro de Gelo" },
    { name: "Besouro Elétrico" },
    { name: "Besouro Venenoso" },
    { name: "Escaravelho Sombrio" },
    { name: "Besouro Blindado" },
    { name: "Besouro Assassino" },
    { name: "Besouro Rei" },
    { name: "Besouro Rainha" },
    { name: "Besouro das Cavernas" },
    { name: "Besouro Ilusionista" },
    { name: "Besouro de Magma" },
    { name: "Besouro Voador Rápido" },
    { name: "Besouro de Pedra" },
    { name: "Besouro Devorador" },
    { name: "Escaravelho Amaldiçoado" },
    { name: "Besouro de Prata" },
    { name: "Besouro Gigante do Deserto" },
    { name: "Besouro Sanguinário" },
    { name: "Besouro Espinhoso" },
    { name: "Escaravelho Guardião" },
    { name: "Besouro Mutante" },
    { name: "Besouro Espectral" },
    { name: "Besouro Primordial" },
    { name: "Besouro Camuflado" },
    { name: "炎甲虫 (Honoo Kabutomushi)", translation: "Besouro de Fogo" },
    { name: "氷甲虫 (Koori Kabutomushi)", translation: "Besouro de Gelo" },
    { name: "黄金虫 (Kogane Mushi)", translation: "Besouro Dourado" },
    { name: "暗黒甲虫 (Ankoku Kabutomushi)", translation: "Besouro Sombrio" }
  ],
  "Tengu": [
    { name: "Tengu do Nariz Longo" },
    { name: "Corvo Místico" },
    { name: "Guardião da Montanha" },
    { name: "Tengu Brincalhão" },
    { name: "Ventania Escarlate" },
    { name: "Tengu Ancião" },
    { name: "天狗 (Tengu)", translation: "Demônio Corvo" },
    { name: "Bico de Aço" },
    { name: "Mestre dos Ventos" },
    { name: "Tengu Caído" },
    { name: "Tengu de Fogo" },
    { name: "Tengu de Gelo" },
    { name: "Tengu das Sombras" },
    { name: "Tengu Trovejante" },
    { name: "Tengu Espadachim" },
    { name: "Tengu Ilusionista" },
    { name: "Tengu Arqueiro" },
    { name: "Tengu Rei" },
    { name: "Tengu Mutante" },
    { name: "Tengu Corrompido" },
    { name: "Tengu Guardião" },
    { name: "Senhor dos Corvos" },
    { name: "Tengu Assassino" },
    { name: "Tengu Sanguinário" },
    { name: "Tengu de Prata" },
    { name: "Tengu Dourado" },
    { name: "Tengu do Desfiladeiro" },
    { name: "Tengu Errante" },
    { name: "Tengu Encouraçado" },
    { name: "Tengu Espiritual" },
    { name: "Tengu Venenoso" },
    { name: "Asa de Ébano" },
    { name: "Tengu Alquimista" },
    { name: "Arauto da Tempestade" },
    { name: "Tengu Mascarado" },
    { name: "Mestre da Montanha Negra" },
    { name: "炎天狗 (Honoo Tengu)", translation: "Tengu de Fogo" },
    { name: "氷天狗 (Koori Tengu)", translation: "Tengu de Gelo" },
    { name: "雷天狗 (Kaminari Tengu)", translation: "Tengu do Trovão" },
    { name: "大天狗 (Daitengu)", translation: "Grande Tengu" }
  ],
  "Lobo Selvagem": [
    { name: "Lobo Solitário" },
    { name: "Fenrir Filhote" },
    { name: "Presas de Prata" },
    { name: "Uivador da Lua Cheia" },
    { name: "Lobo Raivoso" },
    { name: "Caçador Noturno" },
    { name: "狼 (Ookami)", translation: "Lobo Divino" },
    { name: "Lobo das Neves" },
    { name: "Fera Feroz" },
    { name: "Cão do Mato Sombrio" },
    { name: "Lobo de Fogo" },
    { name: "Lobo de Gelo" },
    { name: "Lobo Elétrico" },
    { name: "Lobo Sombrio" },
    { name: "Lobo Rei" },
    { name: "Lobo Gigante" },
    { name: "Lobo Sanguinário" },
    { name: "Lobo Ilusionista" },
    { name: "Lobo Metálico" },
    { name: "Lobo Cristalino" },
    { name: "Lobo Venenoso" },
    { name: "Alfa da Alcatéia" },
    { name: "Lobo Espectral" },
    { name: "Lobo Ancestral" },
    { name: "Lobo Mutante" },
    { name: "Lobo das Cavernas" },
    { name: "Lobo Infernal" },
    { name: "Lobo Camuflado" },
    { name: "Lobo Dourado" },
    { name: "Lobo de Magma" },
    { name: "Lobo das Sombras" },
    { name: "Lobo Espinhoso" },
    { name: "Devorador de Ovelhas" },
    { name: "Lobo Demoníaco" },
    { name: "Lobo Bípede" },
    { name: "Uivador Sangrento" },
    { name: "炎狼 (Honoo Ookami)", translation: "Lobo de Fogo" },
    { name: "氷狼 (Koori Ookami)", translation: "Lobo de Gelo" },
    { name: "鉄狼 (Tetsu Ookami)", translation: "Lobo de Ferro" },
    { name: "魔狼 (Marou)", translation: "Lobo Demônio" }
  ],
  "Centopeia": [
    { name: "Centopeia Rastejante" },
    { name: "Mil Pernas Venenosas" },
    { name: "Verme Rastejante" },
    { name: "Lacraia Gigante" },
    { name: "Horror do Subterrâneo" },
    { name: "Centopeia Couraçada" },
    { name: "大百足 (Oomukade)", translation: "Centopeia Gigante" },
    { name: "Devoradora de Terra" },
    { name: "Abraço Venenoso" },
    { name: "Inseto Deslizante" },
    { name: "Centopeia de Fogo" },
    { name: "Centopeia de Gelo" },
    { name: "Centopeia Elétrica" },
    { name: "Centopeia das Sombras" },
    { name: "Centopeia Rei" },
    { name: "Centopeia Rainha" },
    { name: "Centopeia de Cristal" },
    { name: "Centopeia Metálica" },
    { name: "Centopeia Sanguinária" },
    { name: "Centopeia Assassina" },
    { name: "Centopeia Mutante" },
    { name: "Centopeia Ilusionista" },
    { name: "Centopeia do Deserto" },
    { name: "Centopeia do Pântano" },
    { name: "Centopeia de Magma" },
    { name: "Centopeia Espinhosa" },
    { name: "Centopeia Espectral" },
    { name: "Centopeia Ancestral" },
    { name: "Centopeia Cega" },
    { name: "Centopeia Dourada" },
    { name: "Centopeia Voadora" },
    { name: "Centopeia Ácida" },
    { name: "Milípedes Colossal" },
    { name: "Lacraia das Cavernas" },
    { name: "Rastejador do Abismo" },
    { name: "Devorador de Carnes" },
    { name: "炎百足 (Honoo Mukade)", translation: "Centopeia de Fogo" },
    { name: "氷百足 (Koori Mukade)", translation: "Centopeia de Gelo" },
    { name: "鉄百足 (Tetsu Mukade)", translation: "Centopeia de Ferro" },
    { name: "毒百足 (Doku Mukade)", translation: "Centopeia Venenosa" }
  ],
  "Raposa Demônio": [
    { name: "Kitsune de Nove Caudas" },
    { name: "Raposa Enganadora" },
    { name: "Chama Azul" },
    { name: "Raposa Sorrateira" },
    { name: "Ilusionista Peluda" },
    { name: "Raposa da Meia-Noite" },
    { name: "妖狐 (Youko)", translation: "Raposa Espectral" },
    { name: "Sedutora Selvagem" },
    { name: "Brincalhona Mística" },
    { name: "Besta das Sombras" },
    { name: "Raposa de Fogo" },
    { name: "Raposa de Gelo" },
    { name: "Raposa do Trovão" },
    { name: "Raposa Sombria" },
    { name: "Raposa Branca" },
    { name: "Raposa Dourada" },
    { name: "Raposa de Cristal" },
    { name: "Raposa Metálica" },
    { name: "Raposa Sanguinária" },
    { name: "Raposa Assassina" },
    { name: "Kitsune Corrompida" },
    { name: "Kitsune Ancestral" },
    { name: "Raposa Venenosa" },
    { name: "Raposa Voadora" },
    { name: "Raposa de Três Caudas" },
    { name: "Raposa de Seis Caudas" },
    { name: "Guardiã do Santuário" },
    { name: "Raposa Caçadora" },
    { name: "Espírito da Floresta" },
    { name: "Raposa Prateada" },
    { name: "Raposa Infernal" },
    { name: "Ilusionista Mestra" },
    { name: "Raposa do Deserto" },
    { name: "Mensageira dos Deuses" },
    { name: "Raposa da Tempestade" },
    { name: "Raposa Fantasma" },
    { name: "炎狐 (Honoo Gitsune)", translation: "Raposa de Fogo" },
    { name: "氷狐 (Koori Gitsune)", translation: "Raposa de Gelo" },
    { name: "九尾の狐 (Kyuubi no Kitsune)", translation: "Raposa de Nove Caudas" },
    { name: "黒狐 (Kuro Gitsune)", translation: "Raposa Negra" }
  ],
  "Goblin": [
    { name: "Goblin Risonho" },
    { name: "Bob, o Saqueador" },
    { name: "Goblin da Faca Cega" },
    { name: "Guarda-Costas Goblin" },
    { name: "Goblin Mesquinho" },
    { name: "Atirador Cego" },
    { name: "緑の悪魔 (Midori no Akuma)", translation: "Demônio Verde" },
    { name: "ゴブリン王 (Goburin-ou)", translation: "Rei Goblin" },
    { name: "Goblin Sedento" },
    { name: "Ladrão de Ouro" },
    { name: "Goblin Arqueiro" },
    { name: "Goblin Assassino" },
    { name: "Goblin Xamã" },
    { name: "Goblin Guerreiro" },
    { name: "Goblin Ilusionista" },
    { name: "Goblin de Fogo" },
    { name: "Goblin de Gelo" },
    { name: "Goblin Sombrio" },
    { name: "Goblin Blindado" },
    { name: "Goblin Gigante" },
    { name: "Goblin Mutante" },
    { name: "Goblin Venenoso" },
    { name: "Goblin das Cavernas" },
    { name: "Goblin Sanguinário" },
    { name: "Goblin Bombardeiro" },
    { name: "Goblin Montador de Lobo" },
    { name: "Líder Goblin" },
    { name: "Goblin Camuflado" },
    { name: "Goblin Espectral" },
    { name: "Goblin Ferreiro" },
    { name: "Goblin Ladrão de Galinhas" },
    { name: "Goblin do Pântano" },
    { name: "Goblin Domador" },
    { name: "Goblin Enlouquecido" },
    { name: "Goblin Covarde" },
    { name: "Goblin Dourado" },
    { name: "炎ゴブリン (Honoo Goburin)", translation: "Goblin de Fogo" },
    { name: "氷ゴブリン (Koori Goburin)", translation: "Goblin de Gelo" },
    { name: "闇ゴブリン (Yami Goburin)", translation: "Goblin Sombrio" },
    { name: "大ゴブリン (Dai Goburin)", translation: "Grande Goblin" }
  ],
  "Gato Fantasma": [
    { name: "Gato Preto Azarento" },
    { name: "Bichano Translúcido" },
    { name: "Miado Sombrio" },
    { name: "Felino Assombroso" },
    { name: "Gato de Botas Rotas" },
    { name: "Ronronar Fantasmagórico" },
    { name: "化け猫 (Bakeneko)", translation: "Gato Monstro" },
    { name: "Caçador de Ratos Espectrais" },
    { name: "Patas Silenciosas" },
    { name: "Gato das Nove Vidas" },
    { name: "Gato Esmeralda" },
    { name: "Gato de Fogo Fantasma" },
    { name: "Gato de Gelo Translúcido" },
    { name: "Felino Ilusionista" },
    { name: "Gato Metálico Assombrado" },
    { name: "Gato Demônio Gigante" },
    { name: "Gato Sanguinário" },
    { name: "Gato Rei Fantasma" },
    { name: "Gato Venenoso" },
    { name: "Gato Elétrico" },
    { name: "Gato Sombrio" },
    { name: "Gato Mutante" },
    { name: "Felino Ancestral" },
    { name: "Gato das Cavernas" },
    { name: "Gato de Cristal" },
    { name: "Ronronar da Morte" },
    { name: "Gato Espiritual" },
    { name: "Gato Dourado Assombrado" },
    { name: "Gato de Três Olhos" },
    { name: "Gato de Duas Caudas" },
    { name: "Felino Amaldiçoado" },
    { name: "Gato Protetor de Túmulos" },
    { name: "Gato Infernal" },
    { name: "Mestre dos Miados" },
    { name: "Gato Branco Translúcido" },
    { name: "Felino Invisível" },
    { name: "猫又 (Nekomata)", translation: "Gato de Duas Caudas" },
    { name: "炎猫 (Honoo Neko)", translation: "Gato de Fogo" },
    { name: "氷猫 (Koori Neko)", translation: "Gato de Gelo" },
    { name: "影猫 (Kage Neko)", translation: "Gato das Sombras" }
  ],
  "Esqueleto": [
    { name: "Ossos Ruidosos" },
    { name: "Skelly, o Calvo" },
    { name: "Guerreiro de Cálcio" },
    { name: "Pilha de Ossos" },
    { name: "Esqueleto sem Mandíbula" },
    { name: "Guardião da Tumba" },
    { name: "骸骨 (Gaikotsu)", translation: "Caveira Animada" },
    { name: "死の騎士 (Shi no Kishi)", translation: "Cavaleiro da Morte" },
    { name: "Esqueleto Dançarino" },
    { name: "Sentinela de Marfim" },
    { name: "Esqueleto Arqueiro" },
    { name: "Esqueleto Mago" },
    { name: "Esqueleto Gigante" },
    { name: "Esqueleto de Fogo" },
    { name: "Esqueleto de Gelo" },
    { name: "Esqueleto Sombrio" },
    { name: "Esqueleto de Ferro" },
    { name: "Esqueleto de Ouro" },
    { name: "Esqueleto Ilusionista" },
    { name: "Esqueleto Assassino" },
    { name: "Rei Esqueleto" },
    { name: "Esqueleto Venenoso" },
    { name: "Esqueleto Mutante" },
    { name: "Esqueleto Sanguinário" },
    { name: "Esqueleto Blindado" },
    { name: "Esqueleto Rastejante" },
    { name: "Esqueleto Sem Cabeça" },
    { name: "Ossos Flamejantes" },
    { name: "Esqueleto Elétrico" },
    { name: "Esqueleto de Cristal" },
    { name: "Esqueleto Guardião" },
    { name: "Senhor dos Ossos" },
    { name: "Esqueleto Espectral" },
    { name: "Esqueleto Bardo" },
    { name: "Cavaleiro Ossudo" },
    { name: "Ossos Amaldiçoados" },
    { name: "炎骸骨 (Honoo Gaikotsu)", translation: "Esqueleto de Fogo" },
    { name: "氷骸骨 (Koori Gaikotsu)", translation: "Esqueleto de Gelo" },
    { name: "鉄骸骨 (Tetsu Gaikotsu)", translation: "Esqueleto de Ferro" },
    { name: "骸骨王 (Gaikotsu-ou)", translation: "Rei Esqueleto" }
  ],
  "Espectro": [
    { name: "Vulto Gélido" },
    { name: "Assombração Tímida" },
    { name: "Alma Perdida" },
    { name: "Aparição Sinistra" },
    { name: "Eco do Passado" },
    { name: "Espectro Choroso" },
    { name: "精霊 (Seirei)", translation: "Espírito Sombrio" },
    { name: "Sombra Errante" },
    { name: "Vingador Invisível" },
    { name: "Sopro da Morte" },
    { name: "Espectro de Fogo" },
    { name: "Espectro de Gelo" },
    { name: "Espectro Elétrico" },
    { name: "Espectro Ilusionista" },
    { name: "Espectro Gigante" },
    { name: "Espectro Mutante" },
    { name: "Espectro Assassino" },
    { name: "Espectro Rei" },
    { name: "Espectro Sanguinário" },
    { name: "Espectro de Prata" },
    { name: "Espectro de Ouro" },
    { name: "Espectro de Cristal" },
    { name: "Espectro Venenoso" },
    { name: "Espectro Cego" },
    { name: "Senhor das Assombrações" },
    { name: "Alma Corrompida" },
    { name: "Espectro Encouraçado" },
    { name: "Vulto Rápido" },
    { name: "Sussurro Enlouquecedor" },
    { name: "Espectro Ancestral" },
    { name: "Espectro Guardião" },
    { name: "Espectro da Masmorra" },
    { name: "Poltergeist Violento" },
    { name: "Aparição Demoníaca" },
    { name: "Mestre dos Ecos" },
    { name: "Alma Vingativa" },
    { name: "炎霊 (Honoo Rei)", translation: "Espírito de Fogo" },
    { name: "氷霊 (Koori Rei)", translation: "Espírito de Gelo" },
    { name: "悪霊 (Akuryou)", translation: "Espírito Maligno" },
    { name: "死霊 (Shiryou)", translation: "Espírito Morto" }
  ],
  "Fantasminha": [
    { name: "Casper, o Chato" },
    { name: "Fantasma do Lençol Furado" },
    { name: "Assombração Infantil" },
    { name: "Ectoplasma Pegajoso" },
    { name: "Poltergeist Brincalhão" },
    { name: "Alma Penada" },
    { name: "お化け (Obake)", translation: "Assombração" },
    { name: "Espírito Bagunceiro" },
    { name: "Visão Esfumaçada" },
    { name: "Chorão Invisível" },
    { name: "Fantasminha de Fogo" },
    { name: "Fantasminha de Gelo" },
    { name: "Fantasminha Elétrico" },
    { name: "Fantasminha Ilusionista" },
    { name: "Fantasminha Gigante" },
    { name: "Fantasminha Rei" },
    { name: "Fantasminha Sombrio" },
    { name: "Fantasminha Sanguinário" },
    { name: "Fantasminha Mutante" },
    { name: "Fantasminha Assassino" },
    { name: "Fantasminha de Prata" },
    { name: "Fantasminha Dourado" },
    { name: "Fantasminha de Cristal" },
    { name: "Fantasminha Venenoso" },
    { name: "Fantasma Escondido" },
    { name: "Ectoplasma Tóxico" },
    { name: "Alma Assustada" },
    { name: "Fantasminha Guloso" },
    { name: "Fantasminha de Lama" },
    { name: "Fantasminha Encouraçado" },
    { name: "Fantasma Sorridente" },
    { name: "Vulto Pequenino" },
    { name: "Fantasma Confuso" },
    { name: "Espírito Tímido" },
    { name: "Assombração Amigável" },
    { name: "Fantasma Sem Rosto" },
    { name: "炎お化け (Honoo Obake)", translation: "Fantasma de Fogo" },
    { name: "氷お化け (Koori Obake)", translation: "Fantasma de Gelo" },
    { name: "闇お化け (Yami Obake)", translation: "Fantasma Sombrio" },
    { name: "小霊 (Shourei)", translation: "Pequeno Espírito" }
  ],
  "Gárgula": [
    { name: "Estátua Viva" },
    { name: "Gárgula de Mármore" },
    { name: "Demônio de Pedra" },
    { name: "Vigia Noturno" },
    { name: "Asas de Granito" },
    { name: "Observador do Telhado" },
    { name: "ガーゴイル (Gaagoiru)", translation: "Sentinela de Pedra" },
    { name: "Monstro Petrificado" },
    { name: "Cuspidor de Água" },
    { name: "Defensor do Castelo" },
    { name: "Gárgula de Fogo" },
    { name: "Gárgula de Gelo" },
    { name: "Gárgula Metálica" },
    { name: "Gárgula de Cristal" },
    { name: "Gárgula Obsidiana" },
    { name: "Gárgula Ilusionista" },
    { name: "Gárgula Rei" },
    { name: "Gárgula Gigante" },
    { name: "Gárgula Mutante" },
    { name: "Gárgula Assassina" },
    { name: "Gárgula Sanguinária" },
    { name: "Gárgula Venenosa" },
    { name: "Gárgula Elétrica" },
    { name: "Gárgula de Magma" },
    { name: "Gárgula Dourada" },
    { name: "Gárgula de Prata" },
    { name: "Estátua Amaldiçoada" },
    { name: "Gárgula Sombria" },
    { name: "Gárgula Sem Asas" },
    { name: "Gárgula Rastejante" },
    { name: "Sentinela Ancestral" },
    { name: "Guardião Alado" },
    { name: "Gárgula Demônio" },
    { name: "Gárgula de Diamante" },
    { name: "Gárgula de Lama" },
    { name: "Gárgula Desperta" },
    { name: "炎ガーゴイル (Honoo Gaagoiru)", translation: "Gárgula de Fogo" },
    { name: "氷ガーゴイル (Koori Gaagoiru)", translation: "Gárgula de Gelo" },
    { name: "鉄ガーゴイル (Tetsu Gaagoiru)", translation: "Gárgula de Ferro" },
    { name: "闇ガーゴイル (Yami Gaagoiru)", translation: "Gárgula das Trevas" }
  ],
  "Zumbi": [
    { name: "Morto-Vivo Faminto" },
    { name: "Andarilho Lento" },
    { name: "Zumbi sem Braço" },
    { name: "Comedor de Cérebros" },
    { name: "Carniçal Fedorento" },
    { name: "Defunto Animado" },
    { name: "ゾンビ (Zonbi)", translation: "Cadáver Errante" },
    { name: "Putrefato" },
    { name: "Infectado Desajeitado" },
    { name: "Renascido das Trevas" },
    { name: "Zumbi de Fogo" },
    { name: "Zumbi de Gelo" },
    { name: "Zumbi Tóxico" },
    { name: "Zumbi Mutante" },
    { name: "Zumbi Gigante" },
    { name: "Zumbi Corredor" },
    { name: "Zumbi Blindado" },
    { name: "Zumbi Sanguinário" },
    { name: "Zumbi Assassino" },
    { name: "Rei Zumbi" },
    { name: "Zumbi Ilusionista" },
    { name: "Zumbi Elétrico" },
    { name: "Zumbi de Magma" },
    { name: "Zumbi Rastejante" },
    { name: "Zumbi Explosivo" },
    { name: "Zumbi Sem Cabeça" },
    { name: "Carniçal Ancestral" },
    { name: "Zumbi do Pântano" },
    { name: "Zumbi Metálico" },
    { name: "Zumbi Parasita" },
    { name: "Morto-Vivo Espectral" },
    { name: "Zumbi de Lama" },
    { name: "Infectado Mutante" },
    { name: "Zumbi Voador" },
    { name: "Senhor dos Mortos" },
    { name: "Zumbi Dourado" },
    { name: "炎ゾンビ (Honoo Zonbi)", translation: "Zumbi de Fogo" },
    { name: "氷ゾンビ (Koori Zonbi)", translation: "Zumbi de Gelo" },
    { name: "毒ゾンビ (Doku Zonbi)", translation: "Zumbi Venenoso" },
    { name: "巨大ゾンビ (Kyodai Zonbi)", translation: "Zumbi Gigante" }
  ],
  "Minotauro": [
    { name: "Touro Furioso" },
    { name: "Guardião do Labirinto" },
    { name: "Chifres de Sangue" },
    { name: "Fera Bípede" },
    { name: "Destruidor de Paredes" },
    { name: "Minotauro Cego de Raiva" },
    { name: "牛頭 (Gozu)", translation: "Cabeça de Touro" },
    { name: "Açougueiro Selvagem" },
    { name: "Esmagador de Crânios" },
    { name: "Besta Taurina" },
    { name: "Minotauro de Fogo" },
    { name: "Minotauro de Gelo" },
    { name: "Minotauro Sombrio" },
    { name: "Minotauro Blindado" },
    { name: "Minotauro Rei" },
    { name: "Minotauro Gigante" },
    { name: "Minotauro Assassino" },
    { name: "Minotauro Mutante" },
    { name: "Minotauro Metálico" },
    { name: "Minotauro de Ouro" },
    { name: "Minotauro de Cristal" },
    { name: "Minotauro Venenoso" },
    { name: "Minotauro Elétrico" },
    { name: "Minotauro Ilusionista" },
    { name: "Minotauro Sanguinário" },
    { name: "Minotauro de Magma" },
    { name: "Minotauro Arqueiro" },
    { name: "Minotauro Xamã" },
    { name: "Minotauro Espectral" },
    { name: "Chifres de Ferro" },
    { name: "Touro Ancestral" },
    { name: "Senhor do Labirinto Negro" },
    { name: "Minotauro Corrompido" },
    { name: "Minotauro Guerreiro" },
    { name: "Minotauro Devorador" },
    { name: "Minotauro do Deserto" },
    { name: "炎牛頭 (Honoo Gozu)", translation: "Minotauro de Fogo" },
    { name: "氷牛頭 (Koori Gozu)", translation: "Minotauro de Gelo" },
    { name: "鉄牛頭 (Tetsu Gozu)", translation: "Minotauro de Ferro" },
    { name: "闇牛頭 (Yami Gozu)", translation: "Minotauro Sombrio" }
  ],
  "Ogre": [
    { name: "Ogro Guloso" },
    { name: "Gigante Feio" },
    { name: "Quebra-Ossos" },
    { name: "Ogro de Duas Cabeças" },
    { name: "Brutamontes Bestial" },
    { name: "Monstro Pantanoso" },
    { name: "鬼 (Oni)", translation: "Demônio de Chifres" },
    { name: "Comedor de Homens" },
    { name: "Titã Esverdeado" },
    { name: "Ogro Claviculário" },
    { name: "Ogro de Fogo" },
    { name: "Ogro de Gelo" },
    { name: "Ogro Sombrio" },
    { name: "Ogro Rei" },
    { name: "Ogro Blindado" },
    { name: "Ogro Mutante" },
    { name: "Ogro Assassino" },
    { name: "Ogro Sanguinário" },
    { name: "Ogro Metálico" },
    { name: "Ogro Venenoso" },
    { name: "Ogro Ilusionista" },
    { name: "Ogro Elétrico" },
    { name: "Ogro de Ouro" },
    { name: "Ogro de Cristal" },
    { name: "Ogro de Magma" },
    { name: "Ogro Gigante Colossal" },
    { name: "Ogro Cego" },
    { name: "Ogro Xamã" },
    { name: "Ogro Guerreiro" },
    { name: "Ogro das Cavernas" },
    { name: "Ogro Espectral" },
    { name: "Ogro Ancestral" },
    { name: "Ogro Corrompido" },
    { name: "Senhor dos Ogros" },
    { name: "Ogro de Pedra" },
    { name: "Brutamontes Selvagem" },
    { name: "炎鬼 (Honoo Oni)", translation: "Ogro de Fogo" },
    { name: "氷鬼 (Koori Oni)", translation: "Ogro de Gelo" },
    { name: "鉄鬼 (Tetsu Oni)", translation: "Ogro de Ferro" },
    { name: "大鬼 (Ooni)", translation: "Grande Ogro" }
  ],
  "Harpia": [
    { name: "Mulher-Pássaro" },
    { name: "Cantora da Morte" },
    { name: "Penas Cortantes" },
    { name: "Bruxa Alada" },
    { name: "Senhora dos Ventos" },
    { name: "Predadora dos Céus" },
    { name: "ハーピー (Haapii)", translation: "Demônio Alado" },
    { name: "Rasga-Céus" },
    { name: "Voo Rasante" },
    { name: "Caçadora Aérea" },
    { name: "Harpia de Fogo" },
    { name: "Harpia de Gelo" },
    { name: "Harpia do Trovão" },
    { name: "Harpia Sombria" },
    { name: "Harpia Rei (Rainha)" },
    { name: "Harpia Gigante" },
    { name: "Harpia Metálica" },
    { name: "Harpia Venenosa" },
    { name: "Harpia Assassina" },
    { name: "Harpia Sanguinária" },
    { name: "Harpia Ilusionista" },
    { name: "Harpia Mutante" },
    { name: "Harpia de Cristal" },
    { name: "Harpia de Ouro" },
    { name: "Harpia Blindada" },
    { name: "Harpia Espectral" },
    { name: "Harpia das Cavernas" },
    { name: "Harpia Tempestuosa" },
    { name: "Penas de Aço" },
    { name: "Harpia Corrompida" },
    { name: "Bruxa dos Céus Negros" },
    { name: "Harpia Ancestral" },
    { name: "Harpia Caçadora de Homens" },
    { name: "Senhora das Tempestades" },
    { name: "Harpia de Magma" },
    { name: "Harpia Cega" },
    { name: "炎ハーピー (Honoo Haapii)", translation: "Harpia de Fogo" },
    { name: "氷ハーピー (Koori Haapii)", translation: "Harpia de Gelo" },
    { name: "鋼ハーピー (Hagane Haapii)", translation: "Harpia de Aço" },
    { name: "闇ハーピー (Yami Haapii)", translation: "Harpia Sombria" }
  ],
  "Serpente": [
    { name: "Cobra Rastejante" },
    { name: "Víbora Venenosa" },
    { name: "Abraço Mortal" },
    { name: "Serpente de Escamas Negras" },
    { name: "Cuspidora de Peçonha" },
    { name: "Naja Hipnótica" },
    { name: "大蛇 (Orochi)", translation: "Serpente Gigante" },
    { name: "Língua Bifurcada" },
    { name: "Asfixiadora Silenciosa" },
    { name: "Serpente Ancestral" },
    { name: "Serpente de Fogo" },
    { name: "Serpente de Gelo" },
    { name: "Serpente Elétrica" },
    { name: "Serpente Sombria" },
    { name: "Serpente Rei" },
    { name: "Serpente Gigante Colossal" },
    { name: "Serpente Mutante" },
    { name: "Serpente Metálica" },
    { name: "Serpente Assassina" },
    { name: "Serpente Sanguinária" },
    { name: "Serpente de Cristal" },
    { name: "Serpente Ilusionista" },
    { name: "Serpente de Ouro" },
    { name: "Serpente Blindada" },
    { name: "Serpente Espectral" },
    { name: "Serpente de Magma" },
    { name: "Serpente Voadora" },
    { name: "Serpente de Duas Cabeças" },
    { name: "Serpente do Deserto" },
    { name: "Serpente do Pântano" },
    { name: "Serpente Coral Mortal" },
    { name: "Serpente Cega" },
    { name: "Víbora Ancestral" },
    { name: "Senhora das Cobras" },
    { name: "Serpente Ácida" },
    { name: "Serpente Mística" },
    { name: "炎蛇 (Honoo Hebi)", translation: "Serpente de Fogo" },
    { name: "氷蛇 (Koori Hebi)", translation: "Serpente de Gelo" },
    { name: "鉄蛇 (Tetsu Hebi)", translation: "Serpente de Ferro" },
    { name: "毒蛇 (Dokuhebi)", translation: "Serpente Venenosa" }
  ],
  "Golem de Pedra": [
    { name: "Golem de Cascalho" },
    { name: "Montanha que Anda" },
    { name: "Sentinela de Argila" },
    { name: "Golem Inacabado" },
    { name: "Punhos de Granito" },
    { name: "Guardião de Ferro" },
    { name: "石の巨人 (Ishi no Kyojin)", translation: "Gigante de Pedra" },
    { name: "Monólito Errante" },
    { name: "Pilar de Runas" },
    { name: "Punhos da Terra" },
    { name: "Golem de Fogo e Pedra" },
    { name: "Golem de Gelo e Pedra" },
    { name: "Golem de Ouro" },
    { name: "Golem Metálico" },
    { name: "Golem Rei" },
    { name: "Golem Colossal" },
    { name: "Golem Mutante" },
    { name: "Golem Assassino" },
    { name: "Golem Sanguinário" },
    { name: "Golem Venenoso" },
    { name: "Golem Ilusionista" },
    { name: "Golem Elétrico" },
    { name: "Golem de Cristal" },
    { name: "Golem de Obsidiana" },
    { name: "Golem Espectral" },
    { name: "Golem Ancestral" },
    { name: "Golem Sombrio" },
    { name: "Golem de Lama" },
    { name: "Golem Corrompido" },
    { name: "Golem Guardião Antigo" },
    { name: "Senhor da Montanha" },
    { name: "Golem Desperto" },
    { name: "Golem de Diamante" },
    { name: "Golem de Esmeralda" },
    { name: "Pedra Amaldiçoada" },
    { name: "Golem Destruidor" },
    { name: "炎石の巨人 (Honoo Ishi no Kyojin)", translation: "Gigante de Pedra e Fogo" },
    { name: "氷石の巨人 (Koori Ishi no Kyojin)", translation: "Gigante de Pedra e Gelo" },
    { name: "黄金の巨人 (Ougon no Kyojin)", translation: "Gigante Dourado" },
    { name: "暗黒の巨人 (Ankoku no Kyojin)", translation: "Gigante das Trevas" }
  ],
  "Golem de Gelo": [
    { name: "Estátua de Neve" },
    { name: "Sentinela Glacial" },
    { name: "Congelador de Almas" },
    { name: "Golem de Cristal" },
    { name: "Nevasca Ambulante" },
    { name: "Gigante de Frio" },
    { name: "氷の魔像 (Koori no Mazou)", translation: "Golem Gelado" },
    { name: "Estalactite Viva" },
    { name: "Punhos de Gelo" },
    { name: "Guardião do Inverno" },
    { name: "Golem de Gelo Negro" },
    { name: "Golem de Frio Absoluto" },
    { name: "Golem Rei do Inverno" },
    { name: "Golem de Gelo Colossal" },
    { name: "Golem Metálico Congelado" },
    { name: "Golem de Gelo Sanguinário" },
    { name: "Golem de Gelo Assassino" },
    { name: "Golem de Neve Venenosa" },
    { name: "Golem Ilusionista de Gelo" },
    { name: "Golem de Gelo Elétrico" },
    { name: "Golem de Gelo Dourado" },
    { name: "Golem Mutante Glacial" },
    { name: "Golem de Gelo Ancestral" },
    { name: "Golem Espectral de Gelo" },
    { name: "Golem de Gelo Eterno" },
    { name: "Senhor da Nevasca" },
    { name: "Coração de Gelo" },
    { name: "Golem de Gelo Espinhoso" },
    { name: "Golem de Geada" },
    { name: "Titã de Cristal de Gelo" },
    { name: "Golem de Gelo Quebrado" },
    { name: "Sentinela Polar" },
    { name: "Golem de Gelo Rápido" },
    { name: "Golem Avalanche" },
    { name: "Guardião da Tundra" },
    { name: "Golem Congelante Supremo" },
    { name: "黒氷の魔像 (Kurogoori no Mazou)", translation: "Golem de Gelo Negro" },
    { name: "鋼氷の魔像 (Kougoori no Mazou)", translation: "Golem de Gelo de Aço" },
    { name: "古代氷の魔像 (Kodai Koori no Mazou)", translation: "Golem de Gelo Ancestral" },
    { name: "吹雪の巨人 (Fubuki no Kyojin)", translation: "Gigante da Nevasca" }
  ],
  "Mago Negro": [
    { name: "Aprendiz de Trevas" },
    { name: "Mago que Erra" },
    { name: "Sombra do Grimório" },
    { name: "Bruxo Solitário" },
    { name: "Mago Rejeitado" },
    { name: "Senhor do Caos" },
    { name: "黒魔道士 (Kuromadoushi)", translation: "Mestre das Trevas" },
    { name: "Ocultista Sinistro" },
    { name: "Invocador Maldito" },
    { name: "Feiticeiro Profano" },
    { name: "Mago Negro de Fogo" },
    { name: "Mago Negro de Gelo" },
    { name: "Mago Negro do Trovão" },
    { name: "Necromante Iniciante" },
    { name: "Mago Negro Ilusionista" },
    { name: "Mago Negro Rei" },
    { name: "Grão-Mago Sombrio" },
    { name: "Mago Negro Mutante" },
    { name: "Mago Negro Assassino" },
    { name: "Mago Negro Sanguinário" },
    { name: "Alquimista Negro" },
    { name: "Mago Negro Venenoso" },
    { name: "Feiticeiro Metálico" },
    { name: "Mago Negro de Cristal" },
    { name: "Mago Negro Espectral" },
    { name: "Mago Corrompido" },
    { name: "Senhor dos Grimórios" },
    { name: "Mago Negro Cego" },
    { name: "Mago Negro Dourado" },
    { name: "Mago Negro das Cavernas" },
    { name: "Mago Abissal" },
    { name: "Cultista Sombrio" },
    { name: "Mago Herege" },
    { name: "Bruxo Ancestral" },
    { name: "Mago Negro Ágil" },
    { name: "Mestre das Maldições" },
    { name: "炎の黒魔道士 (Honoo no Kuromadoushi)", translation: "Mago Negro de Fogo" },
    { name: "氷の黒魔道士 (Koori no Kuromadoushi)", translation: "Mago Negro de Gelo" },
    { name: "雷の黒魔道士 (Kaminari no Kuromadoushi)", translation: "Mago Negro do Trovão" },
    { name: "大黒魔道士 (Dai Kuromadoushi)", translation: "Grande Mago Negro" }
  ],
  "Golem de Fogo": [
    { name: "Fornalha Ambulante" },
    { name: "Gigante de Lava" },
    { name: "Queimador de Mundos" },
    { name: "Golem Incandescente" },
    { name: "Sentinela de Magma" },
    { name: "Brasa Viva" },
    { name: "炎の巨人 (Honoo no Kyojin)", translation: "Titã de Fogo" },
    { name: "Fúria Vulcânica" },
    { name: "Núcleo Ardente" },
    { name: "Estátua Flamejante" },
    { name: "Golem de Fogo Azul" },
    { name: "Golem de Lava Sombria" },
    { name: "Golem Rei do Fogo" },
    { name: "Golem de Fogo Colossal" },
    { name: "Golem Metálico Derretido" },
    { name: "Golem de Fogo Sanguinário" },
    { name: "Golem de Fogo Assassino" },
    { name: "Golem de Fogo Venenoso" },
    { name: "Golem Ilusionista de Fogo" },
    { name: "Golem de Fogo Elétrico" },
    { name: "Golem de Fogo Dourado" },
    { name: "Golem Mutante Vulcânico" },
    { name: "Golem de Fogo Ancestral" },
    { name: "Golem Espectral de Fogo" },
    { name: "Golem de Fogo Eterno" },
    { name: "Senhor do Magma" },
    { name: "Coração Incandescente" },
    { name: "Golem de Fogo Espinhoso" },
    { name: "Golem de Cinzas" },
    { name: "Titã de Cristal de Fogo" },
    { name: "Golem de Fogo Instável" },
    { name: "Sentinela Solar" },
    { name: "Golem de Fogo Rápido" },
    { name: "Golem Erupção" },
    { name: "Guardião da Cratera" },
    { name: "Golem Ardente Supremo" },
    { name: "蒼炎の巨人 (Souen no Kyojin)", translation: "Gigante de Chama Azul" },
    { name: "暗黒炎の巨人 (Ankokuen no Kyojin)", translation: "Gigante de Chama Negra" },
    { name: "古代炎の巨人 (Kodai Honoo no Kyojin)", translation: "Gigante de Fogo Ancestral" },
    { name: "溶岩の魔像 (Yougan no Mazou)", translation: "Golem de Lava" }
  ],
  "Cavaleiro Fantasma": [
    { name: "Armadura Vazia" },
    { name: "Cavaleiro Sem Cabeça" },
    { name: "Espírito Templário" },
    { name: "Lâmina Gélida" },
    { name: "Defensor Morto-Vivo" },
    { name: "Paladino Caído" },
    { name: "幽霊騎士 (Yuurei Kishi)", translation: "Cavaleiro Espectral" },
    { name: "Sentinela Fantasmagórica" },
    { name: "Eco de Batalha" },
    { name: "Alma de Ferro" },
    { name: "Cavaleiro Fantasma de Fogo" },
    { name: "Cavaleiro Fantasma de Gelo" },
    { name: "Cavaleiro Fantasma Elétrico" },
    { name: "Cavaleiro Fantasma Sombrio" },
    { name: "Cavaleiro Fantasma Rei" },
    { name: "Cavaleiro Fantasma Gigante" },
    { name: "Cavaleiro Fantasma Mutante" },
    { name: "Cavaleiro Fantasma Assassino" },
    { name: "Cavaleiro Fantasma Sanguinário" },
    { name: "Cavaleiro Fantasma Metálico" },
    { name: "Cavaleiro Fantasma Venenoso" },
    { name: "Cavaleiro Fantasma Ilusionista" },
    { name: "Cavaleiro Fantasma Dourado" },
    { name: "Cavaleiro Fantasma de Cristal" },
    { name: "Senhor dos Cavaleiros Mortos" },
    { name: "Cavaleiro Fantasma Ancestral" },
    { name: "Cavaleiro da Lâmina Amaldiçoada" },
    { name: "Cavaleiro Fantasma Arqueiro" },
    { name: "Cavaleiro Fantasma Escudeiro" },
    { name: "Cavaleiro Fantasma Rastejante" },
    { name: "Paladino Espectral Corrompido" },
    { name: "Cavaleiro das Sombras" },
    { name: "Sentinela do Túmulo" },
    { name: "Cavaleiro Fantasma Cego" },
    { name: "Espada Assombrada" },
    { name: "Cavaleiro do Caos Fantasma" },
    { name: "炎の幽霊騎士 (Honoo no Yuurei Kishi)", translation: "Cavaleiro Fantasma de Fogo" },
    { name: "氷の幽霊騎士 (Koori no Yuurei Kishi)", translation: "Cavaleiro Fantasma de Gelo" },
    { name: "黄金の幽霊騎士 (Ougon no Yuurei Kishi)", translation: "Cavaleiro Fantasma Dourado" },
    { name: "闇の騎士 (Yami no Kishi)", translation: "Cavaleiro das Trevas" }
  ],
  "Orc Guerreiro": [
    { name: "Orc Sangrento" },
    { name: "Líder da Horda" },
    { name: "Pele-Verde Feroz" },
    { name: "Machado Cego" },
    { name: "Orc Esmagador" },
    { name: "Berserker Selvagem" },
    { name: "豚鬼 (Butaoni)", translation: "Demônio Porco" },
    { name: "Matador de Elfos" },
    { name: "Campeão da Tribo" },
    { name: "Grito de Guerra Orc" },
    { name: "Orc de Fogo" },
    { name: "Orc de Gelo" },
    { name: "Orc Sombrio" },
    { name: "Orc Guerreiro Blindado" },
    { name: "Orc Guerreiro Rei" },
    { name: "Orc Guerreiro Gigante" },
    { name: "Orc Guerreiro Assassino" },
    { name: "Orc Guerreiro Mutante" },
    { name: "Orc Guerreiro Metálico" },
    { name: "Orc Guerreiro Venenoso" },
    { name: "Orc Guerreiro Ilusionista" },
    { name: "Orc Guerreiro Elétrico" },
    { name: "Orc Guerreiro Dourado" },
    { name: "Orc Guerreiro de Cristal" },
    { name: "Orc Arqueiro" },
    { name: "Orc Xamã" },
    { name: "Orc Espectral" },
    { name: "Orc Guerreiro Ancestral" },
    { name: "Senhor da Horda Orc" },
    { name: "Orc Berserker Sanguinário" },
    { name: "Orc Cavaleiro de Lobo" },
    { name: "Orc Guerreiro Corrompido" },
    { name: "Orc Guerreiro do Deserto" },
    { name: "Orc Guerreiro do Pântano" },
    { name: "Orc Guerreiro de Magma" },
    { name: "Orc Guerreiro Caolho" },
    { name: "炎豚鬼 (Honoo Butaoni)", translation: "Orc de Fogo" },
    { name: "氷豚鬼 (Koori Butaoni)", translation: "Orc de Gelo" },
    { name: "鉄豚鬼 (Tetsu Butaoni)", translation: "Orc de Ferro" },
    { name: "大豚鬼 (Dai Butaoni)", translation: "Grande Orc" }
  ],
  "Urso Feroz": [
    { name: "Urso-Coruja" },
    { name: "Patas de Chumbo" },
    { name: "Devorador de Mel" },
    { name: "Abraço de Urso" },
    { name: "Besta Parda" },
    { name: "Defensor da Floresta" },
    { name: "凶熊 (Kyouguma)", translation: "Urso Assassino" },
    { name: "Fúria Hibernal" },
    { name: "Monstro Felpudo" },
    { name: "Urso Primordial" },
    { name: "Urso de Fogo" },
    { name: "Urso de Gelo" },
    { name: "Urso Elétrico" },
    { name: "Urso Sombrio" },
    { name: "Urso Rei" },
    { name: "Urso Gigante" },
    { name: "Urso Blindado" },
    { name: "Urso Sanguinário" },
    { name: "Urso Mutante" },
    { name: "Urso Assassino" },
    { name: "Urso Metálico" },
    { name: "Urso Venenoso" },
    { name: "Urso Ilusionista" },
    { name: "Urso Dourado" },
    { name: "Urso de Cristal" },
    { name: "Urso Espectral" },
    { name: "Urso Ancestral" },
    { name: "Senhor dos Ursos" },
    { name: "Urso Polar Furioso" },
    { name: "Urso do Pântano" },
    { name: "Urso de Magma" },
    { name: "Urso Cego" },
    { name: "Urso Corrompido" },
    { name: "Urso Caçador" },
    { name: "Urso Guerreiro Bípede" },
    { name: "Urso Fantasma" },
    { name: "炎熊 (Honooguma)", translation: "Urso de Fogo" },
    { name: "氷熊 (Kooriguma)", translation: "Urso de Gelo" },
    { name: "鉄熊 (Tetsuguma)", translation: "Urso de Ferro" },
    { name: "魔熊 (Maguma)", translation: "Urso Demoníaco" }
  ],
  "Wyvern": [
    { name: "Dragão Falso" },
    { name: "Cuspidor de Veneno" },
    { name: "Asas de Morcego Escamoso" },
    { name: "Caçador das Montanhas" },
    { name: "Lagarto Alado" },
    { name: "Wyvern Rastejante" },
    { name: "飛竜 (Hiryuu)", translation: "Dragão Voador" },
    { name: "Terror dos Céus" },
    { name: "Predador Escamoso" },
    { name: "Serpente com Asas" },
    { name: "Wyvern de Fogo" },
    { name: "Wyvern de Gelo" },
    { name: "Wyvern do Trovão" },
    { name: "Wyvern Sombrio" },
    { name: "Wyvern Rei" },
    { name: "Wyvern Colossal" },
    { name: "Wyvern Blindado" },
    { name: "Wyvern Sanguinário" },
    { name: "Wyvern Mutante" },
    { name: "Wyvern Assassino" },
    { name: "Wyvern Metálico" },
    { name: "Wyvern Tóxico" },
    { name: "Wyvern Ilusionista" },
    { name: "Wyvern Dourado" },
    { name: "Wyvern de Cristal" },
    { name: "Wyvern Espectral" },
    { name: "Wyvern Ancestral" },
    { name: "Wyvern de Magma" },
    { name: "Wyvern Corrompido" },
    { name: "Wyvern do Deserto" },
    { name: "Senhor dos Wyverns" },
    { name: "Wyvern das Cavernas" },
    { name: "Wyvern Voador Veloz" },
    { name: "Wyvern Cego" },
    { name: "Wyvern do Pântano Negro" },
    { name: "Wyvern de Duas Cabeças" },
    { name: "炎飛竜 (Honoo Hiryuu)", translation: "Wyvern de Fogo" },
    { name: "氷飛竜 (Koori Hiryuu)", translation: "Wyvern de Gelo" },
    { name: "雷飛竜 (Ikazuchi Hiryuu)", translation: "Wyvern do Trovão" },
    { name: "暗黒飛竜 (Ankoku Hiryuu)", translation: "Wyvern Sombrio" }
  ],
  "Quimera": [
    { name: "Besta Misturada" },
    { name: "Leão-Cabra-Cobra" },
    { name: "Aberração Mágica" },
    { name: "Experimento Falho" },
    { name: "Mutante Selvagem" },
    { name: "Três Cabeças" },
    { name: "合成獣 (Gouseijuu)", translation: "Besta Sintética" },
    { name: "Fúria Polimórfica" },
    { name: "Terror da Alquimia" },
    { name: "Aberração de Sangue" },
    { name: "Quimera de Fogo" },
    { name: "Quimera de Gelo" },
    { name: "Quimera Elétrica" },
    { name: "Quimera Sombria" },
    { name: "Quimera Rei" },
    { name: "Quimera Gigante" },
    { name: "Quimera Blindada" },
    { name: "Quimera Assassina" },
    { name: "Quimera Metálica" },
    { name: "Quimera Venenosa" },
    { name: "Quimera Ilusionista" },
    { name: "Quimera Dourada" },
    { name: "Quimera de Cristal" },
    { name: "Quimera Espectral" },
    { name: "Quimera Ancestral" },
    { name: "Quimera de Magma" },
    { name: "Quimera Corrompida" },
    { name: "Mestra das Quimeras" },
    { name: "Quimera do Deserto" },
    { name: "Quimera do Pântano" },
    { name: "Quimera Perfeita" },
    { name: "Besta Alquímica Suprema" },
    { name: "Quimera de Duas Cabeças" },
    { name: "Quimera Voadora" },
    { name: "Quimera Rastejante" },
    { name: "Quimera Selvagem Sanguinária" },
    { name: "炎合成獣 (Honoo Gouseijuu)", translation: "Quimera de Fogo" },
    { name: "氷合成獣 (Koori Gouseijuu)", translation: "Quimera de Gelo" },
    { name: "雷合成獣 (Ikazuchi Gouseijuu)", translation: "Quimera do Trovão" },
    { name: "闇合成獣 (Yami Gouseijuu)", translation: "Quimera Sombria" }
  ],
  "Basilisco": [
    { name: "Rei das Cobras" },
    { name: "Olhar Petrificante" },
    { name: "Lagarto Venenoso" },
    { name: "Rastejador Mortal" },
    { name: "Escamas de Pedra" },
    { name: "Serpente de Fogo" },
    { name: "邪視のトカゲ (Jashi no Tokage)", translation: "Lagarto de Olho Maligno" },
    { name: "Transformador em Pedra" },
    { name: "Basilisco Ancestral" },
    { name: "Olhos da Morte" },
    { name: "Basilisco de Fogo" },
    { name: "Basilisco de Gelo" },
    { name: "Basilisco Elétrico" },
    { name: "Basilisco Sombrio" },
    { name: "Basilisco Rei Supremo" },
    { name: "Basilisco Gigante" },
    { name: "Basilisco Blindado" },
    { name: "Basilisco Assassino" },
    { name: "Basilisco Metálico" },
    { name: "Basilisco Super Venenoso" },
    { name: "Basilisco Ilusionista" },
    { name: "Basilisco Dourado" },
    { name: "Basilisco de Cristal" },
    { name: "Basilisco Espectral" },
    { name: "Basilisco Mutante" },
    { name: "Basilisco de Magma" },
    { name: "Basilisco Corrompido" },
    { name: "Basilisco do Deserto" },
    { name: "Basilisco do Pântano" },
    { name: "Olhar de Prata" },
    { name: "Basilisco Voador" },
    { name: "Basilisco de Duas Cabeças" },
    { name: "Basilisco Cego" },
    { name: "Rei Basilisco das Cavernas" },
    { name: "Lagarto do Fim" },
    { name: "Rastejador Petrificante Rápido" },
    { name: "炎邪視 (Honoo Jashi)", translation: "Olho Maligno de Fogo" },
    { name: "氷邪視 (Koori Jashi)", translation: "Olho Maligno de Gelo" },
    { name: "雷邪視 (Ikazuchi Jashi)", translation: "Olho Maligno do Trovão" },
    { name: "石化王 (Sekika-ou)", translation: "Rei da Petrificação" }
  ],
  "Behemoth": [
    { name: "Besta do Apocalipse" },
    { name: "Rei das Feras" },
    { name: "Pisada Terremoto" },
    { name: "Esmagador de Montanhas" },
    { name: "Chifres Colossais" },
    { name: "Monstro Inabalável" },
    { name: "巨獣 (Kyojuu)", translation: "Besta Gigante" },
    { name: "Tanque Vivo" },
    { name: "Força da Natureza" },
    { name: "Behemoth Furioso" },
    { name: "Behemoth de Fogo" },
    { name: "Behemoth de Gelo" },
    { name: "Behemoth Elétrico" },
    { name: "Behemoth Sombrio" },
    { name: "Behemoth Imperador" },
    { name: "Behemoth Titânico" },
    { name: "Behemoth Blindado" },
    { name: "Behemoth Assassino" },
    { name: "Behemoth Metálico" },
    { name: "Behemoth Venenoso" },
    { name: "Behemoth Ilusionista" },
    { name: "Behemoth Dourado" },
    { name: "Behemoth de Cristal" },
    { name: "Behemoth Espectral" },
    { name: "Behemoth Ancestral" },
    { name: "Behemoth Mutante" },
    { name: "Behemoth de Magma" },
    { name: "Behemoth Corrompido" },
    { name: "Behemoth do Deserto" },
    { name: "Behemoth das Profundezas" },
    { name: "Rei Behemoth Primordial" },
    { name: "Besta Terremoto Sanguinária" },
    { name: "Behemoth Selvagem" },
    { name: "Behemoth Cego" },
    { name: "Esmagador de Reinos" },
    { name: "Senhor das Bestas Gigantes" },
    { name: "炎巨獣 (Honoo Kyojuu)", translation: "Besta Gigante de Fogo" },
    { name: "氷巨獣 (Koori Kyojuu)", translation: "Besta Gigante de Gelo" },
    { name: "鋼巨獣 (Hagane Kyojuu)", translation: "Besta Gigante de Aço" },
    { name: "暗黒巨獣 (Ankoku Kyojuu)", translation: "Besta Gigante Sombria" }
  ],
  "Cavaleiro das Trevas": [
    { name: "Espada Negra" },
    { name: "Senhor dos Vampiros" },
    { name: "Terror Encouraçado" },
    { name: "Executor Sombrio" },
    { name: "Guardião do Abismo" },
    { name: "Lâmina Amaldiçoada" },
    { name: "暗黒騎士 (Ankoku Kishi)", translation: "Cavaleiro Sombrio" },
    { name: "Mestre do Medo" },
    { name: "Sem Piedade" },
    { name: "Tirano de Aço" },
    { name: "Cavaleiro das Trevas de Fogo" },
    { name: "Cavaleiro das Trevas de Gelo" },
    { name: "Cavaleiro das Trevas Elétrico" },
    { name: "Senhor Cavaleiro das Trevas" },
    { name: "Cavaleiro das Trevas Gigante" },
    { name: "Cavaleiro das Trevas Mutante" },
    { name: "Cavaleiro das Trevas Assassino" },
    { name: "Cavaleiro das Trevas Metálico" },
    { name: "Cavaleiro das Trevas Venenoso" },
    { name: "Cavaleiro das Trevas Ilusionista" },
    { name: "Cavaleiro das Trevas Dourado" },
    { name: "Cavaleiro das Trevas de Cristal" },
    { name: "Cavaleiro das Trevas Espectral" },
    { name: "Cavaleiro das Trevas Ancestral" },
    { name: "Cavaleiro das Trevas de Magma" },
    { name: "Cavaleiro das Trevas Corrompido" },
    { name: "Lâmina Negra Sedenta" },
    { name: "Executor do Caos" },
    { name: "Paladino Negro Cego" },
    { name: "Guardião Sombrio Supremo" },
    { name: "Cavaleiro das Trevas Rastejante" },
    { name: "Cavaleiro Abissal Arqueiro" },
    { name: "Cavaleiro do Purgatório" },
    { name: "Mestre da Armadura Negra" },
    { name: "Vingador Sombrio" },
    { name: "Cavaleiro do Fim" },
    { name: "炎の暗黒騎士 (Honoo no Ankoku Kishi)", translation: "Cavaleiro Sombrio de Fogo" },
    { name: "氷の暗黒騎士 (Koori no Ankoku Kishi)", translation: "Cavaleiro Sombrio de Gelo" },
    { name: "雷の暗黒騎士 (Kaminari no Ankoku Kishi)", translation: "Cavaleiro Sombrio do Trovão" },
    { name: "真暗黒騎士 (Shin Ankoku Kishi)", translation: "Verdadeiro Cavaleiro Sombrio" }
  ],
  "Kraken": [
    { name: "Terror dos Mares" },
    { name: "Lula Gigante" },
    { name: "Devorador de Navios" },
    { name: "Tentáculos da Profundeza" },
    { name: "Monstro do Abismo" },
    { name: "Senhor das Marés" },
    { name: "海の悪魔 (Umi no Akuma)", translation: "Demônio do Mar" },
    { name: "Abraço Afogado" },
    { name: "Olho do Oceano" },
    { name: "Kraken Ancião" },
    { name: "Kraken de Fogo" },
    { name: "Kraken de Gelo" },
    { name: "Kraken Elétrico" },
    { name: "Kraken Sombrio" },
    { name: "Kraken Rei" },
    { name: "Kraken Colossal" },
    { name: "Kraken Mutante" },
    { name: "Kraken Assassino" },
    { name: "Kraken Blindado" },
    { name: "Kraken Metálico" },
    { name: "Kraken Venenoso" },
    { name: "Kraken Ilusionista" },
    { name: "Kraken Dourado" },
    { name: "Kraken de Cristal" },
    { name: "Kraken Espectral" },
    { name: "Kraken de Magma" },
    { name: "Kraken Corrompido" },
    { name: "Senhor dos Tentáculos" },
    { name: "Kraken Abissal Cego" },
    { name: "Kraken Mutante Acelerado" },
    { name: "Lula Assassina Gigante" },
    { name: "O Grande Afogador" },
    { name: "Kraken Sanguinário" },
    { name: "Besta das Fossas Marianas" },
    { name: "Kraken Espinhoso" },
    { name: "Terror Marinho Supremo" },
    { name: "炎の海魔 (Honoo no Umi Akuma)", translation: "Demônio Marinho de Fogo" },
    { name: "氷の海魔 (Koori no Umi Akuma)", translation: "Demônio Marinho de Gelo" },
    { name: "雷の海魔 (Kaminari no Umi Akuma)", translation: "Demônio Marinho do Trovão" },
    { name: "大王烏賊 (Daiou Ika)", translation: "Grande Rei Lula" }
  ],
  "Hidra": [
    { name: "Besta de Várias Cabeças" },
    { name: "Cabeças Imortais" },
    { name: "Regeneradora de Veneno" },
    { name: "Pesadelo do Pântano" },
    { name: "Serpente Multiplicadora" },
    { name: "Hidra Cuspidora" },
    { name: "多頭蛇 (Tatouda)", translation: "Serpente de Muitas Cabeças" },
    { name: "Terror Tóxico" },
    { name: "Fúria Escamosa" },
    { name: "Hidra de Lerna" },
    { name: "Hidra de Fogo" },
    { name: "Hidra de Gelo" },
    { name: "Hidra Elétrica" },
    { name: "Hidra Sombria" },
    { name: "Hidra Rei Supremo" },
    { name: "Hidra Colossal" },
    { name: "Hidra Mutante" },
    { name: "Hidra Assassina" },
    { name: "Hidra Blindada" },
    { name: "Hidra Metálica" },
    { name: "Hidra Super Venenosa" },
    { name: "Hidra Ilusionista" },
    { name: "Hidra Dourada" },
    { name: "Hidra de Cristal" },
    { name: "Hidra Espectral" },
    { name: "Hidra Ancestral" },
    { name: "Hidra de Magma" },
    { name: "Hidra Corrompida" },
    { name: "Senhora das Cabeças" },
    { name: "Hidra do Deserto" },
    { name: "Hidra Cega" },
    { name: "Hidra Voadora" },
    { name: "Hidra Rastejante Veloz" },
    { name: "Hidra Sanguinária" },
    { name: "Terror Multi-cabeças" },
    { name: "Hidra Mística das Cavernas" },
    { name: "炎多頭蛇 (Honoo Tatouda)", translation: "Hidra de Fogo" },
    { name: "氷多頭蛇 (Koori Tatouda)", translation: "Hidra de Gelo" },
    { name: "雷多頭蛇 (Ikazuchi Tatouda)", translation: "Hidra do Trovão" },
    { name: "暗黒多頭蛇 (Ankoku Tatouda)", translation: "Hidra Sombria" }
  ],
  "Dragão": [
    { name: "Lagarto que Cospe Fogo" },
    { name: "Dragão Preguiçoso" },
    { name: "Sombra das Nuvens" },
    { name: "Asa da destruição" },
    { name: "Terror dos Céus" },
    { name: "Dragão de Cobre" },
    { name: "竜 (Ryuu)", translation: "Dragão Rei" },
    { name: "Senhor das Chamas" },
    { name: "Wyrm Esmeralda" },
    { name: "Dragão de Ouro" },
    { name: "Dragão de Fogo Supremo" },
    { name: "Dragão de Gelo" },
    { name: "Dragão do Trovão" },
    { name: "Dragão das Sombras" },
    { name: "Rei Dragão" },
    { name: "Dragão Colossal" },
    { name: "Dragão Mutante" },
    { name: "Dragão Assassino" },
    { name: "Dragão Metálico Blindado" },
    { name: "Dragão Venenoso" },
    { name: "Dragão Ilusionista" },
    { name: "Dragão de Prata" },
    { name: "Dragão de Cristal" },
    { name: "Dragão Espectral" },
    { name: "Dragão Ancestral" },
    { name: "Dragão de Magma" },
    { name: "Dragão Corrompido" },
    { name: "Senhor dos Wyrms" },
    { name: "Dragão do Deserto" },
    { name: "Dragão Cego" },
    { name: "Dragão Rastejante" },
    { name: "Dragão Sanguinário" },
    { name: "Dragão de Diamante" },
    { name: "Dragão das Tempestades" },
    { name: "Dragão de Quatro Olhos" },
    { name: "Dragão Infernal" },
    { name: "炎竜 (Honoo Ryuu)", translation: "Dragão de Fogo" },
    { name: "氷竜 (Koori Ryuu)", translation: "Dragão de Gelo" },
    { name: "雷竜 (Kaminari Ryuu)", translation: "Dragão do Trovão" },
    { name: "暗黒竜 (Ankoku Ryuu)", translation: "Dragão Sombrio" }
  ],
  "Lich": [
    { name: "Rei dos Mortos" },
    { name: "Mago Esqueleto" },
    { name: "Senhor Necromante" },
    { name: "Alma Filactéria" },
    { name: "Bruxo Imortal" },
    { name: "Feiticeiro Decrépito" },
    { name: "不死の王 (Fushi no Ou)", translation: "Rei Imortal" },
    { name: "Mestre dos Zumbis" },
    { name: "Lich Ancião" },
    { name: "Guardião das Almas" },
    { name: "Lich de Fogo" },
    { name: "Lich de Gelo" },
    { name: "Lich do Trovão" },
    { name: "Lich Sombrio" },
    { name: "Lich Imperador" },
    { name: "Lich Gigante" },
    { name: "Lich Mutante" },
    { name: "Lich Assassino" },
    { name: "Lich Sanguinário" },
    { name: "Lich Metálico" },
    { name: "Lich Venenoso" },
    { name: "Lich Ilusionista" },
    { name: "Lich Dourado" },
    { name: "Lich de Cristal" },
    { name: "Lich Espectral" },
    { name: "Lich de Magma" },
    { name: "Lich Corrompido" },
    { name: "Grão-Lich" },
    { name: "Senhor dos Filactérios" },
    { name: "Lich Cego" },
    { name: "Bruxo Imortal Enlouquecido" },
    { name: "Lich Cultista" },
    { name: "Lich da Tumba Negra" },
    { name: "Arauto dos Mortos" },
    { name: "Necromante Supremo" },
    { name: "Senhor das Sombras Etéreas" },
    { name: "炎の死王 (Honoo no Shiou)", translation: "Rei Morto de Fogo" },
    { name: "氷の死王 (Koori no Shiou)", translation: "Rei Morto de Gelo" },
    { name: "雷の死王 (Kaminari no Shiou)", translation: "Rei Morto do Trovão" },
    { name: "大死王 (Daishiou)", translation: "Grande Rei Morto" }
  ],
  "Anjo Caído": [
    { name: "Asas Negras" },
    { name: "Querubim Corrompido" },
    { name: "Serafim Desterrado" },
    { name: "Luz Obscurecida" },
    { name: "Portador do Pecado" },
    { name: "Santo Caído" },
    { name: "堕天使 (Datenshi)", translation: "Anjo das Trevas" },
    { name: "Penas de Sangue" },
    { name: "Vingador Divino" },
    { name: "Anjo do Apocalipse" },
    { name: "Anjo Caído de Fogo" },
    { name: "Anjo Caído de Gelo" },
    { name: "Anjo Caído Elétrico" },
    { name: "Arcanjo Sombrio" },
    { name: "Príncipe Caído" },
    { name: "Anjo Caído Gigante" },
    { name: "Anjo Caído Mutante" },
    { name: "Anjo Caído Assassino" },
    { name: "Anjo Caído Metálico" },
    { name: "Anjo Caído Venenoso" },
    { name: "Anjo Caído Ilusionista" },
    { name: "Anjo Caído Dourado" },
    { name: "Anjo Caído de Cristal" },
    { name: "Anjo Caído Espectral" },
    { name: "Anjo Caído Ancestral" },
    { name: "Anjo Caído de Magma" },
    { name: "Anjo Corrompido Supremo" },
    { name: "Senhor dos Caídos" },
    { name: "Anjo Caído Cego" },
    { name: "Penas de Prata Escura" },
    { name: "Mensageiro da Perdição" },
    { name: "Serafim do Caos" },
    { name: "Querubim Sangrento" },
    { name: "Anjo do Abismo" },
    { name: "Voz do Inferno" },
    { name: "Guardião Caído" },
    { name: "炎の堕天使 (Honoo no Datenshi)", translation: "Anjo Caído de Fogo" },
    { name: "氷の堕天使 (Koori no Datenshi)", translation: "Anjo Caído de Gelo" },
    { name: "鋼の堕天使 (Hagane no Datenshi)", translation: "Anjo Caído de Aço" },
    { name: "大堕天使 (Dai Datenshi)", translation: "Grande Anjo Caído" }
  ],
  "Dragão Ancião": [
    { name: "Avô dos Dragões" },
    { name: "Sábio Escamoso" },
    { name: "Guardião do Tempo" },
    { name: "Respiração Cósmica" },
    { name: "Asas de Galáxia" },
    { name: "Dragão Milenar" },
    { name: "古竜 (Koryuu)", translation: "Dragão Antigo" },
    { name: "Soberano dos Céus" },
    { name: "Protetor do Mundo" },
    { name: "Dragão Primordial" },
    { name: "Dragão Ancião de Fogo" },
    { name: "Dragão Ancião de Gelo" },
    { name: "Dragão Ancião do Trovão" },
    { name: "Dragão Ancião Sombrio" },
    { name: "Dragão Rei Ancião" },
    { name: "Dragão Ancião Colossal" },
    { name: "Dragão Ancião Mutante" },
    { name: "Dragão Ancião Assassino" },
    { name: "Dragão Ancião Blindado" },
    { name: "Dragão Ancião Venenoso" },
    { name: "Dragão Ancião Ilusionista" },
    { name: "Dragão Ancião Dourado" },
    { name: "Dragão Ancião de Cristal" },
    { name: "Dragão Ancião Espectral" },
    { name: "Deus Dragão Ancião" },
    { name: "Dragão Ancião de Magma" },
    { name: "Dragão Ancião Corrompido" },
    { name: "Senhor Dragão Primordial" },
    { name: "Dragão Ancião Cego" },
    { name: "Dragão Ancião do Deserto" },
    { name: "Dragão Ancião Rastejante" },
    { name: "Sábio Dragão das Estrelas" },
    { name: "Guardião Milenar" },
    { name: "Dragão Mestre Escamoso" },
    { name: "Wyrm Primordial Supremo" },
    { name: "A Voz do Tempo" },
    { name: "炎の古竜 (Honoo no Koryuu)", translation: "Dragão Antigo de Fogo" },
    { name: "氷の古竜 (Koori no Koryuu)", translation: "Dragão Antigo de Gelo" },
    { name: "雷の古竜 (Kaminari no Koryuu)", translation: "Dragão Antigo do Trovão" },
    { name: "暗黒古竜 (Ankoku Koryuu)", translation: "Dragão Antigo Sombrio" }
  ],
  "Ceifador": [
    { name: "A Morte em Pessoa" },
    { name: "Foice Sombria" },
    { name: "Colecionador de Almas" },
    { name: "Capuz Negro" },
    { name: "Senhor do Fim" },
    { name: "Sussurro Fúnebre" },
    { name: "死神 (Shinigami)", translation: "Deus da Morte" },
    { name: "Ceifador de Vidas" },
    { name: "Sombra Condenadora" },
    { name: "O Único Destino" },
    { name: "Ceifador de Fogo" },
    { name: "Ceifador de Gelo" },
    { name: "Ceifador Elétrico" },
    { name: "Grão-Ceifador Sombrio" },
    { name: "Rei Ceifador" },
    { name: "Ceifador Gigante" },
    { name: "Ceifador Mutante" },
    { name: "Ceifador Assassino Silencioso" },
    { name: "Ceifador Sanguinário" },
    { name: "Ceifador Metálico" },
    { name: "Ceifador Venenoso" },
    { name: "Ceifador Ilusionista" },
    { name: "Ceifador Dourado" },
    { name: "Ceifador de Cristal" },
    { name: "Ceifador Espectral" },
    { name: "Ceifador Ancestral" },
    { name: "Ceifador de Magma" },
    { name: "Ceifador Corrompido" },
    { name: "Senhor das Foices" },
    { name: "Ceifador Cego" },
    { name: "Ceifador Escondido" },
    { name: "Portador do Destino" },
    { name: "Arauto do Juízo" },
    { name: "Julgador de Almas" },
    { name: "Ceifador Escarlate" },
    { name: "Mestre da Morte" },
    { name: "炎の死神 (Honoo no Shinigami)", translation: "Deus da Morte de Fogo" },
    { name: "氷の死神 (Koori no Shinigami)", translation: "Deus da Morte de Gelo" },
    { name: "雷の死神 (Kaminari no Shinigami)", translation: "Deus da Morte do Trovão" },
    { name: "大死神 (Daishinigami)", translation: "Grande Deus da Morte" }
  ],
  "Titã": [
    { name: "Colosso de Carne" },
    { name: "Esmagador de Deuses" },
    { name: "Titã Desperto" },
    { name: "Gigante Ancestral" },
    { name: "Passos de Terremoto" },
    { name: "Senhor da Terra" },
    { name: "巨人 (Kyojin)", translation: "Gigante Titânico" },
    { name: "Força Absoluta" },
    { name: "Monólito Vivo" },
    { name: "Conquistador de Mundos" },
    { name: "Titã de Fogo" },
    { name: "Titã de Gelo" },
    { name: "Titã Elétrico" },
    { name: "Titã Sombrio" },
    { name: "Imperador Titã" },
    { name: "Titã Colossal Supremo" },
    { name: "Titã Blindado" },
    { name: "Titã Mutante" },
    { name: "Titã Metálico" },
    { name: "Titã Sanguinário" },
    { name: "Titã Ilusionista" },
    { name: "Titã Dourado" },
    { name: "Titã de Cristal" },
    { name: "Titã Espectral" },
    { name: "Titã Ancestral Primordial" },
    { name: "Titã de Magma" },
    { name: "Titã Corrompido" },
    { name: "Titã Venenoso" },
    { name: "Senhor dos Titãs" },
    { name: "Titã Cego" },
    { name: "Esmagador de Estrelas" },
    { name: "Colosso do Tártaro" },
    { name: "Titã de Adamantium" },
    { name: "Montanha que Caminha" },
    { name: "Titã Guerreiro" },
    { name: "Gigante do Cataclismo" },
    { name: "炎の巨人 (Honoo no Kyojin)", translation: "Titã de Fogo" },
    { name: "氷の巨人 (Koori no Kyojin)", translation: "Titã de Gelo" },
    { name: "雷の巨人 (Kaminari no Kyojin)", translation: "Titã do Trovão" },
    { name: "暗黒の巨人 (Ankoku no Kyojin)", translation: "Titã Sombrio" }
  ],
  "Dragão do Vazio": [
    { name: "Devorador de Estrelas" },
    { name: "Buraco Negro Alado" },
    { name: "Entidade Cósmica" },
    { name: "Respiração de Antimatéria" },
    { name: "Dragão Nebuloso" },
    { name: "Ameaça Galáctica" },
    { name: "虚無竜 (Kyomuryuu)", translation: "Dragão do Nada" },
    { name: "Sombra do Espaço" },
    { name: "O Fim do Tempo" },
    { name: "Besta do Horizonte" },
    { name: "Dragão do Vazio de Fogo" },
    { name: "Dragão do Vazio de Gelo" },
    { name: "Dragão do Vazio Elétrico" },
    { name: "Dragão do Vazio Sombrio" },
    { name: "Rei Dragão do Vazio" },
    { name: "Dragão do Vazio Colossal" },
    { name: "Dragão do Vazio Blindado" },
    { name: "Dragão do Vazio Mutante" },
    { name: "Dragão do Vazio Metálico" },
    { name: "Dragão do Vazio Venenoso" },
    { name: "Dragão do Vazio Ilusionista" },
    { name: "Dragão do Vazio Dourado" },
    { name: "Dragão do Vazio de Cristal" },
    { name: "Dragão do Vazio Espectral" },
    { name: "Dragão do Vazio Ancestral" },
    { name: "Dragão do Vazio de Magma" },
    { name: "Dragão do Vazio Corrompido" },
    { name: "Senhor do Nada" },
    { name: "Dragão do Vazio Cego" },
    { name: "Nebulosa Negra" },
    { name: "Cometa Devorador" },
    { name: "Fenda Espacial" },
    { name: "Wyrm Estelar" },
    { name: "Horizonte de Eventos" },
    { name: "Respiração de Quasar" },
    { name: "Singularidade Alada" },
    { name: "炎虚無竜 (Honoo Kyomuryuu)", translation: "Dragão do Nada de Fogo" },
    { name: "氷虚無竜 (Koori Kyomuryuu)", translation: "Dragão do Nada de Gelo" },
    { name: "雷虚無竜 (Kaminari Kyomuryuu)", translation: "Dragão do Nada do Trovão" },
    { name: "真虚無竜 (Shin Kyomuryuu)", translation: "Verdadeiro Dragão do Nada" }
  ],
  "Rei Demônio": [
    { name: "Soberano do Inferno" },
    { name: "Tirano Demoníaco" },
    { name: "Chifres da Ruína" },
    { name: "Liderança Profana" },
    { name: "Mestre do Caos" },
    { name: "Imperador das Trevas" },
    { name: "魔王 (Maou)", translation: "Rei dos Demônios" },
    { name: "Senhor da Destruição" },
    { name: "Mal Encarnado" },
    { name: "O Antagonista" },
    { name: "Rei Demônio de Fogo" },
    { name: "Rei Demônio de Gelo" },
    { name: "Rei Demônio Elétrico" },
    { name: "Rei Demônio das Sombras" },
    { name: "Grão-Rei Demônio" },
    { name: "Rei Demônio Gigante" },
    { name: "Rei Demônio Blindado" },
    { name: "Rei Demônio Assassino" },
    { name: "Rei Demônio Metálico" },
    { name: "Rei Demônio Venenoso" },
    { name: "Rei Demônio Ilusionista" },
    { name: "Rei Demônio Dourado" },
    { name: "Rei Demônio de Cristal" },
    { name: "Rei Demônio Espectral" },
    { name: "Rei Demônio Ancestral" },
    { name: "Rei Demônio de Magma" },
    { name: "Rei Demônio Corrompido" },
    { name: "Senhor dos Reis Demônios" },
    { name: "Rei Demônio Cego" },
    { name: "Rei Demônio Mutante" },
    { name: "Tirano do Abismo" },
    { name: "Soberano do Tártaro" },
    { name: "Arauto do Inferno" },
    { name: "Imperador do Fogo Fátuo" },
    { name: "Mestre das Hordas" },
    { name: "Besta Diabólica Suprema" },
    { name: "炎の魔王 (Honoo no Maou)", translation: "Rei Demônio de Fogo" },
    { name: "氷の魔王 (Koori no Maou)", translation: "Rei Demônio de Gelo" },
    { name: "雷の魔王 (Kaminari no Maou)", translation: "Rei Demônio do Trovão" },
    { name: "大魔王 (Daimaou)", translation: "Grande Rei Demônio" }
  ],
  "Avatar do Caos": [
    { name: "Tempestade de Entropia" },
    { name: "Forma Indescritível" },
    { name: "Loucura Encarnada" },
    { name: "Distorção de Realidade" },
    { name: "Arauto da Confusão" },
    { name: "Olhos Mutáveis" },
    { name: "混沌の化身 (Konton no Keshin)", translation: "Encarnação do Caos" },
    { name: "Mestre da Desordem" },
    { name: "Anomalia Viva" },
    { name: "Paradoxo Ambulante" },
    { name: "Avatar do Caos de Fogo" },
    { name: "Avatar do Caos de Gelo" },
    { name: "Avatar do Caos Elétrico" },
    { name: "Avatar do Caos Sombrio" },
    { name: "Avatar Supremo do Caos" },
    { name: "Avatar do Caos Gigante" },
    { name: "Avatar do Caos Blindado" },
    { name: "Avatar do Caos Mutante" },
    { name: "Avatar do Caos Metálico" },
    { name: "Avatar do Caos Venenoso" },
    { name: "Avatar do Caos Ilusionista" },
    { name: "Avatar do Caos Dourado" },
    { name: "Avatar do Caos de Cristal" },
    { name: "Avatar do Caos Espectral" },
    { name: "Avatar do Caos Ancestral" },
    { name: "Avatar do Caos de Magma" },
    { name: "Avatar do Caos Corrompido" },
    { name: "Senhor das Anomalias" },
    { name: "Avatar do Caos Cego" },
    { name: "Tempestade de Loucura" },
    { name: "Entidade Indecifrável" },
    { name: "Arauto do Limbo" },
    { name: "Fenda de Realidade" },
    { name: "Distorção Infinita" },
    { name: "O Imprevisível" },
    { name: "O Sem-Forma" },
    { name: "炎の混沌 (Honoo no Konton)", translation: "Caos de Fogo" },
    { name: "氷の混沌 (Koori no Konton)", translation: "Caos de Gelo" },
    { name: "雷の混沌 (Kaminari no Konton)", translation: "Caos do Trovão" },
    { name: "真の混沌 (Shin no Konton)", translation: "Verdadeiro Caos" }
  ],
  "Serpente do Mundo": [
    { name: "Ouroboros Infinito" },
    { name: "Jörmungandr" },
    { name: "Abraço Global" },
    { name: "Serpente que Circunda a Terra" },
    { name: "Escamas Oceânicas" },
    { name: "Devoradora de Continentes" },
    { name: "世界蛇 (Sekai Hebi)", translation: "Cobra Mundial" },
    { name: "Fim dos Tempos" },
    { name: "Guardiã do Horizonte" },
    { name: "Serpente Eterna" },
    { name: "Serpente do Mundo de Fogo" },
    { name: "Serpente do Mundo de Gelo" },
    { name: "Serpente do Mundo Elétrica" },
    { name: "Serpente do Mundo Sombria" },
    { name: "Serpente do Mundo Rei" },
    { name: "Serpente do Mundo Colossal" },
    { name: "Serpente do Mundo Blindada" },
    { name: "Serpente do Mundo Assassina" },
    { name: "Serpente do Mundo Metálica" },
    { name: "Serpente do Mundo Venenosa" },
    { name: "Serpente do Mundo Ilusionista" },
    { name: "Serpente do Mundo Dourada" },
    { name: "Serpente do Mundo de Cristal" },
    { name: "Serpente do Mundo Espectral" },
    { name: "Serpente do Mundo Ancestral" },
    { name: "Serpente do Mundo de Magma" },
    { name: "Serpente do Mundo Corrompida" },
    { name: "Serpente do Mundo Mutante" },
    { name: "Serpente do Mundo Cega" },
    { name: "Senhora dos Mares e Terras" },
    { name: "Anel Planetário" },
    { name: "Ouroboros Estelar" },
    { name: "Laço do Fim do Mundo" },
    { name: "Guardiã do Núcleo" },
    { name: "Serpente do Multiverso" },
    { name: "Devoradora de Mundos" },
    { name: "炎の世界蛇 (Honoo no Sekai Hebi)", translation: "Cobra Mundial de Fogo" },
    { name: "氷の世界蛇 (Koori no Sekai Hebi)", translation: "Cobra Mundial de Gelo" },
    { name: "雷の世界蛇 (Kaminari no Sekai Hebi)", translation: "Cobra Mundial do Trovão" },
    { name: "真の世界蛇 (Shin no Sekai Hebi)", translation: "Verdadeira Cobra Mundial" }
  ],
  "Arauto da Perdição": [
    { name: "Mensageiro do Fim" },
    { name: "Cometa de Sangue" },
    { name: "Previsão Ruim" },
    { name: "Cavaleiro do Apocalipse" },
    { name: "Voz do Abismo" },
    { name: "Despertador de Males" },
    { name: "破滅の使者 (Hametsu no Shisha)", translation: "Emissário da Ruína" },
    { name: "Estrela Cadente Negra" },
    { name: "Sinal do Juízo" },
    { name: "Portador da Morte" },
    { name: "Arauto da Perdição de Fogo" },
    { name: "Arauto da Perdição de Gelo" },
    { name: "Arauto da Perdição Elétrico" },
    { name: "Arauto da Perdição Sombrio" },
    { name: "Grão-Arauto" },
    { name: "Arauto da Perdição Gigante" },
    { name: "Arauto da Perdição Blindado" },
    { name: "Arauto da Perdição Assassino" },
    { name: "Arauto da Perdição Metálico" },
    { name: "Arauto da Perdição Venenoso" },
    { name: "Arauto da Perdição Ilusionista" },
    { name: "Arauto da Perdição Dourado" },
    { name: "Arauto da Perdição de Cristal" },
    { name: "Arauto da Perdição Espectral" },
    { name: "Arauto da Perdição Ancestral" },
    { name: "Arauto da Perdição de Magma" },
    { name: "Arauto da Perdição Corrompido" },
    { name: "Senhor do Apocalipse" },
    { name: "Arauto da Perdição Cego" },
    { name: "Arauto da Perdição Mutante" },
    { name: "O Profeta do Fim" },
    { name: "Trombeta da Destruição" },
    { name: "Cavaleiro do Caos" },
    { name: "Vingador Divino Corrompido" },
    { name: "Sombra do Fim dos Tempos" },
    { name: "Mestre da Desolação" },
    { name: "炎の破滅 (Honoo no Hametsu)", translation: "Ruína de Fogo" },
    { name: "氷の破滅 (Koori no Hametsu)", translation: "Ruína de Gelo" },
    { name: "雷の破滅 (Kaminari no Hametsu)", translation: "Ruína do Trovão" },
    { name: "大破滅の使者 (Dai Hametsu no Shisha)", translation: "Grande Emissário da Ruína" }
  ],
  "Deus da Destruição": [
    { name: "O Fim de Tudo" },
    { name: "Destruidor de Galáxias" },
    { name: "Vazio Encarnado" },
    { name: "Aquele que não se nomeia" },
    { name: "Eternidade Sombria" },
    { name: "A Ruína" },
    { name: "破壊神 (Hakaishin)", translation: "Deus da Destruição" },
    { name: "絶対神 (Zettaishin)", translation: "Deus Absoluto" },
    { name: "Devorador de Mundos" },
    { name: "Apocalipse Vivo" },
    { name: "Deus da Destruição de Fogo" },
    { name: "Deus da Destruição de Gelo" },
    { name: "Deus da Destruição Elétrico" },
    { name: "Deus da Destruição Sombrio" },
    { name: "Supremo Deus da Destruição" },
    { name: "Deus da Destruição Colossal" },
    { name: "Deus da Destruição Blindado" },
    { name: "Deus da Destruição Mutante" },
    { name: "Deus da Destruição Metálico" },
    { name: "Deus da Destruição Venenoso" },
    { name: "Deus da Destruição Ilusionista" },
    { name: "Deus da Destruição Dourado" },
    { name: "Deus da Destruição de Cristal" },
    { name: "Deus da Destruição Espectral" },
    { name: "Deus da Destruição Ancestral" },
    { name: "Deus da Destruição de Magma" },
    { name: "Deus da Destruição Corrompido" },
    { name: "O Desfazedouro" },
    { name: "Estrela Negra" },
    { name: "Colapso Final" },
    { name: "Senhor da Matéria Escura" },
    { name: "O Fim Inevitável" },
    { name: "Aniquilador Universal" },
    { name: "Paradoxo Destrutivo" },
    { name: "Entropia Pura" },
    { name: "O Abismo Olhando de Volta" },
    { name: "炎の破壊神 (Honoo no Hakaishin)", translation: "Deus da Destruição de Fogo" },
    { name: "氷の破壊神 (Koori no Hakaishin)", translation: "Deus da Destruição de Gelo" },
    { name: "雷の破壊神 (Kaminari no Hakaishin)", translation: "Deus da Destruição do Trovão" },
    { name: "真の破壊神 (Shin no Hakaishin)", translation: "Verdadeiro Deus da Destruição" }
  ]
};

const genericVariations = [
  { prefix: "", suffix: ", o Implacável" },
  { prefix: "Grande ", suffix: "" },
  { prefix: "", suffix: " Esfomeado" },
  { prefix: "Filhote de ", suffix: "" },
  { prefix: "Velho ", suffix: "" },
  { prefix: "", suffix: " de Sangue Mágico" },
  { prefix: "暗黒の (Ankoku no) ", suffix: "", translation: "Líder das Trevas {name}" },
  { prefix: "伝説の (Densetsu no) ", suffix: "", translation: "{name} Lendário" },
  { prefix: "", suffix: " Assustado" },
  { prefix: "Rei ", suffix: "" }
];

export { genericVariations };

export function getMonsterVariation(baseName: string): { name: string; translation?: string } {
  if (monstersDatabase[baseName]) {
    const list = monstersDatabase[baseName];
    return list[Math.floor(Math.random() * list.length)];
  }

  // Fallback para outros monstros (10 combinações processadas)
  const genericList = genericVariations.map(gen => {
    let resultName = `${gen.prefix}${baseName}${gen.suffix}`;
    let resultTrans = gen.translation ? gen.translation.replace("{name}", baseName) : undefined;
    return { name: resultName, translation: resultTrans };
  });

  return genericList[Math.floor(Math.random() * genericList.length)];
}
